-- Starting A-Z category taxonomy, styled after Polokwane.info's breadth.
-- Fixed/hand-curated on purpose (see plan) — the routine assigns businesses
-- to these, it never invents new categories, to keep nav/SEO structure stable.

INSERT INTO categories (slug, name) VALUES
  ('accommodation', 'Accommodation'),
  ('accountants', 'Accountants'),
  ('attorneys-legal', 'Attorneys & Legal Services'),
  ('automotive-repairs', 'Automotive & Repairs'),
  ('bakeries', 'Bakeries'),
  ('beauty-hair-salons', 'Beauty & Hair Salons'),
  ('building-construction', 'Building & Construction'),
  ('butcheries', 'Butcheries'),
  ('car-dealerships', 'Car Dealerships'),
  ('catering', 'Catering'),
  ('cleaning-services', 'Cleaning Services'),
  ('clinics-healthcare', 'Clinics & Healthcare'),
  ('computer-it-services', 'Computer & IT Services'),
  ('dentists', 'Dentists'),
  ('doctors-gps', 'Doctors & GPs'),
  ('driving-schools', 'Driving Schools'),
  ('electricians', 'Electricians'),
  ('estate-agents', 'Estate Agents'),
  ('events-function-venues', 'Events & Function Venues'),
  ('fitness-gyms', 'Fitness & Gyms'),
  ('florists', 'Florists'),
  ('funeral-services', 'Funeral Services'),
  ('furniture-homeware', 'Furniture & Homeware'),
  ('hardware-stores', 'Hardware Stores'),
  ('hotels', 'Hotels'),
  ('insurance', 'Insurance'),
  ('locksmiths', 'Locksmiths'),
  ('motor-spares', 'Motor Spares'),
  ('nurseries-garden-centres', 'Nurseries & Garden Centres'),
  ('opticians', 'Opticians'),
  ('pest-control', 'Pest Control'),
  ('pharmacies', 'Pharmacies'),
  ('photographers', 'Photographers'),
  ('physiotherapists', 'Physiotherapists'),
  ('plumbers', 'Plumbers'),
  ('printing-services', 'Printing Services'),
  ('restaurants-takeaways', 'Restaurants & Takeaways'),
  ('schools-education', 'Schools & Education'),
  ('security-services', 'Security Services'),
  ('spas-wellness', 'Spas & Wellness'),
  ('tow-trucks-roadside', 'Tow Trucks & Roadside Assistance'),
  ('travel-agents', 'Travel Agents'),
  ('vets-animal-care', 'Vets & Animal Care'),
  ('wedding-services', 'Wedding Services');
