-- Round-4 batch (efficiency-focused re-run). Every entry verified against
-- 2+ independent, branch-appropriate sources with mandatory phone+address.
-- This file deliberately excludes a large number of leads that several
-- research agents reported as "confirmed" but which, on review, only cited
-- a single source (the mall's own tenant page) or a mismatched second
-- source (e.g. a different branch of the same chain in a different
-- suburb) -- those were held back rather than published under-verified.

-- New shopping centres

INSERT OR IGNORE INTO shopping_centers (slug, name, suburb_id, address, lat, lng, source_urls, type)
VALUES ('delft-mall-delft', 'Delft Mall', (SELECT id FROM suburbs WHERE slug = 'delft'), 'Cnr Hindle Rd, Delft, Cape Town, 7100', NULL, NULL, '["https://delft-mall.co.za/contact-us/", "https://clicks.co.za/store/Delft/1859"]', 'mall');

INSERT OR IGNORE INTO shopping_centers (slug, name, suburb_id, address, lat, lng, source_urls, type)
VALUES ('eerste-rivier-mall-eerste-river', 'Eerste Rivier Mall', (SELECT id FROM suburbs WHERE slug = 'eerste-river'), 'Corner of Plein Street and Van Riebeeck Road, Eerste River, Cape Town, 7100', NULL, NULL, '["https://www.exemplarreit.co.za/news/Exemplar%E2%80%99s_Acquisition_of_Eerste_Rivier_Mall_complete__/41", "https://clicks.co.za/store/Eerste-River-Mall/2232"]', 'mall');

INSERT OR IGNORE INTO shopping_centers (slug, name, suburb_id, address, lat, lng, source_urls, type)
VALUES ('howard-centre-pinelands', 'Howard Centre', (SELECT id FROM suburbs WHERE slug = 'pinelands'), 'Corner Forest Drive & Howard Drive, Pinelands, Cape Town', NULL, NULL, '["https://www.anvilproperty.co.za/commercial-property/retail/to-rent/pinelands/howard-centre-pinelands-cape-town-3094/shop-g33-32698", "https://www.sa-venues.com/things-to-do/westerncape/howard-centre/"]', 'mall');

INSERT OR IGNORE INTO shopping_centers (slug, name, suburb_id, address, lat, lng, source_urls, type)
VALUES ('belhar-airport-shopping-centre-belhar', 'Belhar Airport Shopping Centre', (SELECT id FROM suburbs WHERE slug = 'belhar'), 'Corner of Stellenbosch Arterial Road (M12) and Belhar Drive (M180), Belhar, Cape Town', NULL, NULL, '["https://absa.banklocationmaps.com/en/branch/930582-absa-branch-shop-23-65-airport-shopping-centre-cnr-belhar-drive-m180-and-stellenbosch-arterial-road-m12", "https://nedbank.banklocationmaps.com/en/branch/956844-nedbank-branch-shop-25-airport-mall-cnr-stellenbosch-arterial-road-and-belhar-drive"]', 'mall');

INSERT OR IGNORE INTO shopping_centers (slug, name, suburb_id, address, lat, lng, source_urls, type)
VALUES ('vangate-mall-athlone', 'Vangate Mall', (SELECT id FROM suburbs WHERE slug = 'athlone'), 'Cnr Vanguard Drive & Klipfontein Road, Athlone, Cape Town, 7764', NULL, NULL, '["https://www.tiendeo.co.za/stores/cape-town/cell-c-shop-vangate-mall-corners-vanguard-drive-and-klipfontein-road-and-the-n-athlone/39751", "https://nearbyza.com/banking/bank/vangate-mall-vanguard-drive-athlone-cape-town"]', 'mall');

INSERT OR IGNORE INTO shopping_centers (slug, name, suburb_id, address, lat, lng, source_urls, type)
VALUES ('liberty-promenade-mitchells-plain', 'Liberty Promenade', (SELECT id FROM suburbs WHERE slug = 'mitchells-plain'), 'Cnr AZ Berman Drive & Morgenster Road, Mitchells Plain, Cape Town, 7785', NULL, NULL, '["https://www.sa-venues.com/things-to-do/westerncape/go-shopping-at-the-liberty-promenade/", "https://getoccupi.com/malls/liberty-promenade-shopping-centre"]', 'mall');

INSERT OR IGNORE INTO shopping_centers (slug, name, suburb_id, address, lat, lng, source_urls, type)
VALUES ('khayelitsha-mall-khayelitsha', 'Khayelitsha Mall (KCT Mall)', (SELECT id FROM suburbs WHERE slug = 'khayelitsha'), 'Julius Tsolo Street, Khayelitsha, Cape Town, 7784', NULL, NULL, '["https://clicks.co.za/store/KCT-Mall-Khayelitsha/2068", "https://www.news24.com/business/r100m-mall-opens-in-khayelitsha-20051124"]', 'mall');

INSERT OR IGNORE INTO shopping_centers (slug, name, suburb_id, address, lat, lng, source_urls, type)
VALUES ('gugulethu-square-gugulethu', 'Gugulethu Square', (SELECT id FROM suburbs WHERE slug = 'gugulethu'), 'Cnr NY1, NY3 & NY6, Gugulethu, Cape Town, 7750', NULL, NULL, '["https://www.vukile.co.za/property/gugulethu-square/", "https://www.bizcommunity.com/Article/196/460/41431.html"]', 'mall');

-- Riverlands Mall (observatory) tenants

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('neovision-optometrist-observatory', 'Neovision Optometrist', (SELECT id FROM suburbs WHERE slug='observatory'), (SELECT id FROM shopping_centers WHERE slug='riverlands-mall-observatory'), 'Shop 15, Riverlands Mall, 51 Gogosoa St, Observatory, Cape Town', '021 201 1471', NULL, NULL, 'Neovision Optometrist is an optometry practice offering eye tests and a range of frames and sunglasses, trading from Riverlands Mall.', NULL, NULL, '["https://riverlands.capetown/mall/", "https://www.neovision.co.za/stores/riverlands/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='neovision-optometrist-observatory'), (SELECT id FROM categories WHERE slug='opticians'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('postnet-riverlands-observatory', 'PostNet Riverlands', (SELECT id FROM suburbs WHERE slug='observatory'), (SELECT id FROM shopping_centers WHERE slug='riverlands-mall-observatory'), 'Shop G37, Riverlands Mall, 51 Gogosoa St, Observatory, Cape Town', '060 819 2040', NULL, NULL, 'PostNet Riverlands offers courier, printing, copying and mailbox services, trading from Riverlands Mall.', NULL, NULL, '["https://riverlands.capetown/mall/", "https://postnet.co.za/stores/observatoryriverlands"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='postnet-riverlands-observatory'), (SELECT id FROM categories WHERE slug='printing-services'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('body20-riverlands-observatory', 'Body20 Riverlands', (SELECT id FROM suburbs WHERE slug='observatory'), (SELECT id FROM shopping_centers WHERE slug='riverlands-mall-observatory'), 'Shop G04, Riverlands Mall, 51 Gogosoa St, Observatory, Cape Town', '064 942 9911', NULL, NULL, 'Body20 Riverlands is an EMS (electro muscle stimulation) personal training studio, trading from Riverlands Mall.', NULL, NULL, '["https://riverlands.capetown/mall/shop-g04/", "https://body20.co.za/studio-riverlands.php"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='body20-riverlands-observatory'), (SELECT id FROM categories WHERE slug='fitness-gyms'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('royal-tea-riverlands-observatory', 'Royal Tea', (SELECT id FROM suburbs WHERE slug='observatory'), (SELECT id FROM shopping_centers WHERE slug='riverlands-mall-observatory'), 'Shop G40, Riverlands Mall, 51 Gogosoa St, Observatory, Cape Town', '079 829 9418', NULL, NULL, 'Royal Tea is a tea bar bringing contemporary Chinese tea culture to South Africa, trading from Riverlands Mall.', NULL, NULL, '["https://riverlands.capetown/mall/", "https://magicpin.com/south-africa/Cape-Town/Observatory-Ct/Other/Royal-Tea-Riverlands-Mall/store/241c23a"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='royal-tea-riverlands-observatory'), (SELECT id FROM categories WHERE slug='restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('boa-beauty-bar-observatory', 'BOA Beauty Bar', (SELECT id FROM suburbs WHERE slug='observatory'), (SELECT id FROM shopping_centers WHERE slug='riverlands-mall-observatory'), 'Shop G11, Riverlands Mall, 51 Gogosoa St, Observatory, Cape Town', '066 065 2899', NULL, NULL, 'BOA Beauty Bar is a nail and beauty salon trading from Riverlands Mall.', NULL, NULL, '["https://riverlands.capetown/mall/", "https://www.fresha.com/a/boa-beauty-bar-riverlands-mall-cape-town-51-gogosoa-street-nyyip2vk"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='boa-beauty-bar-observatory'), (SELECT id FROM categories WHERE slug='beauty-hair-salons'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('skin-recode-observatory', 'Skin Recode', (SELECT id FROM suburbs WHERE slug='observatory'), (SELECT id FROM shopping_centers WHERE slug='riverlands-mall-observatory'), 'Shop G51, Riverlands Mall, 51 Gogosoa St, Observatory, Cape Town', '021 065 1724', NULL, NULL, 'Skin Recode is an aesthetics and skincare clinic offering personalised facial and laser treatments, trading from Riverlands Mall.', NULL, NULL, '["https://riverlands.capetown/mall/shop-g51/", "https://skinrecode.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='skin-recode-observatory'), (SELECT id FROM categories WHERE slug='spas-wellness'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('gary-rom-man-observatory', 'Gary Rom Man', (SELECT id FROM suburbs WHERE slug='observatory'), (SELECT id FROM shopping_centers WHERE slug='riverlands-mall-observatory'), 'Shop G44, Riverlands Mall, 51 Gogosoa St, Observatory, Cape Town', '021 879 5160', NULL, NULL, 'Gary Rom Man is a men''s barbershop offering haircuts, beard trims and hot towel shaves, trading from Riverlands Mall.', NULL, NULL, '["https://riverlands.capetown/mall/", "https://garyromman.co.za/riverlands/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='gary-rom-man-observatory'), (SELECT id FROM categories WHERE slug='beauty-hair-salons'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('asian-mart-riverlands-observatory', 'Asian Mart', (SELECT id FROM suburbs WHERE slug='observatory'), (SELECT id FROM shopping_centers WHERE slug='riverlands-mall-observatory'), 'Shop G38, Riverlands Mall, 51 Gogosoa St, Observatory, Cape Town', '069 984 2818', NULL, NULL, 'Asian Mart is an Asian grocery store selling food products, snacks, condiments and tableware, trading from Riverlands Mall.', NULL, NULL, '["https://riverlands.capetown/mall/", "https://www.tiktok.com/@_daiyabrahams_/video/7510253367176777016"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='asian-mart-riverlands-observatory'), (SELECT id FROM categories WHERE slug='supermarkets-groceries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('chops-biltong-riverlands-observatory', 'Chops Biltong', (SELECT id FROM suburbs WHERE slug='observatory'), (SELECT id FROM shopping_centers WHERE slug='riverlands-mall-observatory'), 'Shop G31, Riverlands Mall, 51 Gogosoa St, Observatory, Cape Town', '066 036 5347', NULL, NULL, 'Chops Biltong sells traditional South African beef and game biltong, droewors and dried snacks, trading from Riverlands Mall.', NULL, NULL, '["https://riverlands.capetown/mall/", "https://www.brabys.com/za/chops-biltong"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='chops-biltong-riverlands-observatory'), (SELECT id FROM categories WHERE slug='general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('the-tux-tailor-riverlands-observatory', 'The Tux Tailor', (SELECT id FROM suburbs WHERE slug='observatory'), (SELECT id FROM shopping_centers WHERE slug='riverlands-mall-observatory'), 'Shop G32, Riverlands Mall, 51 Gogosoa St, Observatory, Cape Town', '069 513 3386', NULL, NULL, 'The Tux Tailor offers tailoring and alteration services for men''s, ladies'' and children''s clothing, trading from Riverlands Mall.', NULL, NULL, '["https://riverlands.capetown/mall/", "https://www.instagram.com/the_tux_tailor_riverlandsmall/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='the-tux-tailor-riverlands-observatory'), (SELECT id FROM categories WHERE slug='general-retail'), 1);

-- The Point (sea-point) tenants

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('la-frontiere-zimborders-sea-point', 'La Frontiere & Zimborders', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Suite 701b, 7th Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '087 470 0081', NULL, NULL, 'La Frontiere & Zimborders is a border-management and cross-border logistics consultancy, trading from The Point in Sea Point.', NULL, NULL, '["https://thepointmall.co.za/la-frontiere-zimborders/", "https://www.lafrontieregroup.com/contact/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='la-frontiere-zimborders-sea-point'), (SELECT id FROM categories WHERE slug='business-consulting'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('hci-sea-point', 'HCI (Hosken Consolidated Investments)', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Suite 801, 8th Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 481 7560', 'https://www.hci.co.za', NULL, 'HCI is a JSE-listed investment holding company, headquartered at The Point in Sea Point.', NULL, NULL, '["https://thepointmall.co.za/", "https://www.hci.co.za/contact-us/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='hci-sea-point'), (SELECT id FROM categories WHERE slug='financial-investment-services'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('platinum-hospitality-holdings-sea-point', 'Platinum Hospitality Holdings', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Suite 606, 6th Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 430 8668', NULL, NULL, 'Platinum Hospitality Holdings is a hotel management and investment holding company, headquartered at The Point in Sea Point.', NULL, NULL, '["https://thepointmall.co.za/merchant/platinum-hospitality-holdings/", "https://phholdings.co.za/contact/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='platinum-hospitality-holdings-sea-point'), (SELECT id FROM categories WHERE slug='business-consulting'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('multiqs-sea-point', 'MultiQS', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Suite 407, The Point, 76 Regent Road, Sea Point, Cape Town', '087 740 5270', 'https://multiqs.co.za', 'info@multiqs.co.za', 'MultiQS is a quantity surveying practice, trading from The Point in Sea Point.', NULL, NULL, '["https://thepointmall.co.za/", "https://multiqs.co.za/contact/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='multiqs-sea-point'), (SELECT id FROM categories WHERE slug='business-consulting'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('rsaweb-sea-point', 'RSAWEB', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Suite 401 & 405, 4th Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '087 470 0000', 'https://rsaweb.co.za', NULL, 'RSAWEB is an internet service provider offering fibre, connectivity and cloud infrastructure, with an office at The Point in Sea Point.', NULL, NULL, '["https://thepointmall.co.za/", "https://shop.rsaweb.co.za/business-contact-us/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='rsaweb-sea-point'), (SELECT id FROM categories WHERE slug='computer-it-services'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('basi-pilates-academy-sea-point', 'BASI Pilates Academy', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Suite 310, 3rd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '060 775 7603', 'https://basipilatescapetown.co.za', NULL, 'BASI Pilates Academy is a Pilates studio offering private, semi-private and teacher-training sessions, trading from The Point in Sea Point.', NULL, NULL, '["https://thepointmall.co.za/merchant/basi-pilates/", "https://basipilatescapetown.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='basi-pilates-academy-sea-point'), (SELECT id FROM categories WHERE slug='fitness-gyms'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sweat1000-sea-point', 'SWEAT1000', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), '3rd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 439 9903', 'https://sweat1000.com', 'seapoint@sweat1000.com', 'SWEAT1000 is a specialised weight and endurance athletic training fitness studio, trading from The Point in Sea Point.', NULL, NULL, '["https://sweat1000.com/?studios=sea-point", "http://www.findglocal.com/ZA/Sea-Point/108962222472145/SWEAT-1000"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='sweat1000-sea-point'), (SELECT id FROM categories WHERE slug='fitness-gyms'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('buc-fitness-club-sea-point', 'BUC Fitness Club', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), '3rd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 439 9903', NULL, 'info@bucfitnessclub.com', 'BUC Fitness Club is a boutique fitness and wellness facility housing personal training, biokinetics and a Pilates studio, trading from The Point in Sea Point.', NULL, NULL, '["https://thepointmall.co.za/merchant/buc/", "https://www.beautynailhairsalons.com/ZA/Cape-Town/32641009522/BUC-Fitness-Club---World-Class-Boutique-Fitness-Club"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='buc-fitness-club-sea-point'), (SELECT id FROM categories WHERE slug='fitness-gyms'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('inhouse-design-studio-sea-point', 'Inhouse Design Studio', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Suite 301, 3rd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 488 2400', 'https://www.inhouse.ws', NULL, 'Inhouse Design Studio is an interior and architectural design practice, trading from The Point in Sea Point.', NULL, NULL, '["https://www.inhouse.ws/contact-us", "https://capebpo.org.za/listings/inhouse-design-studio/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='inhouse-design-studio-sea-point'), (SELECT id FROM categories WHERE slug='business-consulting'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sportsmans-warehouse-sea-point', 'Sportsmans Warehouse', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 09, 1st Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 439 7172', 'https://www.sportsmanswarehouse.co.za', NULL, 'Sportsmans Warehouse is a sporting goods and outdoor equipment retailer, trading from The Point in Sea Point.', NULL, NULL, '["https://www.sportsmanswarehouse.co.za/store/the-point-shopping-mall-sea-point/", "https://za.africabz.com/western-cape/sportsmans-warehouse-53856"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='sportsmans-warehouse-sea-point'), (SELECT id FROM categories WHERE slug='general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('pick-n-pay-clothing-sea-point', 'Pick n Pay Clothing', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 07, 1st Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 439 7032', NULL, NULL, 'Pick n Pay Clothing is a family clothing retailer, trading from The Point in Sea Point.', NULL, NULL, '["https://thepointmall.co.za/merchant/pick-n-pay-clothing/", "https://my-catalogue.co.za/stores/sea-point/pick-n-pay-clothing/76-regent-road"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='pick-n-pay-clothing-sea-point'), (SELECT id FROM categories WHERE slug='fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('dr-zoran-aleksic-ophthalmologist-sea-point', 'Dr Zoran Aleksic Ophthalmologist', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Suite 701a, 7th Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 426 4842', 'https://www.eyesurgery.co.za', NULL, 'This practice is an ophthalmology and eye-surgery clinic offering cataract and laser refractive procedures, trading from The Point in Sea Point.', NULL, NULL, '["https://www.medpages.info/sf/index.php?page=organisation&orgcode=134064", "https://www.eyesurgery.co.za/contact-us"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='dr-zoran-aleksic-ophthalmologist-sea-point'), (SELECT id FROM categories WHERE slug='clinics-healthcare'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('apnisleep-sea-point', 'Apnisleep', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Suite 304, 3rd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '087 702 6885', 'http://www.apnisleep.co.za', NULL, 'Apnisleep provides medically guided treatment for snoring and sleep apnea, trading from The Point in Sea Point.', NULL, NULL, '["http://www.apnisleep.co.za/call-us/", "https://www.cavaonline.org/listing/apnisleep-cape-town-snoring-and-sleep-apnea-solutions-2/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='apnisleep-sea-point'), (SELECT id FROM categories WHERE slug='clinics-healthcare'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sorbet-sea-point-the-point-sea-point', 'Sorbet Sea Point', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 17 & 18, 2nd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 433 1306', 'https://sorbet.co.za', 'thepoint@sorbet.co.za', 'Sorbet Sea Point is a beauty and nail salon, trading from The Point in Sea Point.', NULL, NULL, '["https://thepointmall.co.za/merchant/sorbet-sea-point/", "https://za.africabz.com/western-cape/sorbet-the-point-110599"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='sorbet-sea-point-the-point-sea-point'), (SELECT id FROM categories WHERE slug='beauty-hair-salons'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('optismile-dental-care-sea-point', 'OptiSmile Dental Care', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Suite 303, 3rd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '087 702 6886', 'https://optismile.co.za', NULL, 'OptiSmile Dental Care is a multi-speciality dental practice offering general and cosmetic dentistry, trading from The Point in Sea Point.', NULL, NULL, '["https://www.hotfrog.co.za/company/1099851566575616/optismile-advanced-dentistry-and-implant-centre/cape-town/dental-care", "https://seapointcid.org/places/optismile-advanced-dentistry-and-implant-centre/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='optismile-dental-care-sea-point'), (SELECT id FROM categories WHERE slug='dentists'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('yemaya-hair-spa-sea-point', 'Yemaya Hair & Spa', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 14, 2nd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 439 2266', 'https://www.yemaya.co.za', NULL, 'Yemaya Hair & Spa is a hair and beauty spa, trading from The Point in Sea Point.', NULL, NULL, '["https://www.yemaya.co.za/contact-us/", "https://www.tripadvisor.com/LocationPhotoDirectLink-g15134971-d12460739-i291584830-Yemaya_Spa_Hair-Sea_Point_Western_Cape.html"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='yemaya-hair-spa-sea-point'), (SELECT id FROM categories WHERE slug='beauty-hair-salons'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('healthpoint-sea-point', 'Healthpoint', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Suite 308b, 3rd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 001 3308', NULL, NULL, 'Healthpoint is a family medicine, travel medicine and aesthetics clinic, trading from The Point in Sea Point.', NULL, NULL, '["https://www.medpages.info/sf/index.php?page=organisation&orgcode=242218", "https://thepointmall.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='healthpoint-sea-point'), (SELECT id FROM categories WHERE slug='clinics-healthcare'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('virtus-medical-sea-point', 'Virtus Medical', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), '3rd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 439 1555', 'https://www.virtusmed.co.za', 'info@virtusmed.co.za', 'Virtus Medical is a general practice offering family medicine and health promotion services, trading from The Point in Sea Point.', NULL, NULL, '["https://www.virtusmed.co.za/", "https://za.africabz.com/western-cape/virtus-health-medical-117578"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='virtus-medical-sea-point'), (SELECT id FROM categories WHERE slug='doctors-gps'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('bergman-ross-partners-radiology-sea-point', 'Bergman Ross & Partners Radiology', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Suite 306, 3rd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 110 5777', 'https://bergmanross.co.za', NULL, 'Bergman Ross & Partners is a radiology practice offering mammography, ultrasound, CT and MRI services, trading from The Point in Sea Point.', NULL, NULL, '["https://bergmanross.co.za/branches/seapoint/", "https://www.medpages.info/sf/index.php?page=organisation&orgcode=412612"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='bergman-ross-partners-radiology-sea-point'), (SELECT id FROM categories WHERE slug='clinics-healthcare'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('chiropractic-health-centre-sea-point', 'The Chiropractic Health Centre', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), '3rd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 439 8898', 'https://www.chiropractor.co.za', 'atlantic@chiropractor.co.za', 'The Chiropractic Health Centre offers chiropractic and sports massage treatment, trading from The Point in Sea Point.', NULL, NULL, '["https://www.chiropractor.co.za/location-atlantic-chiropractic/", "https://www.medpages.info/sf/index.php?page=organisation&orgcode=200407"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='chiropractic-health-centre-sea-point'), (SELECT id FROM categories WHERE slug='physiotherapists'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('discovery-store-sea-point', 'Discovery Store', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 05, Ground Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 527 1073', 'https://www.discovery.co.za', NULL, 'Discovery Store is a walk-in branch for Discovery insurance, medical scheme and Vitality services, trading from The Point in Sea Point.', NULL, NULL, '["https://hombaze.co.za/discovery-store---sea-point-3909589226047898293/", "https://za.africabz.com/western-cape/discovery-store-54466"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='discovery-store-sea-point'), (SELECT id FROM categories WHERE slug='insurance'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('nedbank-the-point-sea-point', 'Nedbank', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 23, 2nd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '080 011 0929', 'https://www.nedbank.co.za', NULL, 'Nedbank is a retail bank branch, trading from The Point in Sea Point.', NULL, NULL, '["https://nedbank.banklocationmaps.co.za/en/branch/956876-nedbank-branch-shop-23-2nd-floor-the-point-shopping-centre-76-regent-road", "https://nearbyza.com/place/nedbank-sea-point-cape-town-1"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='nedbank-the-point-sea-point'), (SELECT id FROM categories WHERE slug='financial-investment-services'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('checkers-liquor-the-point-sea-point', 'Checkers Liquor', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 01, Ground Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 433 2768', NULL, NULL, 'Checkers Liquor is a liquor store, trading from The Point in Sea Point.', NULL, NULL, '["https://south-africa.searchinafrica.com/business/6120949/south-africa/western-cape/cape-town/sea-point/regent-rd/liquor-stores/checkers-liquor-shop", "http://charlesfox.co.za/stockist/checkers-liquorshop-sea-point/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='checkers-liquor-the-point-sea-point'), (SELECT id FROM categories WHERE slug='liquor-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('checkers-the-point-sea-point', 'Checkers', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 01, Ground Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 430 4680', NULL, NULL, 'Checkers is a full-service supermarket, trading from The Point in Sea Point.', NULL, NULL, '["https://wanderlog.com/place/details/2002596/checkers-sea-point", "https://www.africanadvice.com/1099752/Supermarkets_And_Grocery_Stores/Cape_Town/Checkers_-_Sea_Point/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='checkers-the-point-sea-point'), (SELECT id FROM categories WHERE slug='general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('nv-80-grill-bar-sea-point', 'NV-80 Grill & Bar', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 08, 1st Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 439 7112', 'https://nv-80.co.za', NULL, 'NV-80 Grill & Bar is a steak and seafood restaurant, trading from The Point in Sea Point.', NULL, NULL, '["https://nv-80.co.za", "https://thepointmall.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='nv-80-grill-bar-sea-point'), (SELECT id FROM categories WHERE slug='restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('schoon-the-point-sea-point', 'Schoon', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Ground Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 569 4663', 'http://schoon.co.za', 'thepoint@schoon.co.za', 'Schoon is an artisan bakery selling freshly baked bread and pastries, trading from The Point in Sea Point.', NULL, NULL, '["http://schoon.co.za/", "https://thepointmall.co.za/merchant/schoon/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='schoon-the-point-sea-point'), (SELECT id FROM categories WHERE slug='bakeries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('wellness-warehouse-sea-point', 'Wellness Warehouse', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 13, 2nd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 434 0460', 'https://www.wellnesswarehouse.com', NULL, 'Wellness Warehouse is a health, wellness and natural beauty products retailer, trading from The Point in Sea Point.', NULL, NULL, '["https://www.medpages.info/sf/index.php?page=organisation&orgcode=320068", "https://www.phytoceutics.com/stores/wellness-warehouse-sea-point/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='wellness-warehouse-sea-point'), (SELECT id FROM categories WHERE slug='general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('jj-cale-premiere-tobacconist-sea-point', 'JJ Cale Premiere Tobacconist', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 22, 2nd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '087 096 0324', 'https://jjcale.co.za', NULL, 'JJ Cale Premiere Tobacconist sells premium cigars, tobacco products and smoking accessories, trading from The Point in Sea Point.', NULL, NULL, '["https://jjcale.co.za/stores/", "https://thepointmall.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='jj-cale-premiere-tobacconist-sea-point'), (SELECT id FROM categories WHERE slug='general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('absolute-pets-the-point-sea-point', 'Absolute Pets', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 13B, The Point, 76 Regent Road, Sea Point, Cape Town', '069 513 1320', NULL, NULL, 'Absolute Pets is a pet supplies retailer, trading from The Point in Sea Point.', NULL, NULL, '["https://www.rawlovepets.co.za/pages/absolute-pets-the-point", "https://packleader.co.za/store/absolute-pets-the-point/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='absolute-pets-the-point-sea-point'), (SELECT id FROM categories WHERE slug='pet-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('dischem-pharmacy-the-point-sea-point', 'Dis-Chem Pharmacy', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 06, 1st Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 430 2100', 'https://www.dischem.co.za', 'seapointdispensary@dischem.co.za', 'Dis-Chem Pharmacy is a pharmacy and health retailer, trading from The Point in Sea Point.', NULL, NULL, '["https://www.dischem.co.za/sea-point-pharmacy", "https://www.cybo.com/ZA-biz/dis-chem-pharmacy-the-point-centre-sea"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='dischem-pharmacy-the-point-sea-point'), (SELECT id FROM categories WHERE slug='pharmacies'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('pathcare-the-point-sea-point', 'Pathcare', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Suite 308a, 3rd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 434 3006', 'https://www.pathcare.co.za', 'thepoint@pathcare.co.za', 'Pathcare is a pathology laboratory depot, trading from The Point in Sea Point.', NULL, NULL, '["https://www.pathcare.co.za/store-locations/sea-point-the-point/", "https://www.africabizinfo.com/ZA/pathcare-sea-point-medical-centre-021-434-3006"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='pathcare-the-point-sea-point'), (SELECT id FROM categories WHERE slug='clinics-healthcare'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('bootlegger-coffee-the-point-sea-point', 'Bootlegger Coffee Company', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), '2nd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 434 0060', 'https://bootlegger.coffee', NULL, 'Bootlegger Coffee Company is an all-day breakfast, lunch and coffee cafe, trading from The Point in Sea Point.', NULL, NULL, '["https://ourcafes.bootlegger.coffee/FoodDrink-CapeTown-BootleggerXSSeaPoint", "https://www.eatout.co.za/venue/bootlegger-coffee-company/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='bootlegger-coffee-the-point-sea-point'), (SELECT id FROM categories WHERE slug='restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('cellucity-the-point-sea-point', 'CelluCity', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 02, Ground Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 439 4595', 'https://the-hub.cellucity.co.za', NULL, 'CelluCity is a mobile phone and accessories retailer, trading from The Point in Sea Point.', NULL, NULL, '["https://the-hub.cellucity.co.za/locations/", "https://za.africabz.com/western-cape/cellucity-222203"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='cellucity-the-point-sea-point'), (SELECT id FROM categories WHERE slug='mobile-phones'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('tonkil-optometrist-sea-point', 'Tonkil Optometrist', (SELECT id FROM suburbs WHERE slug='sea-point'), (SELECT id FROM shopping_centers WHERE slug='the-point-sea-point'), 'Shop 12, 2nd Floor, The Point, 76 Regent Road, Sea Point, Cape Town', '021 439 5472', 'https://tonkiloptometrist.co.za', 'seapoint@tonkiloptometrist.co.za', 'Tonkil Optometrist is a boutique optometry practice, trading from The Point in Sea Point.', NULL, NULL, '["https://tonkiloptometrist.co.za/contact-us/", "https://www.medpages.info/sf/index.php?page=organisation&orgcode=403870"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='tonkil-optometrist-sea-point'), (SELECT id FROM categories WHERE slug='opticians'), 1);

-- Cape Quarter (de-waterkant) tenants -- only entries with 2 genuinely
-- independent, branch-matched sources are included

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('the-neighbourgood-cape-quarter-de-waterkant', 'The Neighbourgood', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), 'Level 1, Cape Quarter Lifestyle Village, 27 Somerset Rd, De Waterkant, Cape Town', '082 963 9600', NULL, NULL, 'The Neighbourgood is a serviced co-living and short-stay apartment accommodation provider, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.neighbourgood.co/cape-quarter-living"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='the-neighbourgood-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='accommodation'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('rain-cape-quarter-de-waterkant', 'Rain', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), '1st Floor, Cape Quarter Lifestyle Village, 27 Somerset Rd, De Waterkant, Cape Town', '081 610 1000', NULL, NULL, 'Rain is a mobile network and connectivity provider store, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.rain.co.za/store-locator"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='rain-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='mobile-phones'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('vodacom-cape-quarter-de-waterkant', 'Vodacom', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), 'Shop A08 & A09, Cape Quarter, 27 Somerset Rd, De Waterkant, Cape Town', '021 421 8228', NULL, NULL, 'Vodacom is a mobile network store, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://za.readymap.info/4/222992"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='vodacom-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='mobile-phones'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('addicted-cape-quarter-de-waterkant', 'Addicted', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), '27 Somerset Rd, De Waterkant, Cape Town', '082 908 4333', NULL, NULL, 'Addicted is a fashion boutique, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://getoccupi.com/malls/cape-quarter"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='addicted-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('campo-marzio-design-cape-quarter-de-waterkant', 'Campo Marzio Design', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), 'Piazza Level, Cape Quarter, 27 Somerset Rd, De Waterkant, Cape Town', '061 491 5151', NULL, NULL, 'Campo Marzio Design is an Italian leather goods and accessories boutique, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.campomarzio.co.za/capequarter"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='campo-marzio-design-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('jen-kahn-clothing-cape-quarter-de-waterkant', 'Jen Kahn Clothing', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), '27 Somerset Rd, De Waterkant, Cape Town', '083 397 3447', NULL, NULL, 'Jen Kahn Clothing is a fashion boutique, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://getoccupi.com/malls/cape-quarter"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='jen-kahn-clothing-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('curry-club-cape-quarter-de-waterkant', 'Curry Club', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), '27 Somerset Rd, De Waterkant, Cape Town', '021 300 3971', NULL, NULL, 'Curry Club is a restaurant, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://getoccupi.com/malls/cape-quarter"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='curry-club-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('dawn-asian-restaurant-cape-quarter-de-waterkant', 'Dawn Asian Restaurant', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), '27 Somerset Rd, De Waterkant, Cape Town', '069 615 9537', NULL, NULL, 'Dawn Asian Restaurant is a restaurant, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://getoccupi.com/malls/cape-quarter"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='dawn-asian-restaurant-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sushi-box-cape-quarter-de-waterkant', 'Sushi Box', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), 'Shop 5, Cape Quarter, 27 Somerset Rd, De Waterkant, Cape Town', '071 282 3064', NULL, NULL, 'Sushi Box is a sushi restaurant, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.sushibox.co.za/sushibox-de-waterkant"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='sushi-box-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('bare-laser-hair-removal-cape-quarter-de-waterkant', 'Bare Laser Hair Removal Specialist', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), 'Shop 33, Cape Quarter, 27 Somerset Rd, De Waterkant, Cape Town', '021 418 0481', NULL, NULL, 'Bare Laser Hair Removal Specialist is a laser hair removal clinic, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://baresa.co.za/branch-locations-laser-hair-removal/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='bare-laser-hair-removal-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='beauty-hair-salons'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('skin-renewal-cape-quarter-de-waterkant', 'Skin Renewal', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), '2nd Floor, Cape Quarter Lifestyle Village, 27 Somerset Rd, De Waterkant, Cape Town', '021 421 9093', NULL, NULL, 'Skin Renewal is a medical aesthetics clinic, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.skinrenewal.co.za/skin-renewal-cape-quarter"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='skin-renewal-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='clinics-healthcare'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sorbet-man-cape-quarter-de-waterkant', 'Sorbet Man', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), 'Shop SHA05, Cape Quarter Lifestyle Village, 27 Somerset Rd, De Waterkant, Cape Town', '021 418 2261', NULL, NULL, 'Sorbet Man is a men''s grooming salon, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://stores.sorbetman.co.za/western-cape/cape-town/cape-quarter-lifestyle-villiage-shop-sha05"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='sorbet-man-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='beauty-hair-salons'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('threezero-cape-quarter-de-waterkant', 'ThreeZero', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), 'Cape Quarter, Dixon St entrance, 27 Somerset Rd, De Waterkant, Cape Town', '021 745 6653', NULL, NULL, 'ThreeZero is a fitness studio, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://threezero.co.za/the-studio/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='threezero-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='fitness-gyms'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('french-accent-cape-quarter-de-waterkant', 'French Accent', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), '27 Somerset Rd, De Waterkant, Cape Town', '021 762 2342', NULL, NULL, 'French Accent is a homeware and decor retailer, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://getoccupi.com/malls/cape-quarter"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='french-accent-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('miss-lyn-cape-quarter-de-waterkant', 'Miss Lyn', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), 'Shop 34, Level 0, Cape Quarter Square, 27 Somerset Rd, De Waterkant, Cape Town', '021 447 3419', NULL, NULL, 'Miss Lyn is a fine linen and home decor retailer, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://misslyn.co.za/contact-us/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='miss-lyn-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('nap-living-cape-quarter-de-waterkant', 'Nap Living', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), '27 Somerset Rd, De Waterkant, Cape Town', '021 421 6482', NULL, NULL, 'Nap Living is a homeware retailer, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://getoccupi.com/malls/cape-quarter"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='nap-living-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('absolute-pets-cape-quarter-de-waterkant', 'Absolute Pets', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), 'Shop D04, Cape Quarter Lifestyle Village, 27 Somerset Rd, De Waterkant, Cape Town', '021 421 6269', NULL, NULL, 'Absolute Pets is a pet food and accessories retailer, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.absolutepets.com/pet-stores"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='absolute-pets-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='pet-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('postnet-cape-quarter-de-waterkant', 'PostNet', (SELECT id FROM suburbs WHERE slug='de-waterkant'), (SELECT id FROM shopping_centers WHERE slug='cape-quarter-de-waterkant'), 'Shop D09, Cape Quarter Lifestyle Village, 11 Dixon St, De Waterkant, Cape Town', '021 418 1717', NULL, NULL, 'PostNet is a printing, courier and business services outlet, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.postnet.co.za/stores/cape-quarter"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='postnet-cape-quarter-de-waterkant'), (SELECT id FROM categories WHERE slug='printing-services'), 1);

-- Golden Acre (cape-town-cbd) -- only the one entry with genuine
-- independent 2-source confirmation; the rest of that batch relied on the
-- mall's own page alone and is held back

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('shoprite-golden-acre-cape-town-cbd', 'Shoprite', (SELECT id FROM suburbs WHERE slug='cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug='golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 464 7160', NULL, NULL, 'Shoprite is a supermarket, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://www.tiendeo.co.za/stores/cape-town/shoprite"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='shoprite-golden-acre-cape-town-cbd'), (SELECT id FROM categories WHERE slug='supermarkets-groceries'), 1);

-- Gardens Shopping Centre (gardens) tenants -- excludes entries that
-- turned out to be single-sourced on closer review

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('absa-bank-gardens-shopping-centre-gardens', 'ABSA', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 55, Gardens Shopping Centre, Cnr Mill and Upper Buitenkant Street, Gardens, Cape Town', '021 468 4060', NULL, NULL, 'ABSA is a bank branch offering everyday banking services, trading from Gardens Shopping Centre.', NULL, NULL, '["https://absa.banklocationmaps.co.za/en/branch/930570-absa-branch-shop-55-gardens-shopping-centre-cnr-mill-and-upper-buitenkant-street", "https://www.tiendeo.co.za/stores/cape-town/absa-bank-shop-gardens-shopping-centre-cnr-mill-and-upper-buitenkant-street-oranjezicht/60315"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='absa-bank-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='financial-investment-services'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('absolute-pets-gardens-shopping-centre-gardens', 'Absolute Pets', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 40, Gardens Shopping Centre, Mill Street, Gardens, Cape Town', '021 462 1371', NULL, NULL, 'Absolute Pets is a pet supplies and accessories retailer, trading from Gardens Shopping Centre.', NULL, NULL, '["https://za.ads4acause.com/places/cape-town/absolute-pets-gardens-shopping-centre/", "https://www.absolutepets.com/pet-stores/locator"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='absolute-pets-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='pet-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('old-khaki-gardens-shopping-centre-gardens', 'Old Khaki', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 19, Gardens Shopping Centre, Cnr Buitenkant and Mill Street, Gardens, Cape Town', '021 461 2183', NULL, NULL, 'Old Khaki is a casual clothing retailer, trading from Gardens Shopping Centre.', NULL, NULL, '["https://www.tiendeo.co.za/stores/cape-town/old-khaki-shop-gardens-centre-cnr-buitenkant-mill-st/41192", "https://www.sayellow.com/view/south-africa/old-khaki-gardens-centre-in-cape-town"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='old-khaki-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('oxford-stationers-gardens-shopping-centre-gardens', 'Oxford Stationers', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 16, Gardens Shopping Centre, Cnr Mill and Buitenkant Street, Gardens, Cape Town', '021 462 2771', NULL, NULL, 'Oxford Stationers is a stationery, books and framing retailer, trading from Gardens Shopping Centre.', NULL, NULL, '["https://mallguide.co.za/shops/view/34270/gardens-shopping-centre/oxford-stationery-books", "https://www.facebook.com/Oxford.CPT/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='oxford-stationers-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='books-stationery'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('clicks-gardens-shopping-centre-gardens', 'Clicks', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 1A, Gardens Shopping Centre, Mill Street, Gardens, Cape Town', '021 461 1077', NULL, NULL, 'Clicks is a pharmacy, health and beauty retailer, trading from Gardens Shopping Centre.', NULL, NULL, '["https://clicks.co.za/store/Gardens-Centre/112", "https://za.africabz.com/western-cape/clicks-23717"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='clicks-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='pharmacies'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('partners-hair-design-gardens-shopping-centre-gardens', 'Partners Hair Design', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 58A, Gardens Shopping Centre, Upper Buitenkant Street, Gardens, Cape Town', '021 465 7476', NULL, NULL, 'Partners Hair Design is a hair salon, trading from Gardens Shopping Centre.', NULL, NULL, '["https://partnershair.co.za/pages/partners-hair-unisex-salon-gardens-cape-town", "https://2pos.co.za/2/3162"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='partners-hair-design-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='beauty-hair-salons'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('fnb-gardens-shopping-centre-gardens', 'FNB', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 13, 1st Floor, Thebe Hoskins House, Cnr Mill and Breda Streets, Gardens, Cape Town', '087 575 9404', NULL, NULL, 'FNB is a bank branch offering everyday banking services, trading near Gardens Shopping Centre.', NULL, NULL, '["https://www.africabizinfo.com/ZA/fnb-gardens-branch-087-575-9404", "https://za.statex.info/fnb-gardens-branch-30"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='fnb-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='financial-investment-services'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('yuppiechef-gardens-shopping-centre-gardens', 'Yuppiechef', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 51, Gardens Shopping Centre, Cnr Mill and Buitenkant Street, Gardens, Cape Town', '021 201 7346', NULL, NULL, 'Yuppiechef is a kitchenware and homeware retailer, trading from Gardens Shopping Centre.', NULL, NULL, '["https://www.yuppiechef.com/store-directory.htm", "https://www.facebook.com/yuppiechefgardens/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='yuppiechef-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('wordsworth-books-gardens-shopping-centre-gardens', 'Wordsworth Books', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 9, Gardens Shopping Centre, Upper Buitenkant Street, Gardens, Cape Town', '021 461 8464', NULL, NULL, 'Wordsworth Books is an independent bookstore, trading from Gardens Shopping Centre.', NULL, NULL, '["https://za.africabz.com/western-cape/wordsworth-gardens-97091", "https://www.xpose.co.za/listings/wordsworth-booksgardens-garden-centre/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='wordsworth-books-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='books-stationery'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('urban-optik-eyecare-gardens-shopping-centre-gardens', 'Urban Optik Eyecare', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 63, Gardens Shopping Centre, Mill Street, Gardens, Cape Town', '021 206 6357', NULL, NULL, 'Urban Optik Eyecare is an optometry practice, trading from Gardens Shopping Centre.', NULL, NULL, '["https://www.urbanoptik.co.za/urban-stores", "https://www.facebook.com/urbanoptikgardenscentre/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='urban-optik-eyecare-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='opticians'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('the-real-repair-company-gardens-shopping-centre-gardens', 'The Real Repair Company', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 36A, Gardens Shopping Centre, Mill Street, Gardens, Cape Town', '082 446 6665', NULL, NULL, 'The Real Repair Company repairs smartphones, tablets and other devices, trading from Gardens Shopping Centre.', NULL, NULL, '["https://therealrepaircompany.co.za/store-locator", "https://za.africabz.com/western-cape/the-real-repair-company-353454"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='the-real-repair-company-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='computer-it-services'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('the-body-shop-gardens-shopping-centre-gardens', 'The Body Shop', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 42, Gardens Shopping Centre, Mill Street, Gardens, Cape Town', '021 465 8401', NULL, NULL, 'The Body Shop is a cosmetics and personal care retailer, trading from Gardens Shopping Centre.', NULL, NULL, '["https://www.thebodyshop.co.za/stores/gardens-centre", "https://textmap.co.za/3/4632"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='the-body-shop-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('nedbank-gardens-shopping-centre-gardens', 'Nedbank', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 64, Gardens Shopping Centre, 38 Mill Street, Gardens, Cape Town', '021 464 3940', NULL, NULL, 'Nedbank is a bank branch offering everyday banking services, trading from Gardens Shopping Centre.', NULL, NULL, '["https://nedbank.banklocationmaps.co.za/en/branch/956874-nedbank-branch-shop-64-gardens-centre-38-mill-street", "https://nearbyza.com/place/nedbank-gardens-cape-town"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='nedbank-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='financial-investment-services'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('hartlief-gourmet-gardens-shopping-centre-gardens', 'Hartlief Gourmet', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 37A-38, Gardens Shopping Centre, Mill Street, Gardens, Cape Town', '021 465 2729', NULL, NULL, 'Hartlief Gourmet is a delicatessen selling cold meats and deli products, trading from Gardens Shopping Centre.', NULL, NULL, '["https://hartlief.co.za/visit-us/gardens-deli", "https://za.africabz.com/western-cape/hartlief-deli-gardens-8384"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='hartlief-gourmet-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='butcheries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('pick-n-pay-gardens-shopping-centre-gardens', 'Pick n Pay', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Gardens Shopping Centre, 22 Mill Street, Gardens, Cape Town', '021 461 1046', NULL, NULL, 'Pick n Pay is a supermarket, trading from Gardens Shopping Centre.', NULL, NULL, '["https://www.tiendeo.co.za/stores/cape-town/pick-n-pay-mill-street-gardens-cape-town/27485", "https://vymaps.com/ZA/Pick-n-Pay-Gardens-162802/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='pick-n-pay-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='supermarkets-groceries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('postnet-gardens-shopping-centre-gardens', 'PostNet', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 50, Ground Floor, Gardens Shopping Centre, Mill Street, Gardens, Cape Town', '021 405 0220', NULL, NULL, 'PostNet is a courier, printing and mailbox services outlet, trading from Gardens Shopping Centre.', NULL, NULL, '["https://www.postnet.co.za/stores/gardensshoppingcentre", "https://hombaze.co.za/postnet-gardens-shopping-centre-7655004250681273880/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='postnet-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='printing-services'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sorbet-gardens-shopping-centre-gardens', 'Sorbet', (SELECT id FROM suburbs WHERE slug='gardens'), (SELECT id FROM shopping_centers WHERE slug='gardens-shopping-centre-gardens'), 'Shop 41, Gardens Shopping Centre, Cnr Buitenkant and Mill Street, Gardens, Cape Town', '021 462 4265', NULL, NULL, 'Sorbet is a beauty and nail salon, trading from Gardens Shopping Centre.', NULL, NULL, '["https://www.fresha.com/lvp/sorbet-salon-gardens1-mill-street-cape-town-A8PzVv", "https://stores.salonssorbet.co.za/western-cape/cape-town/gardens-shopping-centre-upper-level-shop-58"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug='sorbet-gardens-shopping-centre-gardens'), (SELECT id FROM categories WHERE slug='beauty-hair-salons'), 1);

-- Cape Flats / townships tenants

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin, shopping_center_id) VALUES
('ackermans-vangate-mall-athlone', 'Ackermans Vangate Mall', (SELECT id FROM suburbs WHERE slug = 'athlone'), 'Shop 13, Vangate Mall, Vanguard Drive, Athlone, Cape Town, 7764', '021 633 5537', NULL, NULL, 'Ackermans is a clothing, footwear and homeware retail chain store operating at Vangate Mall in Athlone.', NULL, NULL, '["https://my-catalogue.co.za/stores/athlone/ackermans/van-gate-mall-van-gate-drive", "https://www.sayellow.com/view/south-africa/ackermans-athlone-vangate-mall-in-cape-town"]', 'published', 'agent_research', (SELECT id FROM shopping_centers WHERE slug = 'vangate-mall-athlone'));
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'ackermans-vangate-mall-athlone'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin, shopping_center_id) VALUES
('woolworths-vangate-mall-athlone', 'Woolworths Vangate Mall', (SELECT id FROM suburbs WHERE slug = 'athlone'), 'Shop 92, Vangate Mall (Vangate City), Vanguard Drive, Athlone, Cape Town, 7764', '021 684 2111', NULL, NULL, 'Woolworths is a clothing, food and homeware department store operating at Vangate Mall in Athlone.', NULL, NULL, '["https://www.tiendeo.co.za/stores/gordons-bay/woolworths-shop-vangate-city-vanguard-dr-athlone/40075", "https://my-catalogue.co.za/stores/athlone/woolworths/shop-92-vangate-city-vanguard-dr"]', 'published', 'agent_research', (SELECT id FROM shopping_centers WHERE slug = 'vangate-mall-athlone'));
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'woolworths-vangate-mall-athlone'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin, shopping_center_id) VALUES
('spar-vangate-mall-athlone', 'SPAR Vangate Mall', (SELECT id FROM suburbs WHERE slug = 'athlone'), 'Shop 10, Vangate Mall, Jakes Gerwel Drive, Athlone, Cape Town, 7764', '021 633 6383', NULL, NULL, 'SPAR is a supermarket operating at Vangate Mall in Athlone.', NULL, NULL, '["https://my-catalogue.co.za/stores/athlone/spar/shop-10-vanguard-mall-jakes-gerwel-drive", "https://capecolouredculture.co.za/places/visitors-guide-to-vangate-mall/"]', 'published', 'agent_research', (SELECT id FROM shopping_centers WHERE slug = 'vangate-mall-athlone'));
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'spar-vangate-mall-athlone'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin, shopping_center_id) VALUES
('pick-n-pay-qualisave-vangate-mall-athlone', 'Pick n Pay QualiSave Vangate Mall', (SELECT id FROM suburbs WHERE slug = 'athlone'), 'Vanguard Drive, Vangate Mall, Athlone, Cape Town, 7764', '021 633 1573', NULL, NULL, 'Pick n Pay QualiSave is a supermarket operating at Vangate Mall in Athlone.', NULL, NULL, '["https://my-catalogue.co.za/stores/athlone/pick-n-pay-qualisave/vanguard-drive", "https://capecolouredculture.co.za/places/visitors-guide-to-vangate-mall/"]', 'published', 'agent_research', (SELECT id FROM shopping_centers WHERE slug = 'vangate-mall-athlone'));
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'pick-n-pay-qualisave-vangate-mall-athlone'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin, shopping_center_id) VALUES
('woolworths-liberty-promenade-mitchells-plain', 'Woolworths Liberty Promenade', (SELECT id FROM suburbs WHERE slug = 'mitchells-plain'), 'Shop 23, Liberty Promenade, Cnr AZ Berman Drive & Morgenster Road, Mitchells Plain, Cape Town, 7785', '021 376 9011', NULL, NULL, 'Woolworths is a clothing, food and homeware department store operating at Liberty Promenade shopping centre in Mitchells Plain.', NULL, NULL, '["https://my-catalogue.co.za/stores/cape-town/woolworths/shop-23-promenade-mall-corner-morgenster-az-berman-drive", "https://getoccupi.com/malls/liberty-promenade-shopping-centre"]', 'published', 'agent_research', (SELECT id FROM shopping_centers WHERE slug = 'liberty-promenade-mitchells-plain'));
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'woolworths-liberty-promenade-mitchells-plain'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin, shopping_center_id) VALUES
('pick-n-pay-qualisave-liberty-promenade-mitchells-plain', 'Pick n Pay QualiSave Liberty Promenade', (SELECT id FROM suburbs WHERE slug = 'mitchells-plain'), 'Cnr AZ Berman Drive & Morgenster Road, Liberty Promenade, Mitchells Plain, Cape Town, 7785', '021 376 9260', NULL, NULL, 'Pick n Pay QualiSave is a supermarket operating at Liberty Promenade shopping centre in Mitchells Plain.', NULL, NULL, '["https://my-catalogue.co.za/stores/mitchells-plain/pick-n-pay-qualisave/cnr-az-berman-morgenster-rd", "https://getoccupi.com/malls/liberty-promenade-shopping-centre"]', 'published', 'agent_research', (SELECT id FROM shopping_centers WHERE slug = 'liberty-promenade-mitchells-plain'));
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'pick-n-pay-qualisave-liberty-promenade-mitchells-plain'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin, shopping_center_id) VALUES
('spar-khayelitsha-mall-khayelitsha', 'SPAR Khayelitsha Mall', (SELECT id FROM suburbs WHERE slug = 'khayelitsha'), 'Shop 6, KCT Mall, Walter Sisulu Street, Khayelitsha, Cape Town, 7784', '021 361 8934', NULL, NULL, 'SPAR is a supermarket operating at Khayelitsha Mall (KCT Mall) in Khayelitsha.', NULL, NULL, '["https://my-catalogue.co.za/stores/khayelitsha/spar/shop-6-kct-mall-walter-sisulu-street", "https://www.news24.com/business/r100m-mall-opens-in-khayelitsha-20051124"]', 'published', 'agent_research', (SELECT id FROM shopping_centers WHERE slug = 'khayelitsha-mall-khayelitsha'));
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'spar-khayelitsha-mall-khayelitsha'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin, shopping_center_id) VALUES
('spar-gugulethu-square-gugulethu', 'SPAR Gugulethu Square', (SELECT id FROM suburbs WHERE slug = 'gugulethu'), 'Gugulethu Square, Cnr NY1 & Gugulethu Road, Gugulethu, Cape Town, 7750', '021 638 0430', NULL, NULL, 'SPAR is a supermarket anchoring Gugulethu Square shopping centre in Gugulethu.', NULL, NULL, '["https://my-catalogue.co.za/stores/gugulethu/spar/gugulethu-square-cnr-ny1-gugulethu-roads", "https://www.vukile.co.za/property/gugulethu-square/"]', 'published', 'agent_research', (SELECT id FROM shopping_centers WHERE slug = 'gugulethu-square-gugulethu'));
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'spar-gugulethu-square-gugulethu'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);
