-- Round-5 batch (efficiency-focused re-run, strict 2-independent-source
-- verification with branch-specific matching). Covers Old Biscuit Mill,
-- Palms, Golden Acre, Cape Quarter, Victoria Wharf, Waterstone Village,
-- new shopping centres (Gordon's Bay, Strand, Westlake), Cape Flats
-- suburb discovery, and one confirmed closure.

-- Confirmed closure
UPDATE businesses SET closed_at = datetime('now')
WHERE slug = 'morituri-pizzeria-ristorante-claremont' AND closed_at IS NULL;

-- New shopping centres

INSERT OR IGNORE INTO shopping_centers (slug, name, suburb_id, address, lat, lng, source_urls, type)
VALUES ('gordons-bay-mall-gordons-bay', 'Gordon''s Bay Mall', (SELECT id FROM suburbs WHERE slug = 'gordons-bay'), 'Sir Lowry''s Pass Road, Gordon''s Bay, Cape Town, 7140', NULL, NULL, '["https://clicks.co.za/store/Gordons-Bay-/1871", "https://my-catalogue.co.za/stores/gordon-s-bay/checkers/gordon-s-bay-shopping-centre-sir-lowry-s-pass-road"]', 'mall');

INSERT OR IGNORE INTO shopping_centers (slug, name, suburb_id, address, lat, lng, source_urls, type)
VALUES ('strand-pavilion-mall-strand', 'Strand Pavilion Mall', (SELECT id FROM suburbs WHERE slug = 'strand'), 'Beach Road, Strand, Cape Town', NULL, NULL, '["http://strandpavilion.co.za/shoppingmall.htm", "https://cape-town.infoisinfo.co.za/search/restaurants-and-bars/b/strand"]', 'mall');

INSERT OR IGNORE INTO shopping_centers (slug, name, suburb_id, address, lat, lng, source_urls, type)
VALUES ('westlake-shopping-centre-westlake', 'Westlake Shopping Centre', (SELECT id FROM suburbs WHERE slug = 'westlake'), 'Westlake Drive, Westlake, Cape Town, 7945', NULL, NULL, '["https://www.westlakeshoppingcentre.co.za/shopping", "https://www.swindon.co.za/area-westlake-cape-town"]', 'mall');

-- Gordon's Bay Mall tenant (only one with a mandatory phone number)

INSERT OR IGNORE INTO businesses
  (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin)
VALUES (
  'checkers-gordons-bay-mall-gordons-bay', 'Checkers Gordon''s Bay Mall',
  (SELECT id FROM suburbs WHERE slug = 'gordons-bay'),
  (SELECT id FROM shopping_centers WHERE slug = 'gordons-bay-mall-gordons-bay'),
  'Gordon''s Bay Mall, Sir Lowry''s Pass Road, Gordon''s Bay, Cape Town, 7140', '021 856 9660', NULL, NULL,
  'Checkers Gordon''s Bay Mall is a supermarket branch of the Checkers chain, anchoring the Gordon''s Bay Mall shopping centre.',
  NULL, NULL,
  '["https://my-catalogue.co.za/stores/gordon-s-bay/checkers/gordon-s-bay-shopping-centre-sir-lowry-s-pass-road", "https://clicks.co.za/store/Gordons-Bay-/1871"]',
  'published', 'agent_research'
);
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary)
VALUES ((SELECT id FROM businesses WHERE slug = 'checkers-gordons-bay-mall-gordons-bay'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);

-- The Old Biscuit Mill (woodstock) tenants

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('espresso-lab-microroasters-woodstock', 'Espresso Lab Microroasters', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '021 447 0845', NULL, NULL, 'Espresso Lab Microroasters is a specialty coffee roaster serving traceable, sustainably sourced coffee, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/espresso-lab-microroasters/", "https://www.tripadvisor.com/Restaurant_Review-g6776544-d13183504-Reviews-Espresso_Lab_Microroaster-Woodstock_Western_Cape.html"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'espresso-lab-microroasters-woodstock'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('redemption-burgers-woodstock', 'Redemption Burgers', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '079 476 3648', NULL, NULL, 'Redemption Burgers is a rustic burger and craft beer eatery, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/redemption-burgers/", "https://www.tripadvisor.com/Restaurant_Review-g312659-d6451335-Reviews-Redemption_Burgers-Cape_Town_Central_Western_Cape.html"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'redemption-burgers-woodstock'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('design-academy-of-fashion-woodstock', 'Design Academy of Fashion', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '021 448 9379', NULL, NULL, 'Design Academy of Fashion is a private higher education provider offering an accredited fashion diploma and short courses, based at The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/design-academy-of-fashion/", "https://designacademyoffashion.com/home/contact/find-us/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'design-academy-of-fashion-woodstock'), (SELECT id FROM categories WHERE slug = 'schools-education'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('abode-woodstock', 'Abode', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '072 261 3540', NULL, NULL, 'Abode sells locally-sourced southern African craft, design, lighting and decor, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/abode/", "https://insideguide.co.za/cape-town/old-biscuit-mill/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'abode-woodstock'), (SELECT id FROM categories WHERE slug = 'furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('artformes-woodstock', 'Artformes', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '021 447 8194', NULL, NULL, 'Artformes is a contemporary sculpture gallery focused on sculptural form in contemporary African art, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/artformes/", "https://www.artformes.com/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'artformes-woodstock'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('auterra-jewellery-woodstock', 'AuTerra Jewellery', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '082 563 5086', NULL, NULL, 'AuTerra Jewellery handcrafts contemporary jewellery in gold and silver recycled from e-waste, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/auterra/", "https://auterra.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'auterra-jewellery-woodstock'), (SELECT id FROM categories WHERE slug = 'jewellers'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('botanica-jewellery-woodstock', 'Botanica Jewellery', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '021 447 8194', NULL, NULL, 'Botanica Jewellery hand-engraves and hand-carves sterling silver and gold jewellery with a Western Cape botanical theme, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/botanica-jewellery/", "https://www.botanicajewellery.com/pages/contact-us"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'botanica-jewellery-woodstock'), (SELECT id FROM categories WHERE slug = 'jewellers'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('fields-woodstock', 'Fields', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '021 741 1240', NULL, NULL, 'Fields is a contemporary menswear brand crafted in natural yarns sourced from southern Africa, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/fields/", "https://fieldsstore.com/pages/find-us"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'fields-woodstock'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('malok-woodstock', 'Malok', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '079 696 6321', NULL, NULL, 'Malok is a South African clothing brand producing feminine, natural-fabric garments, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/malok/", "https://www.instagram.com/malok_lifestyle/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'malok-woodstock'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('plush-bazaar-woodstock', 'Plush Bazaar', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '021 447 7103', NULL, NULL, 'Plush Bazaar is a hiring shop and prop/food styling studio with a curated retail section, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/plush-bazaar/", "https://plushprops.blogspot.com/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'plush-bazaar-woodstock'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('the-live-edge-woodstock', 'The Live Edge', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '071 488 0535', NULL, NULL, 'The Live Edge creates bespoke live-edge tables and decor from sustainably sourced wood, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/the-live-edge/", "https://www.theliveedge.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'the-live-edge-woodstock'), (SELECT id FROM categories WHERE slug = 'furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('colcacchio-go-woodstock', 'Col''Cacchio GO', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '021 180 0387', NULL, NULL, 'Col''Cacchio GO is a fast-casual wood-fired pizza, pasta and salad concept, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/colcacchio-go/", "https://www.colcacchio.co.za/post/old-biscuit-mill-welcomes-brand-new-col-cacchio-go-to-the-neighbourhood"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'colcacchio-go-woodstock'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('hello-indigo-halo-woodstock', 'Hello Indigo Halo', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '076 364 3518', NULL, NULL, 'Hello Indigo Halo is a retail store specialising in crystals, incense and gifts, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/hello-indigo-halo/", "https://helloindigohalo.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'hello-indigo-halo-woodstock'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('rubyyes-south-africa-woodstock', 'Rubyyes South Africa', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '021 447 1924', NULL, NULL, 'Rubyyes South Africa is a boutique selling luxury resortwear and boho-chic beachwear brands, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/rubyyes-south-africa/", "https://yesclothing.co.za/pages/about"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'rubyyes-south-africa-woodstock'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('studio-isobel-sippel-woodstock', 'Studio Isobel Sippel', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '021 447 8194', NULL, NULL, 'Studio Isobel Sippel is a textile studio producing handcrafted cushions, quilts and home textiles, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/studio-isobel-sippel/", "https://www.findglocal.com/ZA/Cape-Town/490990247663964/Studio-Isobel-Sippel"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'studio-isobel-sippel-woodstock'), (SELECT id FROM categories WHERE slug = 'furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('the-glass-bead-cabin-woodstock', 'The Glass & Bead Cabin', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '074 583 8593', NULL, NULL, 'The Glass & Bead Cabin sells beads retail and wholesale, and offers sand-carved custom glass work, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/the-glass-bead-cabin/", "https://www.beadandglasscabin.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'the-glass-bead-cabin-woodstock'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('tuska-atelier-woodstock', 'Tuska Atelier', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '021 447 8194', NULL, NULL, 'Tuska Atelier is a leather atelier handcrafting bags and accessories from cowhide, ostrich and crocodile leather, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/tuska-atelier/", "https://tuskaatelier.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'tuska-atelier-woodstock'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('big-picture-company-woodstock', 'Big Picture Company', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '021 421 8101', NULL, NULL, 'Big Picture Company is a boutique film production company servicing international commercials, based at The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/big-picture-company/", "https://www.thebigpicture.co.za/contact"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'big-picture-company-woodstock'), (SELECT id FROM categories WHERE slug = 'marketing-advertising'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('la-marzocco-south-africa-woodstock', 'La Marzocco South Africa', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-old-biscuit-mill-woodstock'), '373-375 Albert Road, Woodstock, Cape Town', '010 271 4600', NULL, NULL, 'La Marzocco South Africa is a showroom for specialty coffee equipment manufacturing and sales, trading from The Old Biscuit Mill.', NULL, NULL, '["https://theoldbiscuitmill.co.za/tenants/la-marzocco-south-africa/", "https://lamarzoccosa.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'la-marzocco-south-africa-woodstock'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

-- The Palms Decor and Lifestyle Centre (woodstock) tenants

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('mulholland-interior-solutions-woodstock', 'Mulholland Interior Solutions', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-palms-decor-and-lifestyle-centre-woodstock'), 'Shop 023, 145 Sir Lowry Road, Woodstock, Cape Town', '021 461 0591', NULL, NULL, 'Mulholland Interior Solutions is an interior decor and furnishing showroom, trading from The Palms Decor and Lifestyle Centre.', NULL, NULL, '["https://www.palms.co.za/tenants", "https://mulhollandinteriors.myshopify.com/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'mulholland-interior-solutions-woodstock'), (SELECT id FROM categories WHERE slug = 'furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('estora-home-woodstock', 'Estora Home', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-palms-decor-and-lifestyle-centre-woodstock'), 'Unit A103, 145 Sir Lowry Road, Woodstock, Cape Town', '021 565 0090', NULL, NULL, 'Estora Home is a furniture and homeware showroom, trading from The Palms Decor and Lifestyle Centre.', NULL, NULL, '["https://www.palms.co.za/tenants", "https://www.estorahome.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'estora-home-woodstock'), (SELECT id FROM categories WHERE slug = 'furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('debt-scan-woodstock', 'Debt Scan', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-palms-decor-and-lifestyle-centre-woodstock'), 'Unit A071, 145 Sir Lowry Road, Woodstock, Cape Town', '079 591 3308', NULL, NULL, 'Debt Scan is a debt counselling and financial services provider, trading from The Palms Decor and Lifestyle Centre.', NULL, NULL, '["https://www.palms.co.za/tenants", "https://www.debtscan.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'debt-scan-woodstock'), (SELECT id FROM categories WHERE slug = 'financial-investment-services'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('migal-vanas-photography-woodstock', 'Migal Vanas Photography', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-palms-decor-and-lifestyle-centre-woodstock'), 'Unit A042, 145 Sir Lowry Road, Woodstock, Cape Town', '082 339 0237', NULL, NULL, 'Migal Vanas Photography is a commercial photography studio, trading from The Palms Decor and Lifestyle Centre.', NULL, NULL, '["https://www.palms.co.za/tenants", "https://migalvanas.com/contact"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'migal-vanas-photography-woodstock'), (SELECT id FROM categories WHERE slug = 'photographers'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('the-counselling-hub-woodstock', 'The Counselling Hub', (SELECT id FROM suburbs WHERE slug = 'woodstock'), (SELECT id FROM shopping_centers WHERE slug = 'the-palms-decor-and-lifestyle-centre-woodstock'), 'Unit A033, 1st Floor, The Palms Emporium, 145 Sir Lowry Road, Woodstock, Cape Town', '071 940 0691', NULL, NULL, 'The Counselling Hub provides counselling and support services by appointment, trading from The Palms Decor and Lifestyle Centre.', NULL, NULL, '["https://www.palms.co.za/tenants", "https://counsellinghub.org.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'the-counselling-hub-woodstock'), (SELECT id FROM categories WHERE slug = 'clinics-healthcare'), 1);

-- Golden Acre (cape-town-cbd) tenants

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('exact-cape-town-cbd', 'Exact', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 425 2640', NULL, NULL, 'Exact is a TFG-owned fashion retailer offering clothing and footwear for the family, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://www.facebook.com/exactclothing/posts/our-golden-acre-kids-store-now-open/1770095069731030/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'exact-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('fashion-world-cape-town-cbd', 'Fashion World', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 419 4737', NULL, NULL, 'Fashion World is an affordable fashion retailer offering shoes, clothing and accessories, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://www.tiendeo.co.za/stores/cape-town/fashion-world-shop-g-golden-acre-shopping-centre-adderley-street-cape-town/78225"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'fashion-world-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('franco-ceccato-cape-town-cbd', 'Franco Ceccato', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 421 0681', NULL, NULL, 'Franco Ceccato is a footwear retailer offering shoes for men, women and children, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://www.yep.co.za/biz/store/iyp/12964730_2"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'franco-ceccato-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('heroes-cape-town-cbd', 'Heroes', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 425 1893', NULL, NULL, 'Heroes is a menswear and footwear retailer, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://za.near-place.com/heroes-61-golden-acre-foreshore-cape-town"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'heroes-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('identity-cape-town-cbd', 'Identity', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '081 171 0521', NULL, NULL, 'Identity is a South African fashion retailer offering on-trend apparel and accessories, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://www.yellosa.co.za/company/852123/identity-storesbranchesgolden-acre-shopping-centre"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'identity-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('jam-clothing-cape-town-cbd', 'Jam Clothing', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '062 218 4410', NULL, NULL, 'Jam Clothing is a value fashion retailer offering clothing for the family, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://jamclothing.co.za/stores/jam-golden-acre-cape-town/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'jam-clothing-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('mr-price-kids-cape-town-cbd', 'Mr Price Kids', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '087 049 3438', NULL, NULL, 'Mr Price Kids is a children''s clothing and footwear retailer, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://www.mrphome.com/en_za/store/mr-price-goldenacre-kids"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'mr-price-kids-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('pep-cape-town-cbd', 'PEP', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 425 0880', NULL, NULL, 'PEP is a value retailer offering clothing, homeware and cellular products, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://www.tiendeo.co.za/stores/cape-town/pep-stores-shop--golden-acre-adderley-street-cape-town-cbd-cape-town-western-cape/11875"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'pep-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('rage-cape-town-cbd', 'Rage', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 418 9808', NULL, NULL, 'Rage is a footwear and clothing retailer, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://www.tiendeo.co.za/stores/cape-town/rage-s-s-golden-acre-adderley-street/10495"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'rage-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('side-step-cape-town-cbd', 'Side Step', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 418 0245', NULL, NULL, 'Side Step is a footwear retailer offering fashion shoes for men and women, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://www.side-step.co.za/stores/golden-acre-side-step/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'side-step-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('soviet-cape-town-cbd', 'Soviet', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '011 061 0660', NULL, NULL, 'Soviet is a denim and streetwear fashion retailer, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "http://sovietdenim.blogspot.com/2015/10/a-golden-affair-with-soviet-gold-is.html"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'soviet-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sportscene-cape-town-cbd', 'Sportscene', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 417 4618', NULL, NULL, 'Sportscene is a sportswear and sneaker retailer, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://www.tiendeo.co.za/stores/cape-town/sportscene-golden-acre-shopping-centrecnr-adderley-strand-str/62727"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'sportscene-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('studio-88-cape-town-cbd', 'Studio 88', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 418 0756', NULL, NULL, 'Studio 88 is a branded fashion and sportswear retailer, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://www.tiendeo.co.za/stores/cape-town/studio-88-shop-c-golden-acre-shopping-centre-corner-strand-and-addreley-streets-foreshore/17409"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'studio-88-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sneaker-factory-cape-town-cbd', 'Sneaker Factory', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 427 9049', NULL, NULL, 'Sneaker Factory is a sneaker and footwear retailer, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://bash.com/store/sneaker-factory-golden-acre-western-cape-8001/062885"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'sneaker-factory-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('the-fix-cape-town-cbd', 'The Fix', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 425 5564', NULL, NULL, 'The Fix is a women''s fashion retailer offering clothing, footwear and accessories, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://www.hellopeter.com/the-fix/reviews/the-fix-cape-town-golden-acre-closes-before-closing-time-and-chase-customers-away-4870909"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'the-fix-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('traders-warehouse-cape-town-cbd', 'Traders Warehouse', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 418 3439', NULL, NULL, 'Traders Warehouse offers discounted branded fashion for the whole family, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://traderswarehouse.co.za/?page_id=111"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'traders-warehouse-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('atlantic-meat-cape-town-cbd', 'Atlantic Meat', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 100 1248', NULL, NULL, 'Atlantic Meat is a butchery offering fresh meat and poultry, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://www.atlanticmeat.co.za/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'atlantic-meat-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'butcheries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('kfc-golden-acre-cape-town-cbd', 'KFC', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 418 6172', NULL, NULL, 'KFC is a fried chicken fast food restaurant, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://locations.kfc.co.za/western-cape/cape-town/shop-86-9-adderley-streets-golden-acre-shopping-centre"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'kfc-golden-acre-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('pep-cell-cape-town-cbd', 'PEP Cell', (SELECT id FROM suburbs WHERE slug = 'cape-town-cbd'), (SELECT id FROM shopping_centers WHERE slug = 'golden-acre-cape-town-cbd'), 'Golden Acre Shopping Centre, 9 Adderley St, Cape Town', '021 418 1875', NULL, NULL, 'PEP Cell is a mobile phone and accessories retailer, trading from Golden Acre.', NULL, NULL, '["https://golden-acre.co.za/stores/", "https://za.near-place.com/pep-cell-shop-no-c68-golden-acre-shopping-centre-cape-town"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'pep-cell-cape-town-cbd'), (SELECT id FROM categories WHERE slug = 'mobile-phones'), 1);

-- Cape Quarter (de-waterkant) tenants

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('african-elite-properties-de-waterkant', 'African Elite Properties', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Shop A22, Cape Quarter, Dixon Street, De Waterkant, Cape Town', '021 421 1090', NULL, NULL, 'African Elite Properties is a luxury serviced-apartment letting and accommodation agency, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://africaneliteproperties.com/stay-with-us/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'african-elite-properties-de-waterkant'), (SELECT id FROM categories WHERE slug = 'accommodation'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('baraka-gifts-decor-de-waterkant', 'Baraka Gifts & Décor', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Shop 34-35, Level 0, Cape Quarter Lifestyle Village, 27 Somerset Rd, De Waterkant, Cape Town', '021 425 8883', NULL, NULL, 'Baraka Gifts & Décor is a gift and home décor shop selling handmade, fair-trade and artisan-made jewellery, textiles and décor items, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.barakashop.co.za/about-us/", "https://www.capetownmagazine.com/shopping/baraka-gift-and-decor-shop-in-cape-town/176_22_19471"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'baraka-gifts-decor-de-waterkant'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('palette-art-gallery-de-waterkant', 'Palette Art Gallery', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Shop 28, Cape Quarter Square, 27 Somerset Road, De Waterkant, Cape Town', '083 432 2006', NULL, NULL, 'Palette Art Gallery is a fine art gallery selling paintings and sculptures, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.palettesculpturegallery.co.za/", "https://www.capetownmagazine.com/cape-quarter-shopping-experience"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'palette-art-gallery-de-waterkant'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('silvan-de-waterkant', 'Silvan', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Shop 32, Cape Quarter Lifestyle Village, 27 Somerset Road, De Waterkant, Cape Town', '082 827 8111', NULL, NULL, 'Silvan is a knitwear and lifestyle brand selling locally made bamboo and cotton knitwear and botanically themed products, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://silvan.co.za/pages/our-story", "https://m.facebook.com/silvan.capetown/photos/-we-are-inlove-with-our-flagship-store-at-cape-quarter-visit-us-in-the-heart-of-/1064828365757251/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'silvan-de-waterkant'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('mobile-mate-de-waterkant', 'Mobile Mate', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Shop A17, Cape Quarter Lifestyle Village, 27 Somerset Rd, De Waterkant, Cape Town', '066 170 2867', NULL, NULL, 'Mobile Mate is a mobile phone and device shop offering sales, repairs and accessories for smartphones and laptops, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://mobilemate.co.za/contact-us/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'mobile-mate-de-waterkant'), (SELECT id FROM categories WHERE slug = 'mobile-phones'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('dr-jb-fine-de-waterkant', 'Dr JB Fine', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Shop 10, The Square, Cape Quarter, Napier Street, De Waterkant, Cape Town', '021 434 1913', NULL, NULL, 'Dr JB Fine is a general practitioner medical practice, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.medpages.info/sf/index.php?page=person&personcode=20600"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'dr-jb-fine-de-waterkant'), (SELECT id FROM categories WHERE slug = 'doctors-gps'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sparc-rehabilitation-centre-de-waterkant', 'SPARC Rehabilitation Centre', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Level 2, Cape Quarter, 27 Somerset Road, De Waterkant, Cape Town', '021 425 2298', NULL, NULL, 'SPARC is a sports performance and rehabilitation centre offering physiotherapy and related allied-health services, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.brabys.com/za/western-cape/cape-town/green-point/rehabilitation/sparc-sports-performance-and-rehabilitation-centre"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'sparc-rehabilitation-centre-de-waterkant'), (SELECT id FROM categories WHERE slug = 'physiotherapists'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('billy-now-de-waterkant', 'Billy Now', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Store A15, Mezzanine Level, Cape Quarter Lifestyle Village, 27 Somerset Rd, De Waterkant, Cape Town', '082 575 9573', NULL, NULL, 'Billy Now is a clothing label selling limited-run printed shirts and jackets made in Cape Town, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://shop.billynow.com/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'billy-now-de-waterkant'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('for-the-love-of-silk-de-waterkant', 'For the Love of Silk', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Shop 30, Cape Quarter Lifestyle Village, 27 Somerset Rd, De Waterkant, Cape Town', '061 431 7188', NULL, NULL, 'For the Love of Silk is a luxury silk textile and clothing retailer selling silk garments, scarves and bedding, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://fortheloveofsilk.co.za/", "https://www.sayellow.com/view/south-africa/for-the-love-of-silk-in-cape-town"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'for-the-love-of-silk-de-waterkant'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('philip-wulfsohn-jewellery-de-waterkant', 'Philip Wulfsohn Jewellery', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Shop A14, The Square, Cape Quarter, 27 Somerset Road, De Waterkant, Cape Town', '021 421 2628', NULL, NULL, 'Philip Wulfsohn Jewellery is a jewellery atelier offering handcrafted and bespoke jewellery in gold, platinum and silver, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://philipwulfsohn.com/pages/about", "https://www.capetownetc.com/cape-town/philip-wulfsohn-jewellery-a-cut-above-the-rest/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'philip-wulfsohn-jewellery-de-waterkant'), (SELECT id FROM categories WHERE slug = 'jewellers'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('rizelli-fashion-de-waterkant', 'Rizelli Fashion', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Shop A06, Cape Quarter Shopping Village, 27 Somerset Road, De Waterkant, Cape Town', '083 775 2209', NULL, NULL, 'Rizelli is a fashion store stocking footwear and clothing brands, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.xpose.co.za/listings/rizelli-shop-a06-cape-quarter-cape-town/", "https://www.facebook.com/rizellifashion/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'rizelli-fashion-de-waterkant'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('le-pickle-de-waterkant', 'Le Pickle', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Shop 2, Cape Quarter Lifestyle Village, 8 Jarvis Street, De Waterkant, Cape Town', '061 581 9662', NULL, NULL, 'Le Pickle is a burger restaurant serving smash burgers, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.lepickle.co.za/", "https://crushmag-online.com/le-pickle-founders-on-smashing-burgers-expectations/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'le-pickle-de-waterkant'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('nibbly-bits-de-waterkant', 'Nibbly Bits', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Cape Quarter, 27 Somerset Road, De Waterkant, Cape Town', '021 569 9584', NULL, NULL, 'Nibbly Bits is a bakery and café selling handmade biscuits, cakes and snacks, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.dining-out.co.za/restaurant-index.aspx?MemberID=11107&SiteVersion=desktop", "https://wanderlog.com/place/details/12305517/nibbly-bits-cape-quarter"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'nibbly-bits-de-waterkant'), (SELECT id FROM categories WHERE slug = 'bakeries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('vida-e-caffe-de-waterkant', 'Vida e Caffé', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Unit D05, Cape Quarter Square, 27 Somerset Road, De Waterkant, Cape Town', '021 418 0235', NULL, NULL, 'Vida e Caffé is a coffee shop and café chain, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.tripadvisor.co.za/Restaurant_Review-g12880258-d14102536-Reviews-Vida_E_Caffe-Green_Point_Western_Cape.html", "https://www.zomato.com/capetown/vida-e-caff%C3%A8-3-green-point"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'vida-e-caffe-de-waterkant'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('yumcious-de-waterkant', 'Yumcious', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), 'Cape Quarter, 72 Waterkant Street, De Waterkant, Cape Town', '072 208 8986', NULL, NULL, 'Yumcious is a bistro-style restaurant offering a pay-by-weight buffet as well as burgers and sandwiches, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "http://www.capetownmagazine.com/all-day-at-cape-quarter"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'yumcious-de-waterkant'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('latelier-optometrist-de-waterkant', 'L''Atelier Optometrist', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), '27 Somerset Road, Cape Quarter Lifestyle Village, De Waterkant, Cape Town', '021 418 0895', NULL, NULL, 'L''Atelier Optometrist is a boutique optometry and contact lens practice, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.prjctwrks.com/portfolio/l-atelier-cape-quarter/", "https://www.favrspecs.com/en/opticians/in/cape-town/373/latelier-optometrist/20776/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'latelier-optometrist-de-waterkant'), (SELECT id FROM categories WHERE slug = 'opticians'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('andalousse-de-waterkant', 'Andalousse', (SELECT id FROM suburbs WHERE slug = 'de-waterkant'), (SELECT id FROM shopping_centers WHERE slug = 'cape-quarter-de-waterkant'), '2 Jarvis Street, Cape Quarter, De Waterkant, Cape Town', '082 734 8615', NULL, NULL, 'Andalousse is a halal-certified Moroccan restaurant serving tajines, couscous and other traditional dishes, trading from Cape Quarter.', NULL, NULL, '["https://capequarter.co.za/shops/", "https://www.eatout.co.za/venue/andalousse-moroccan-cuisine/", "https://iamcapetown.co.za/tour/i-am-cape-town-eat-local-halaal/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'andalousse-de-waterkant'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

-- Victoria Wharf (va-waterfront) tenants

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('cape-union-mart-va-waterfront', 'Cape Union Mart', (SELECT id FROM suburbs WHERE slug = 'va-waterfront'), (SELECT id FROM shopping_centers WHERE slug = 'victoria-wharf-shopping-centre-va-waterfront'), 'Shop 142, Victoria Wharf Shopping Centre, 3 Dock Rd, V&A Waterfront, Cape Town', '021 419 0019', NULL, NULL, 'Cape Union Mart is an outdoor clothing, footwear and adventure gear retailer, trading from Victoria Wharf Shopping Centre.', NULL, NULL, '["https://www.tiendeo.co.za/stores/cape-town/cape-union-mart-shop-victoria-wharf-victoria-alfred-waterfront-cape-town/36351", "https://www.guzzle.co.za/cape-union-mart/cape-town"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'cape-union-mart-va-waterfront'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('truworths-va-waterfront', 'Truworths', (SELECT id FROM suburbs WHERE slug = 'va-waterfront'), (SELECT id FROM shopping_centers WHERE slug = 'victoria-wharf-shopping-centre-va-waterfront'), 'Shop G108, Victoria Wharf Shopping Centre, 3 Dock Rd, V&A Waterfront, Cape Town', '021 418 5520', NULL, NULL, 'Truworths is a South African fashion retailer selling clothing and accessories for women, men and kids, trading from Victoria Wharf Shopping Centre.', NULL, NULL, '["https://sabusinesslistings.co.za/listings/truworths-v-a-waterfront/", "https://www.guzzle.co.za/truworths/cape-town"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'truworths-va-waterfront'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('totalsports-va-waterfront', 'Totalsports', (SELECT id FROM suburbs WHERE slug = 'va-waterfront'), (SELECT id FROM shopping_centers WHERE slug = 'victoria-wharf-shopping-centre-va-waterfront'), 'Shop 127, Victoria Wharf Shopping Centre, 3 Dock Rd, V&A Waterfront, Cape Town', '021 418 5528', NULL, NULL, 'Totalsports is a sports clothing, footwear and accessories retailer, trading from Victoria Wharf Shopping Centre.', NULL, NULL, '["https://www.shopshours.co.za/totalsports/cape-town/c-57f3cabc47d677c3b27e3e05", "https://www.tiendeo.co.za/stores/cape-town/totalsports-victoria-wharf-victoria-and-alfred-waterfront/6409"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'totalsports-va-waterfront'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('exclusive-books-va-waterfront', 'Exclusive Books', (SELECT id FROM suburbs WHERE slug = 'va-waterfront'), (SELECT id FROM shopping_centers WHERE slug = 'victoria-wharf-shopping-centre-va-waterfront'), 'Victoria Wharf Shopping Centre, 3 Dock Rd, V&A Waterfront, Cape Town', '021 419 0905', NULL, NULL, 'Exclusive Books is a South African bookstore chain selling books, stationery and gifts, trading from Victoria Wharf Shopping Centre.', NULL, NULL, '["https://www.shopshours.co.za/exclusive-books/cape-town", "https://www.tiendeo.co.za/stores/cape-town/exclusive-books"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'exclusive-books-va-waterfront'), (SELECT id FROM categories WHERE slug = 'books-stationery'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('poetry-va-waterfront', 'Poetry', (SELECT id FROM suburbs WHERE slug = 'va-waterfront'), (SELECT id FROM shopping_centers WHERE slug = 'victoria-wharf-shopping-centre-va-waterfront'), 'Victoria Wharf Shopping Centre, 3 Dock Rd, V&A Waterfront, Cape Town', '021 419 0020', NULL, NULL, 'Poetry is a South African fashion retailer selling women''s clothing, footwear and accessories, trading from Victoria Wharf Shopping Centre.', NULL, NULL, '["https://www.shopshours.co.za/poetry/cape-town", "https://www.tiendeo.co.za/stores/cape-town/poetry"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'poetry-va-waterfront'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('ocean-basket-va-waterfront', 'Ocean Basket', (SELECT id FROM suburbs WHERE slug = 'va-waterfront'), (SELECT id FROM shopping_centers WHERE slug = 'victoria-wharf-shopping-centre-va-waterfront'), 'Shop 222, Upper Level, Victoria Wharf Shopping Centre, 3 Dock Rd, V&A Waterfront, Cape Town', '060 980 7154', NULL, NULL, 'Ocean Basket is a seafood restaurant chain serving calamari, fish and sushi, trading from Victoria Wharf Shopping Centre.', NULL, NULL, '["https://www.findmy.co.za/food/category-detail/ocean-basket-vanda-waterfront/22769", "https://restaurants-in-cape-town.co.za/restaurants/ocean-basket-va-waterfront/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'ocean-basket-va-waterfront'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('zara-va-waterfront', 'Zara', (SELECT id FROM suburbs WHERE slug = 'va-waterfront'), (SELECT id FROM shopping_centers WHERE slug = 'victoria-wharf-shopping-centre-va-waterfront'), 'Victoria Wharf Shopping Centre, 3 Dock Rd, V&A Waterfront, Cape Town', '021 446 8700', NULL, NULL, 'Zara is an international fashion retailer and anchor tenant selling women''s, men''s and children''s clothing, trading from Victoria Wharf Shopping Centre.', NULL, NULL, '["https://getoccupi.com/malls/victoria-wharf-shopping-centre", "https://www.shopshours.co.za/zara/cape-town"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'zara-va-waterfront'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('hm-va-waterfront', 'H&M', (SELECT id FROM suburbs WHERE slug = 'va-waterfront'), (SELECT id FROM shopping_centers WHERE slug = 'victoria-wharf-shopping-centre-va-waterfront'), 'Victoria Wharf Shopping Centre, 3 Dock Rd, V&A Waterfront, Cape Town', '0860 690 707', NULL, NULL, 'H&M is an international fashion retailer and anchor tenant selling clothing and homeware for women, men and children, trading from Victoria Wharf Shopping Centre.', NULL, NULL, '["https://www.hm.com/za/store-locator/south-africa/cape-town/victoria-alfred-waterfront/", "https://www.alamy.com/hm-storedress-shopfashion-retail-shop-retailer-in-africa-in-victoria-wharf-shopping-centre-or-mall-in-the-va-waterfront-cape-town-south-africa-image333482402.html"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'hm-va-waterfront'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

-- Waterstone Village (somerset-west) tenants

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('absolute-pets-somerset-west', 'Absolute Pets', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 4, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 300 3326', NULL, NULL, 'Absolute Pets is a pet supplies retailer stocking pet food, accessories, grooming products and pet health essentials, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://www.rawlovepets.co.za/pages/absolute-pets-waterstone-village"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'absolute-pets-somerset-west'), (SELECT id FROM categories WHERE slug = 'pet-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('bargain-books-somerset-west', 'Bargain Books', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 28B, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 851 0107', NULL, NULL, 'Bargain Books is a bookstore offering a wide range of fiction, non-fiction, stationery and gifts, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://bargainbooks.co.za/stores/somerset"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'bargain-books-somerset-west'), (SELECT id FROM categories WHERE slug = 'books-stationery'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('clicks-waterstone-village-somerset-west', 'Clicks', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 12, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 851 8850', NULL, NULL, 'Clicks is a pharmacy, health and beauty retailer offering dispensary services, cosmetics and everyday essentials, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://clicks.co.za/store/Waterstone-Village/163"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'clicks-waterstone-village-somerset-west'), (SELECT id FROM categories WHERE slug = 'pharmacies'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('flight-centre-waterstone-village-somerset-west', 'Flight Centre', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 42, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '022 065 0300', NULL, NULL, 'Flight Centre is a travel agency offering flight bookings, holiday packages and travel planning services, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://www.flightcentre.co.za/stores/somerset-west"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'flight-centre-waterstone-village-somerset-west'), (SELECT id FROM categories WHERE slug = 'travel-agents'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('pick-n-pay-waterstone-village-somerset-west', 'Pick n Pay', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 40/41, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 851 8831', NULL, NULL, 'Pick n Pay is a supermarket offering groceries, fresh produce and household essentials, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://www.callupcontact.com/b/Supermarkets/Pick_39n_Pay_Waterstone/168"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'pick-n-pay-waterstone-village-somerset-west'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('woolworths-waterstone-village-somerset-west', 'Woolworths', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 38/39, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 850 7911', NULL, NULL, 'Woolworths is a supermarket and food market offering fresh produce, groceries and prepared meals, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://www.woolworthsholdings.co.za/woolworths-adds-another-new-concept-store-at-waterstone-village/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'woolworths-waterstone-village-somerset-west'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('virgin-active-waterstone-village-somerset-west', 'Virgin Active', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Ground Floor, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 851 2704', NULL, NULL, 'Virgin Active is a health club and gym offering fitness equipment, group classes, a heated pool and childcare facilities, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://www.virginactive.co.za/gyms/waterstone-village"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'virgin-active-waterstone-village-somerset-west'), (SELECT id FROM categories WHERE slug = 'fitness-gyms'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('spur-waterstone-somerset-west', 'Spur', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 19, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 850 0316', NULL, NULL, 'Spur is a family restaurant serving burgers, steaks and grill favourites, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://getoccupi.com/malls/waterstone-village"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'spur-waterstone-somerset-west'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('mcdonalds-waterstone-somerset-west', 'McDonald''s Waterstone', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 850 0943', NULL, NULL, 'McDonald''s Waterstone is a fast-food restaurant serving burgers, fries and breakfast items, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://getoccupi.com/malls/waterstone-village", "https://www.tiendeo.co.za/stores/somerset-west/mcdonald-s"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'mcdonalds-waterstone-somerset-west'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('kfc-waterstone-somerset-west', 'KFC Waterstone', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 850 0689', NULL, NULL, 'KFC Waterstone is a fast-food restaurant specialising in fried chicken meals, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://getoccupi.com/malls/waterstone-village", "https://www.tiendeo.co.za/stores/somerset-west/kfc"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'kfc-waterstone-somerset-west'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('the-hussar-grill-waterstone-somerset-west', 'The Hussar Grill', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 26, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 851 9858', NULL, NULL, 'The Hussar Grill is a steakhouse restaurant known for prime cuts and grilled dishes, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://getoccupi.com/malls/waterstone-village"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'the-hussar-grill-waterstone-somerset-west'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('the-body-shop-waterstone-village-somerset-west', 'The Body Shop', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 46B, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 851 0097', NULL, NULL, 'The Body Shop is a cosmetics and skincare retailer offering ethically sourced beauty products, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://getoccupi.com/malls/waterstone-village"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'the-body-shop-waterstone-village-somerset-west'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('tsonga-waterstone-village-somerset-west', 'Tsonga', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 24, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 007 0760', NULL, NULL, 'Tsonga is a footwear and leather goods retailer offering handcrafted shoes, bags and accessories, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://getoccupi.com/malls/waterstone-village"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'tsonga-waterstone-village-somerset-west'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('intercare-waterstone-somerset-west', 'Intercare Waterstone', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), '1st Floor, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 891 1100', NULL, NULL, 'Intercare Waterstone is a multi-disciplinary medical centre offering GP, specialist and day-clinic services, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://getoccupi.com/malls/waterstone-village"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'intercare-waterstone-somerset-west'), (SELECT id FROM categories WHERE slug = 'clinics-healthcare'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('wellness-warehouse-waterstone-village-somerset-west', 'Wellness Warehouse', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 14, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 569 5594', NULL, NULL, 'Wellness Warehouse is a health and wellness retailer offering supplements, natural foods and personal care products, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://getoccupi.com/malls/waterstone-village"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'wellness-warehouse-waterstone-village-somerset-west'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('mtn-waterstone-village-somerset-west', 'MTN', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 15, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '083 869 1425', NULL, NULL, 'MTN is a mobile network retail store offering cellphones, contracts and accessories, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://getoccupi.com/malls/waterstone-village"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'mtn-waterstone-village-somerset-west'), (SELECT id FROM categories WHERE slug = 'mobile-phones'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('lira-fynn-somerset-west', 'Lira & Fynn', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 5, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '067 360 0861', NULL, NULL, 'Lira & Fynn is a fashion and lifestyle boutique offering women''s clothing and accessories, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://findngo.com/waterstone-village"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'lira-fynn-somerset-west'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sorbet-waterstone-village-somerset-west', 'Sorbet', (SELECT id FROM suburbs WHERE slug = 'somerset-west'), (SELECT id FROM shopping_centers WHERE slug = 'waterstone-village-somerset-west'), 'Shop 9, Waterstone Village, Cnr of R44 & Main Road, Somerset West, 7130', '021 851 8047', NULL, NULL, 'Sorbet is a beauty salon offering nails, waxing, facials and beauty treatments, trading from Waterstone Village.', NULL, NULL, '["https://www.waterstonevillage.co.za", "https://www.tiendeo.co.za/stores/somerset-west/sorbet"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'sorbet-waterstone-village-somerset-west'), (SELECT id FROM categories WHERE slug = 'beauty-hair-salons'), 1);

-- Cape Flats suburb discovery

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('clicks-grassy-park-grassy-park', 'Clicks Grassy Park', (SELECT id FROM suburbs WHERE slug = 'grassy-park'), '79 3rd Avenue, Grassy Park Ext 15, Grassy Park, Cape Town, 7941', '021 705 4755', NULL, NULL, 'Clicks Grassy Park is a pharmacy, health, beauty and homeware retail store in Grassy Park.', NULL, NULL, '["https://my-catalogue.co.za/stores/grassy-park/clicks/79-3rd-avenue-grassy-park-ext-15", "https://naturallyafricahaircare.co.za/store-locator/grassy-park-clicks/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'clicks-grassy-park-grassy-park'), (SELECT id FROM categories WHERE slug = 'pharmacies'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('spar-grassy-park-grassy-park', 'SPAR Grassy Park', (SELECT id FROM suburbs WHERE slug = 'grassy-park'), 'C/O 4th Ave & Victoria Road, Grassy Park, Cape Town', '021 200 0488', NULL, NULL, 'SPAR Grassy Park is a full-service supermarket on the corner of 4th Avenue and Victoria Road in Grassy Park.', NULL, NULL, '["https://my-catalogue.co.za/stores/grassy-park/spar/c-o-4th-ave-victoria-road", "https://www.spar.co.za/Home/Store-View/SPAR-Grassy-Park-Western-Cape/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'spar-grassy-park-grassy-park'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('woolworths-grassy-park-grassy-park', 'Woolworths Grassy Park', (SELECT id FROM suburbs WHERE slug = 'grassy-park'), 'Cnr Prince George Dr & 5th Ave, Grassy Park, Cape Town, 7941', '021 707 5400', NULL, NULL, 'Woolworths Grassy Park is a food, clothing and homeware department store on the corner of Prince George Drive and 5th Avenue.', NULL, NULL, '["https://my-catalogue.co.za/stores/grassy-park/woolworths/cnr-prince-george-dr-5th-ave", "https://www.gps-data-team.com/where/south_africa/store_locator/Woolworths-ZA/Woolworths-Grassy-Park.html"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'woolworths-grassy-park-grassy-park'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('cash-crusaders-grassy-park-grassy-park', 'Cash Crusaders Grassy Park', (SELECT id FROM suburbs WHERE slug = 'grassy-park'), 'Kismet Building, Corner of 5th Avenue and Italian Road, Grassy Park, Cape Town', '021 706 6463', NULL, NULL, 'Cash Crusaders Grassy Park buys and sells second-hand goods and electronics from the Kismet Building on 5th Avenue.', NULL, NULL, '["https://my-catalogue.co.za/stores/cape-town/cash-crusaders/kismet-building-corner-of-5th-avenue-and-italian-road-grassy-park", "https://yandex.com/maps/org/cash_crusaders_grassy_park/148703898621/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'cash-crusaders-grassy-park-grassy-park'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('pick-n-pay-supermarket-plattekloof-plattekloof', 'Pick n Pay Supermarket Plattekloof', (SELECT id FROM suburbs WHERE slug = 'plattekloof'), 'Gert Van Rooyen & Plattekloof Roads, Plattekloof, Cape Town, 7500', '021 558 6100', NULL, NULL, 'Pick n Pay Supermarket Plattekloof is a full-service grocery supermarket at the corner of Gert van Rooyen and Plattekloof Roads.', NULL, NULL, '["https://my-catalogue.co.za/stores/plattekloof/pick-n-pay-supermarket/plattekloof", "https://www.guzzle.co.za/pick-n-pay/plattekloof"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'pick-n-pay-supermarket-plattekloof-plattekloof'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('spar-plattekloof-plattekloof', 'SPAR Plattekloof', (SELECT id FROM suburbs WHERE slug = 'plattekloof'), 'Corner of Olienhout Avenue and Plattekloof Drive, Plattekloof, Cape Town', '021 911 1010', NULL, NULL, 'SPAR Plattekloof is a supermarket at the corner of Olienhout Avenue and Plattekloof Drive.', NULL, NULL, '["https://my-catalogue.co.za/stores/plattekloof/spar/cnr-olienhout-plattekloof-drive", "https://yandex.com/maps/?text=SPAR%20Plattekloof%20Olienhout"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'spar-plattekloof-plattekloof'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('cash-crusaders-lansdowne-lansdowne', 'Cash Crusaders Lansdowne', (SELECT id FROM suburbs WHERE slug = 'lansdowne'), 'Corner Jan Smuts & Lansdowne Road, Lansdowne, Cape Town', '021 703 2428', NULL, NULL, 'Cash Crusaders Lansdowne buys and sells second-hand goods and electronics at the corner of Jan Smuts and Lansdowne Road.', NULL, NULL, '["https://my-catalogue.co.za/stores/cape-town/cash-crusaders/corner-jan-smuts-lansdowne-road-lansdowne", "https://yandex.com/maps/?text=Cash%20Crusaders%20Lansdowne%20Cape%20Town"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'cash-crusaders-lansdowne-lansdowne'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('shoprite-retreat-retreat', 'Shoprite Retreat', (SELECT id FROM suburbs WHERE slug = 'retreat'), 'Cnr 8th Avenue and Retreat Road, Retreat, Cape Town, 7945', '021 710 1560', NULL, NULL, 'Shoprite Retreat is a full-service grocery supermarket at the corner of 8th Avenue and Retreat Road.', NULL, NULL, '["https://my-catalogue.co.za/stores/retreat/shoprite/cnr-8th-avenue-and-retreat-road", "https://yandex.com/maps/?text=Shoprite%20Retreat%20Cape%20Town"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'shoprite-retreat-retreat'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);
