INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin)
VALUES ('maitcomp-printers-maitland', 'Maitcomp Printers', (SELECT id FROM suburbs WHERE slug = 'maitland'), '179 Voortrekker Road, Maitland, Cape Town, 7405', '021 510 0595', 'https://maitcomp.co.za', 'info@maitcomp.co.za', 'Maitcomp Printers is a printing business offering business cards, signage, banners, stickers, vehicle branding, graphic design and computer sales and repair, in Maitland.', NULL, NULL, '["https://maitcomp.co.za/contact/", "https://cape-town.infoisinfo.co.za/search/printing-services-and-others/b/maitland", "https://www.findglocal.com/ZA/Cape-Town/1537267079863695/Maitcomp-Printers"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary)
VALUES ((SELECT id FROM businesses WHERE slug = 'maitcomp-printers-maitland'), (SELECT id FROM categories WHERE slug = 'printing-services'), 1);
INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin)
VALUES ('maitland-gas-maitland', 'Maitland Gas', (SELECT id FROM suburbs WHERE slug = 'maitland'), '398 Voortrekker Road, Maitland, Cape Town', '021 510 7440', NULL, NULL, 'Maitland Gas is a supplier of gases for domestic and industrial use, in Maitland.', NULL, NULL, '["https://nearfinderza.com/en/business/wc/cape-town/installations/maitland-gas_44383+8.html", "https://www.thinklocal.co.za/biz/maitland-gas-maitland", "https://www.yep.co.za/biz/store/maitland-gas/223836"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary)
VALUES ((SELECT id FROM businesses WHERE slug = 'maitland-gas-maitland'), (SELECT id FROM categories WHERE slug = 'industrial-suppliers-manufacturing'), 1);
INSERT OR IGNORE INTO businesses (slug, name, suburb_id, address, phone, website, email, description, lat, lng, source_urls, status, origin)
VALUES ('bearings-distributors-maitland', 'Bearings Distributors', (SELECT id FROM suburbs WHERE slug = 'maitland'), 'Unit C5, Maitland Industrial Park, Voortrekker Road, Maitland, Cape Town, 7405', '021 593 2193', 'https://bearingsdistributors.co.za', NULL, 'Bearings Distributors is a bearings and seals supplier, in Maitland.', NULL, NULL, '["https://bearingsdistributors.co.za/contact-us/", "https://www.brabys.com/business/5716748/south-africa/western-cape/cape-town/maitland/voortrekker-rd/bearings-seals/bearings-distributors"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary)
VALUES ((SELECT id FROM businesses WHERE slug = 'bearings-distributors-maitland'), (SELECT id FROM categories WHERE slug = 'industrial-suppliers-manufacturing'), 1);
