-- content-upgrade:capetown:020: 15 descriptions (35 deferred, no SQL), generated by scripts/content-upgrade/to-sql.mjs
-- multiserv-maynard-mall-wynberg (researched)
UPDATE businesses SET description = 'Multiserv Maynard Mall Wynberg is a shoe repair, key cutting and dry-cleaning franchise inside Maynard Mall on Main Road, also offering leather repair, stitching, battery sales and courier services. The business has traded under the Multiserv name since 1969, making it one of the longer-running repair franchises in the Cape Town area, with other branches dotted across the greater Cape Town suburbs.

The Wynberg branch is open Monday to Friday from 9am to 5:30pm and Saturdays from 9am to 3pm, closed on Sundays. It suits Wynberg shoppers who want several household repair and convenience services, from a broken zip to a lost key, handled in one visit rather than several separate trips around the mall.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.cylex.net.za/company/multiserv-maynard-mall-wynberg-23861466.html'), description_enriched_at = datetime('now') WHERE slug = 'multiserv-maynard-mall-wynberg' AND description = 'Multiserv is a shoe repair, key cutting and dry-cleaning franchise inside Maynard Mall, Wynberg, also offering leather repair, stitching, battery sales and courier services.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- norval-foundation-tokai (researched)
UPDATE businesses SET description = 'Norval Foundation is an art museum and sculpture garden in the Tokai region of Cape Town, with a mission to promote modern and contemporary art from Africa and its diaspora. The museum runs a changing programme of curated exhibitions, alongside an exhibition archive of past shows and an artist editions programme.

Visitors can take a guided tour, stop at the on-site café, or hire one of the museum''s featured spaces for an event. The foundation''s Art For All Learning Centre runs an education programme alongside the exhibitions. A current collaboration with Cape Grace, a Fairmont-managed hotel, extends the museum''s contemporary African art collection beyond its own walls and into the hotel. It suits art lovers wanting a half-day visit that combines galleries, sculpture and a sit-down meal.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.norvalfoundation.org'), description_enriched_at = datetime('now') WHERE slug = 'norval-foundation-tokai' AND description = 'Norval Foundation is an art museum and sculpture garden in Tokai, showcasing modern and contemporary art from Africa and its diaspora through curated exhibitions.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- positano-noordhoek (researched)
UPDATE businesses SET description = 'Positano is an Italian-inspired resort-wear and swimwear label, handmade in Cape Town, with its first retail store opening in Noordhoek Farm Village in 2023. The range covers swimwear, including a prosthetic-friendly line, along with dresses, skirts, tops, jackets, cardigans, pants, shorts, bags and other accessories.

The flagship store at the corner of Village Lane and Noordhoek Main Road trades daily from 9am to 5pm. Customers can also reach the brand directly by phone or email for queries about products or collections. It suits shoppers looking for resort wear and swimwear with an Italian coastal feel, made locally rather than imported.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://positano.co.za/pages/contact'), description_enriched_at = datetime('now') WHERE slug = 'positano-noordhoek' AND description = 'Positano is an Italian-inspired resort-wear and swimwear boutique handmade in Cape Town, with its first retail store opening in Noordhoek Farm Village in 2023.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- quagga-rare-books-and-art-kalk-bay (researched)
UPDATE businesses SET description = 'Quagga Rare Books & Art is a family-owned antiquarian bookshop on Main Road in Kalk Bay, founded in 1990 and specialising in rare and unusual books, maps, artwork, photography and ephemera. The shop has built a distinctive footprint in the antiquarian book trade through its eye for the unusual, covering categories from Africana and Afrikaans titles to Anglo-Boer War history, art and architecture, biographies and children''s books.

Customers can browse the shop''s interesting mix of stock in person in Kalk Bay or through its online catalogue, and the business ships worldwide using a secure airmail process. It also provides accredited valuations of rare items. It suits collectors and researchers looking for scarce South African books, maps and ephemera rather than new releases.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://quaggabooks.co.za'), description_enriched_at = datetime('now') WHERE slug = 'quagga-rare-books-and-art-kalk-bay' AND description = 'Quagga Rare Books & Art is a family-owned antiquarian bookshop in Kalk Bay specialising in rare and unusual books and art, trading since 1990.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- seaforth-restaurant-simons-town (researched)
UPDATE businesses SET description = 'Seaforth Restaurant sits on the white sands of Seaforth Beach in Simon''s Town, with views of the mountains and sea and penguins from the nearby Boulders colony on hand to entertain diners. The menu covers the fruits of the sea as well as sharing platters fit for a discerning palate, cooked from the freshest ingredients available and served right on the water''s edge.

The restaurant has become internationally renowned for its food and service over the years, and it caters specifically for tour groups, with a range of tour group menus available on request for larger parties. It suits visitors combining a trip to the Boulders penguin colony with a relaxed seafood lunch on the beach, as well as groups looking to book ahead for a tour stop.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.seaforthrestaurant.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'seaforth-restaurant-simons-town' AND description = 'Seaforth Restaurant sits on Seaforth Beach near the Boulders penguin colony in Simon''s Town, serving seafood and sharing platters with views over False Bay.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- vintage-with-love-zonnebloem (researched)
UPDATE businesses SET description = 'Vintage with Love is a secondhand and vintage clothing store on Canterbury Street in Zonnebloem, selling pre-loved, gently worn clothes for a good cause. The shop stocks women''s and men''s clothing, from tops, bottoms and dresses to jackets, coats and accessories, including some luxury brand pieces among its collections.

The business works on a simple model: customers donate or sell their pre-loved clothing, the shop lists, markets and sells each piece to a new owner, and the proceeds are donated to a network of charities. It suits shoppers who want unique, pre-owned fashion finds while supporting a good cause, as well as anyone looking to donate or sell clothes they no longer wear.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.vintagewithlove.co.za'), description_enriched_at = datetime('now') WHERE slug = 'vintage-with-love-zonnebloem' AND description = 'Vintage with Love is a secondhand and vintage clothing store in Zonnebloem, offering pre-loved fashion and accessories as part of a sustainable-fashion retail concept.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- wild-eatery-zonnebloem (researched)
UPDATE businesses SET description = 'Wild Eatery is a vegan garden truck set up in a backyard garden on Harrington Street in Zonnebloem, serving creative plant-based fare such as gluten-free falafel wraps, inari tempura and black rice bowls. An attached natural foods shop sells local peanut butter cups and other plant-based goodies alongside the food truck menu.

The setting is relaxed and garden-based, making it a comfortable spot for a lunch with family or a dog in tow. Orders can be placed in person on Harrington Street or through one of the eatery''s delivery partners. It suits anyone looking for a casual, plant-based meal with a laid-back, garden-truck atmosphere in Zonnebloem.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.wildeatery.co.za/locations', '$[#]', 'https://www.corner.inc/place/563497'), description_enriched_at = datetime('now') WHERE slug = 'wild-eatery-zonnebloem' AND description = 'Wild Eatery is an outdoor cafe in Zonnebloem, accessible from both Harrington Street and via NUDE FOODS, a plastic-free grocery store, on Constitution Street.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- agrimark-philippi-horticultural (researched)
UPDATE businesses SET description = 'Agrimark Philippi is an agricultural and farming supplies store on Olieboom Road, part of the wider Agrimark retail chain and serving the Philippi farming community. The branch offers deliveries and direct diesel deliveries, product sourcing, credit facilities, prepaid airtime, data and electricity, and gift cards.

Its services also include Safetop pick and mix, BlueSky AdBlue, paint mixing, gas swap and exchange, and battery testing, covering much of what a working farm or smallholding needs in one stop. The store trades Monday to Friday from 7:30am to 5pm and Saturdays from 8am to 1pm, closed on Sundays. It suits farmers and smallholders in the Philippi Horticultural Area who want supplies, fuel services and farm essentials from one local branch.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.agrimark.co.za/store/agrimark-philippi'), description_enriched_at = datetime('now') WHERE slug = 'agrimark-philippi-horticultural' AND description = 'Agrimark Philippi is an agricultural and farming supplies retailer on Olieboom Road, serving the Philippi farming community as part of the wider Agrimark retail chain.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- pinelands-dental-inc-howard-centre-pinelands (researched)
UPDATE businesses SET description = 'Pinelands Dental Inc is a general and cosmetic dental practice on the second floor of Howard Centre in Pinelands, offering fillings, crowns, bridges, root canal treatment, extractions and implants. Patients can contact the practice by landline, or by cellphone and WhatsApp for quicker queries.

The practice is open Monday to Friday from 8:30am to 5:30pm, with alternate Saturday mornings from 8:30am to 12:30pm for patients who cannot get in during the week. Appointments can also be booked online through the practice''s website. It suits families in Pinelands looking for a dental practice offering both everyday and cosmetic treatment, with some weekend availability.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://pinelandsdentalinc.co.za/contact-us/'), description_enriched_at = datetime('now') WHERE slug = 'pinelands-dental-inc-howard-centre-pinelands' AND description = 'Pinelands Dental Inc is a general and cosmetic dental practice in Howard Centre, Pinelands, offering fillings, crowns, bridges, root canal treatment, extractions and implants.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- pizza-perfect-richwood (researched)
UPDATE businesses SET description = 'Pizza Perfect is a pizza restaurant at Richmond Corner in Richwood, part of a small Cape Town-based pizza chain that describes its food as real, authentic wood-fired pizza. Alongside pizza, the Richwood menu covers burgers, chicken, wraps, salads, chips, kids'' meals and desserts, giving the table something beyond pizza if not everyone wants the same thing.

Orders can be eaten in at the restaurant or placed through third-party delivery platforms for customers who would rather eat at home, with the brand''s own delivery page also listing it among Cape Town''s pizza options. It suits Richwood and Milnerton households wanting a casual, wood-fired pizza dinner, whether they eat in or have it delivered to the door.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.facebook.com/PizzaPerfectRichmondCorner/', '$[#]', 'https://www.mrdfood.com/food-delivery/restaurant/pizza-perfect-richmond-richmond/17357'), description_enriched_at = datetime('now') WHERE slug = 'pizza-perfect-richwood' AND description = 'Pizza Perfect is a pizza restaurant at Richmond Corner in Richwood, part of a Cape Town-based pizza chain, serving pizza for eat-in and takeaway.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- royal-tea-riverlands-observatory (researched)
UPDATE businesses SET description = 'Royal Tea is a bubble-tea bar at Riverlands Mall in Observatory, serving handcrafted Chinese-style teas including classic bubble teas with tapioca pearls and fresh-fruit tea blends. The brand describes itself as bringing contemporary Chinese tea culture to South Africa, with flavoured powders such as taro and strawberry mixed into its drinks to create different flavour combinations.

Customers can also buy Royal Tea''s own ingredients separately, including tapioca pearls and flavoured powders, to recreate bubble tea drinks at home rather than only drinking them in store. It suits shoppers at Riverlands Mall looking for a sweet, milky tea break or a more unusual drink than a standard coffee, as well as anyone wanting to stock up on bubble tea supplies.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://magicpin.com/south-africa/Cape-Town/Observatory-Ct/Other/Royal-Tea-Riverlands-Mall/store/241c23a'), description_enriched_at = datetime('now') WHERE slug = 'royal-tea-riverlands-observatory' AND description = 'Royal Tea is a bubble-tea bar at Riverlands Mall serving handcrafted Chinese-style teas, including classic bubble teas with tapioca pearls and fresh-fruit tea blends.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- virtus-medical-sea-point (researched)
UPDATE businesses SET description = 'Virtus Medical is a general practice on the third floor of The Point in Sea Point, established in 2013 and offering GP consultations alongside in-house dietician and counselling services. Beyond everyday consultations, the practice runs dedicated clinics for different needs, including a baby clinic, a woman''s wellness service, an infusion clinic and an aesthetics clinic.

Patients can book appointments online or by phone for any of these services, all from the same Regent Road premises. It suits Sea Point residents who want general healthcare and a range of more specific clinics, from baby check-ups to aesthetic treatments, under one roof rather than being referred elsewhere.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.virtusmed.co.za'), description_enriched_at = datetime('now') WHERE slug = 'virtus-medical-sea-point' AND description = 'Virtus Medical is a general practice at The Point in Sea Point, established in 2013, offering GP consultations alongside in-house dietician and counselling services.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- sorbet-gardens-shopping-centre-gardens (researched)
UPDATE businesses SET description = 'Sorbet Gardens is a beauty salon trading from Shop 41 in Gardens Shopping Centre, on the corner of Buitenkant and Mill Street. The salon''s treatment menu covers facials and general skincare, hair removal and eyebrow threading, acne facials, dermaplaning and makeup application, giving Gardens-area clients a range of skin and grooming treatments to choose from at one salon.

The branch trades long hours through the week, open from 9am to 7pm Monday to Friday, 8am to 5pm on Saturdays and 9am to 2pm on Sundays, making weekend and after-work appointments easy to fit in. It is a convenient option for residents and workers in Gardens and the surrounding City Bowl suburbs looking for facial, skin and grooming treatments without travelling far from home or the office.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.fresha.com/lvp/sorbet-salon-gardens1-mill-street-cape-town-A8PzVv'), description_enriched_at = datetime('now') WHERE slug = 'sorbet-gardens-shopping-centre-gardens' AND description = 'Sorbet is a beauty salon in Gardens Shopping Centre, Gardens, offering nail, beauty and spa treatments as part of the national Sorbet salon chain.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- spar-khayelitsha-mall-khayelitsha (researched)
UPDATE businesses SET description = 'SPAR Khayelitsha Mall is a supermarket branch trading from Shop 6 inside KCT Mall on Walter Sisulu Street, at the heart of Khayelitsha. Like other branches in the wider SPAR network found across South Africa, it stocks everyday groceries, fresh produce and household basics for shoppers doing a regular family shop, with the convenience of trading from within a busy community mall alongside other retailers.

The branch trades Monday to Friday from 9am to 5:30pm, Saturdays from 9am to 2:30pm and Sundays from 9am to 2pm, giving Khayelitsha shoppers a dependable supermarket option across most of the week. Residents of Khayelitsha and the surrounding communities who need a nearby grocery stop, whether for a full weekly shop or a quick essentials run, will find this branch a convenient choice within KCT Mall.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://my-catalogue.co.za/stores/khayelitsha/spar/shop-6-kct-mall-walter-sisulu-street'), description_enriched_at = datetime('now') WHERE slug = 'spar-khayelitsha-mall-khayelitsha' AND description = 'SPAR Khayelitsha Mall is a supermarket branch at KCT Mall on Walter Sisulu Street, stocking groceries and household essentials for shoppers in central Khayelitsha.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- the-crazy-store-richmond-corner-richwood (researched)
UPDATE businesses SET description = 'The Crazy Store at Richmond Corner is a discount variety retailer trading from Shop 27 in the Richmond Corner Shopping Centre, at the Plattekloof and Tygervalley intersection in Richwood. It forms part of South Africa''s largest discount variety chain, with more than 375 stores nationwide, and carries the toys, stationery, home accessories, party supplies, gifts and seasonal costume ranges the brand is known for.

The branch trades seven days a week, from 9am to 6pm every day including Sundays, making it an easy stop for shoppers in Richwood, Milnerton and the surrounding northern suburbs who want to stretch their budget on household basics, gifts or a last-minute costume, without needing to plan a trip around limited opening hours.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.hotfrog.co.za/company/1439126240653312/the-crazy-store-richmond-corner/cape-town/retail-stores'), description_enriched_at = datetime('now') WHERE slug = 'the-crazy-store-richmond-corner-richwood' AND description = 'The Crazy Store at Richmond Corner is a variety and homeware store in Richwood, Milnerton, offering a range of household, gift and stationery items.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- content-upgrade:capetown:020: 11 trading-hours updates (sourced from research, listing had none)
-- multiserv-maynard-mall-wynberg (hours)
UPDATE businesses SET hours = 'Mon-Fri 09:00-17:30, Sat 09:00-15:00, Sun Closed' WHERE slug = 'multiserv-maynard-mall-wynberg' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- wild-eatery-zonnebloem (hours)
UPDATE businesses SET hours = 'Mon-Fri 10:00-15:30, Sat 10:00-15:00, Sun Closed' WHERE slug = 'wild-eatery-zonnebloem' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- agrimark-philippi-horticultural (hours)
UPDATE businesses SET hours = 'Mon-Fri 07:30-17:00, Sat 08:00-13:00, Sun Closed' WHERE slug = 'agrimark-philippi-horticultural' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- pep-blue-downs (hours)
UPDATE businesses SET hours = 'Mon-Thu 08:30-17:30, Fri 08:30-17:00, Sat 08:00-15:00, Sun 09:00-13:00' WHERE slug = 'pep-blue-downs' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- pep-kensington-shopping-centre-kensington (hours)
UPDATE businesses SET hours = 'Mon 08:30-17:30, Tue 09:00-17:30, Wed-Fri 08:30-17:30, Sat 08:30-13:30, Sun Closed' WHERE slug = 'pep-kensington-shopping-centre-kensington' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- shoe-city-ottery-centre-ottery (hours)
UPDATE businesses SET hours = 'Mon-Fri 09:00-19:00, Sat 08:00-17:00, Sun Closed' WHERE slug = 'shoe-city-ottery-centre-ottery' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- sorbet-gardens-shopping-centre-gardens (hours)
UPDATE businesses SET hours = 'Mon-Fri 09:00-19:00, Sat 08:00-17:00, Sun 09:00-14:00' WHERE slug = 'sorbet-gardens-shopping-centre-gardens' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- spar-khayelitsha-mall-khayelitsha (hours)
UPDATE businesses SET hours = 'Mon-Fri 09:00-17:30, Sat 09:00-14:30, Sun 09:00-14:00' WHERE slug = 'spar-khayelitsha-mall-khayelitsha' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- the-crazy-store-richmond-corner-richwood (hours)
UPDATE businesses SET hours = 'Mon-Sun 09:00-18:00' WHERE slug = 'the-crazy-store-richmond-corner-richwood' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- ackermans-makhaza-khayelitsha (hours)
UPDATE businesses SET hours = 'Mon-Fri 09:00-18:00, Sat 09:00-17:00, Sun Closed' WHERE slug = 'ackermans-makhaza-khayelitsha' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- vizi-hair-durbanville (hours)
UPDATE businesses SET hours = 'Mon Closed, Tue-Fri 08:00-17:00, Sat 08:00-13:30, Sun Closed' WHERE slug = 'vizi-hair-durbanville' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
