-- content-upgrade:capetown:012: 29 descriptions (21 deferred, no SQL), generated by scripts/content-upgrade/to-sql.mjs
-- pick-n-pay-strand (researched)
UPDATE businesses SET description = 'Pick n Pay in Strand Square is a full supermarket stocking groceries and household essentials, with fresh produce, fresh breads and baked goods, and a meat counter alongside everyday toiletries. The store also operates a PnP Liquor outlet and a recycling point, and offers PnP Courier Services and a range of pre-cooked meals for shoppers wanting a quicker option. The branch keeps extended trading hours on weekdays, giving shoppers more time to get their shopping done outside the usual nine-to-five.

The store trades from Strand Square on Fagan Street in Strand, and suits households doing a full weekly shop as well as shoppers picking up fresh bread, meat or a pre-cooked meal, posting a parcel, or recycling on the same visit.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://strandsquarecentre.co.za/stores/'), description_enriched_at = datetime('now') WHERE slug = 'pick-n-pay-strand' AND description = 'Pick n Pay is a supermarket with a branch in Strand Square, Strand, stocking groceries, fresh produce and household goods.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- pick-n-pay-tyger-valley-bellville (researched)
UPDATE businesses SET description = 'Pick n Pay in Tyger Valley Shopping Centre is a full-service supermarket trading from Shop 559 in the centre''s food precinct, stocking groceries, fresh produce and household goods for everyday shopping. The centre''s own store directory lists the branch under its food category, with its own trading hours and contact details separate from the rest of the mall.

The store opens from nine in the morning to seven at night on weekdays and Saturdays, and keeps shorter hours of nine to five on Sundays and public holidays, giving shoppers a reliable window for a full shop most days of the week.

The supermarket trades from Tyger Valley Shopping Centre on Bill Bezuidenhout Avenue in Bellville, and suits shoppers doing a weekly grocery run or a quick top-up while visiting one of the northern suburbs'' busiest shopping centres.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.tygervalley.co.za/store/pick-n-pay/5041'), description_enriched_at = datetime('now') WHERE slug = 'pick-n-pay-tyger-valley-bellville' AND description = 'Pick n Pay is a supermarket inside Tyger Valley Shopping Centre in Bellville, stocking groceries, fresh produce and household goods.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- prima-hire-builders-plant-eerste-river (researched)
UPDATE businesses SET description = 'Prima Hire Builders Plant is a construction equipment hire business operating from its own yard on Bosman Street in Eerste River. Listed under the construction equipment category, the business supplies building and construction plant and machinery to contractors and other customers working on site.

The yard keeps set weekday and Saturday trading hours, giving customers a clear window to collect or return hired equipment around a working week, rather than operating purely by appointment.

The business is based at 8 Bosman Street in Eerste River, and suits building contractors, renovators and other customers in the surrounding area who need construction plant and machinery hired out for a job rather than bought outright.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.cylex.net.za/company/prima-hire-builders-plant-23702210.html'), description_enriched_at = datetime('now') WHERE slug = 'prima-hire-builders-plant-eerste-river' AND description = 'Prima Hire Builders Plant hires out building and construction plant and machinery, including TLBs, from its yard in Eerste River.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- safety-protective-clothing-epping (researched)
UPDATE businesses SET description = 'Safety Protective Clothing in Epping Industria manufactures and distributes personal protective equipment and workwear meeting SABS and CE standards. Its range covers PPE coveralls, conti suits, safety boots, lab coats, hard hats, barrier netting, ear plugs and safety spectacles.

The business also supplies gloves in nitrile and leather, rainwear, freezer wear, reflective vests, chef wear, dustcoats, mop caps, sleeve protectors, aprons and full-body harnesses. This range spans everyday workwear through to specialised safety equipment for industrial and food-service settings.

The company is based at Unit 9, Magnum Park on Bofors Circle in Epping Industria, and suits businesses needing bulk protective clothing and safety gear for staff in factories, kitchens or on site.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.hotfrog.co.za/company/1448401229697024/safety-protective-clothing-pty-ltd/cape-town/security-safety-products'), description_enriched_at = datetime('now') WHERE slug = 'safety-protective-clothing-epping' AND description = 'Safety Protective Clothing manufactures and distributes personal protective equipment and workwear meeting SABS and CE standards, based in Epping Industria.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- sakura-beauty-bar-welgemoed (researched)
UPDATE businesses SET description = 'Sakura Beauty Bar in Welgemoed is a beauty salon built around what it calls the art of mindful beauty, with therapists taking time to understand each client''s needs before any treatment begins. Its custom treatments include waxing with careful aftercare, nail art shaped around a client''s style, and brow and lash work designed to suit individual features.

The salon also offers facials chosen for each client''s skin type, from consultation through to the finishing touch, along with massage therapy focused on comfort and tension relief. The salon describes its approach as one where clients are listened to, treatments are made personal, and small details are never rushed.

The salon is in the Welgemoed Centre on Kommissaris Street, and suits clients looking for an unhurried, detail-focused beauty appointment in the northern suburbs.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://sakurabeautybar.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'sakura-beauty-bar-welgemoed' AND description = 'Sakura Beauty Bar is a beauty salon in Welgemoed offering facials, manicures, hair removal and waxing, threading and makeup services.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- sheet-street-vangate-mall-athlone (researched)
UPDATE businesses SET description = 'Sheet Street at Vangate Mall is a branch of the national home furnishings and textiles retailer, trading from Shop 58 inside the mall. The store''s own branch page lists it separately from other Sheet Street stores, with its own set of contact details and trading hours specific to the Vangate Mall location.

Shoppers can expect the chain''s usual range of bedding, curtaining, towels and other home textiles, sold from a dedicated storefront rather than a shared department, with staff on hand during the store''s own posted hours rather than those of the wider mall.

The store is at Shop 58 in Vangate Mall, on the corner of Vanguard Drive and Klipfontein Road in Athlone, and suits shoppers looking to pick up linen, curtains or other home textiles while already shopping at the mall.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.sheetstreet.com/sheet-street-vangate-mall-30511'), description_enriched_at = datetime('now') WHERE slug = 'sheet-street-vangate-mall-athlone' AND description = 'Sheet Street Vangate Mall is a branch of the Sheet Street home furnishings and textiles chain, in Vangate Mall, Athlone.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- sidewalk-cafe-vredehoek (researched)
UPDATE businesses SET description = 'Sidewalk Cafe in Vredehoek is a long-standing neighbourhood restaurant run by the Madame Zingara group, known for its cosy, hodge-podge country kitchen décor. A Cape Town Etc review found the restaurant unchanged after years away, with the same carefully considered menu and the same relaxed, homely atmosphere.

The menu includes fresh juices made to order, and the signature chicken, prawn and pea risotto, alongside a changing fish of the day and other mains such as fillet steak. Other dishes on the table in the review included spinach and ricotta parcels and a vegetarian penne, with cheesecake among the desserts on offer.

The restaurant is on Derry Street in Vredehoek, and suits a relaxed dinner built around comfort food and familiar flavours done well.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.capetownetc.com/food-and-drink/sidewalk-cafe/'), description_enriched_at = datetime('now') WHERE slug = 'sidewalk-cafe-vredehoek' AND description = 'Sidewalk Cafe is a long-standing neighbourhood cafe and restaurant on Derry Street in Vredehoek, serving breakfasts, light meals and coffee.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- sorbet-salon-riverlands-observatory (researched)
UPDATE businesses SET description = 'Sorbet Salon at Riverlands Mall offers an extensive treatment menu covering manicures, pedicures and specialised pedicures, gel nails and nail repair, facials, waxing, threading, brows and lashes, makeup and sugaring. The branch''s own page describes the salon as aiming for guests to leave with a smile, with trained staff delivering the full range of Sorbet''s nail, skin and beauty treatments under one roof.

Booking is available in person, by phone or through the Sorbet app, which also covers loyalty points and gift cards across the group''s salons, nail bars and hair bars.

The salon trades from Shop G48 in Riverlands Mall in Observatory, and suits anyone looking to combine a manicure or pedicure with a facial, wax or brow treatment in a single appointment.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://stores.salonssorbet.co.za/western-cape/cape-town/shop-g48-riverlands-mall'), description_enriched_at = datetime('now') WHERE slug = 'sorbet-salon-riverlands-observatory' AND description = 'Sorbet Salon Riverlands is a beauty salon inside Riverlands Mall in Observatory offering manicures, pedicures, massages, threading, tinting and waxing.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- steers-liberty-promenade-mitchells-plain (researched)
UPDATE businesses SET description = 'Steers at Liberty Promenade is a quick-service restaurant trading from Shop 196 inside the centre, serving the chain''s flame-grilled burgers, chicken and ribs alongside its hand-cut chips. The centre''s own shop listing confirms the branch''s contact details and trading hours as a tenant of the mall rather than a stand-alone outlet.

Being inside the centre puts the restaurant within reach of other Liberty Promenade shoppers, making it a convenient stop for a quick meal between errands rather than a dedicated sit-down booking.

The restaurant is at Shop 196 in Liberty Promenade, on the corner of AZ Berman Drive and Morgenster Road in Mitchells Plain, and suits shoppers and locals wanting a fast meal while out at the centre.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://libertypromenade.co.za/shops/steers/'), description_enriched_at = datetime('now') WHERE slug = 'steers-liberty-promenade-mitchells-plain' AND description = 'Steers is a flame-grilled burgers, chicken and ribs quick-service restaurant operating in the food court at Liberty Promenade, Mitchells Plain.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- steers-melkbosstrand (researched)
UPDATE businesses SET description = 'Steers Melkbosstrand is a flame-grilled quick-service restaurant at Birkenhead Shopping Centre, serving the chain''s burgers, chicken and ribs together with hand-cut chips and thick shakes. The branch''s own official listing gives it daily trading hours of 10am to 9pm, open every day of the week rather than keeping shorter weekend hours.

Dine-in, takeaway and delivery are all available from the branch, giving customers in the coastal town more than one way to get their order, whether that is a sit-down meal or something collected on the way home.

The restaurant is at Shop 19B in Birkenhead Shopping Centre, on the corner of Otto du Plessis and Birkenhead Road in Melkbosstrand, and suits a quick family meal or a takeaway order after a day at the beach.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://location.steers.co.za/melkbosstrand'), description_enriched_at = datetime('now') WHERE slug = 'steers-melkbosstrand' AND description = 'Steers Melkbosstrand is a flame-grilled burger, chicken and ribs takeaway restaurant at Birkenhead Shopping Centre, part of the Steers chain.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- stor-age-springfield-road-ottery (researched)
UPDATE businesses SET description = 'Stor-Age Springfield Road is a self-storage facility offering individually alarmed units in more than 40 different sizes, suited to anything from a few boxes to a full household move. The facility also sells packaging supplies, offers dedicated business storage, and provides van hire and parcel collection for customers who need more than just a unit to rent. Security includes controlled access, surveillance cameras and regular patrols, and leases run flexibly, with units available to rent for as little as one month rather than a long-term contract.

The facility is on Springfield Street in Ottery, keeping set weekday and Saturday-morning hours and closing on Sundays, and suits households moving or renovating as well as businesses needing extra storage space in the southern suburbs.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://stor-age.co.za/stores/ottery-springfield-road', '$[#]', 'https://www.cylex.net.za/company/stor-age-self-storage-ottery-springfield-road-23805876.html'), description_enriched_at = datetime('now') WHERE slug = 'stor-age-springfield-road-ottery' AND description = 'Stor-Age Springfield Road is a self-storage facility on Springfield Street offering individual storage units for households and businesses in Ottery.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- surfshack-camps-bay (researched)
UPDATE businesses SET description = 'Surfshack on the Camps Bay beachfront is a contemporary, diner-inspired eatery with a view-drenched terrace offering front-row seats to the ocean, and a rustic-chic interior for a more laid-back setting. A review by Inside Guide describes the vibe as chilled yet buzzy, drawing both locals and tourists to the beachfront.

Sharing plates on the menu include crispy corn on the cob, tempura crab claw, blistered jalapeño peppers and seared ahi tuna, while mains run from barbecue lamb chops and grilled chicken kebabs to dry-aged sirloin on the bone and a bucket of shellfish. The menu also includes a pizza section and a range of burgers, among them a lobster roll, a hot pastrami dog, a hot honey fried-chicken burger and a bacon-beer-and-cheese burger, finishing with sweet options such as frozen mousse, banana cream pie and milk panna cotta.

The restaurant is at 201 The Promenade on Victoria Road, and suits a relaxed meal with sunset views over the Atlantic.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://insideguide.co.za/cape-town/restaurants/surfshack/'), description_enriched_at = datetime('now') WHERE slug = 'surfshack-camps-bay' AND description = 'Surfshack is a laid-back seaside diner on Camps Bay beachfront, serving wood-fired pizzas, burgers and shareable plates with ocean views.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- tekkie-town-the-junxion-mall-philippi (researched)
UPDATE businesses SET description = 'Tekkie Town at The Junxion Mall in Philippi is a footwear retailer that promises great customer service alongside a wide range of quality branded footwear, clothing and accessories at affordable prices. The store caters for the whole family, stocking international brands including Nike, Adidas and Puma.

The branch positions itself as a one-stop option for sneakers and casual footwear for parents and children shopping together, rather than a specialist store for one type of shoe. It trades from Shop 08 in the mall, on the corner of Govan Mbeki and New Eisleben Roads.

The store suits families in Philippi looking for branded sneakers, shoes and accessories without needing to travel to a bigger mall.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.jamii.co.za/7047-philippi-footwear-tekkie-town-phillipi-junxion-mall'), description_enriched_at = datetime('now') WHERE slug = 'tekkie-town-the-junxion-mall-philippi' AND description = 'Tekkie Town is a footwear retailer inside The Junxion Mall in Philippi, part of a national sneaker and shoe chain.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- the-barbers-range-bothasig (researched)
UPDATE businesses SET description = 'The Barber''s Range in Bothasig Square offers haircuts, fades and scissor cuts for men and children, along with head and face shaves, waxing and hot-towel grooming treatments. The branch''s own page notes that customers can simply walk in rather than needing to book ahead, making it a convenient stop for a quick trim or a full grooming session.

The shop keeps long weekday hours into the evening, with shorter hours on Fridays and weekend trading on Saturday and Sunday, giving working customers and families flexibility around when they come in.

The barbershop is at Shop 8 in Bothasig Square on Vryburger Avenue, Bothasig, and suits men, children and pensioners looking for a straightforward haircut or grooming treatment without needing an appointment.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://thebarbersrange.co.za/barbers-cape-town-branches/bothasig-barber/', '$[#]', 'https://www.fresha.com/lvp/the-barbers-range-bothasig-vryburger-avenue-kaapstad-30AyDN'), description_enriched_at = datetime('now') WHERE slug = 'the-barbers-range-bothasig' AND description = 'The Barber''s Range Bothasig is a barbershop and hair salon in Bothasig Square offering haircuts and grooming services for men.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- the-indian-oven-hout-bay (researched)
UPDATE businesses SET description = 'The Indian Oven in Hout Bay''s Red Sails Building is a North Indian restaurant at the foot of Chapman''s Peak, with chefs using traditional recipes and fresh, locally sourced ingredients. The restaurant''s extensive menu runs from savoury curries to spicy biryanis, alongside tandoori and paneer dishes made with authentic spices.

Diners consistently praise the biryani and curries, describing the food as consistently delicious and the service as excellent, with the aroma from the kitchen often enough to draw passers-by inside. Reviewers also highlight the warm atmosphere and knowledgeable staff who can guide first-time visitors through the menu.

The restaurant is at Shop 8 in the Red Sails Building in Hout Bay, and suits anyone looking for an authentic North Indian meal with a cosy, welcoming setting.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.indianoven.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'the-indian-oven-hout-bay' AND description = 'The Indian Oven is a North Indian restaurant in Hout Bay''s Red Sails Building serving tandoori-oven starters, curries and naan.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- tonys-roma-flamingo-square-table-view (researched)
UPDATE businesses SET description = 'Tony''s Roma in Flamingo Square is a bar and grill restaurant in the heart of Table View, offering a full bar with big screens for sports alongside an upmarket, family-friendly dining room. The restaurant serves breakfast, lunch and dinner, and describes itself as catering for the whole family, from young to old.

The menu runs from succulent ribs and crispy fresh salads to char-grilled steaks and flame-grilled burgers, with food prepared on a wood-fired oven to bring out bold and delicate flavours through seasoning during grilling. The combination of sports bar and restaurant gives it a dual role as both a casual spot to watch a game and a sit-down dinner venue.

The restaurant is at Flamingo Square on the corner of Study and Blaauwberg Road, and suits a family meal out or a casual evening watching sport over ribs and a drink.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://tonysroma.co.za/about/'), description_enriched_at = datetime('now') WHERE slug = 'tonys-roma-flamingo-square-table-view' AND description = 'Tony''s Roma Flamingo Square is a bar-grill restaurant in Flamingo Square known for its ribs, char-grilled steaks and flame-grilled burgers.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- urban-health-pharmacy-lansdowne (researched)
UPDATE businesses SET description = 'Urban Health Pharmacy in Lansdowne is an independent pharmacy and member of the WeCare Pharmacy Network, open 24 hours a day. The pharmacy describes itself as dedicated to its customers'' healthcare needs, offering a wide range of pharmacy services alongside everyday essentials.

Its round-the-clock hours make it a resource for prescriptions and urgent medication needs outside normal pharmacy hours, serving the Lansdowne area at any time of day or night, whether that is a late-night script or an early-morning top-up of everyday essentials.

Being part of a wider pharmacy network gives the branch access to shared buying power and systems, while still operating as an independent, locally run pharmacy that deals directly with its own customers.

The pharmacy is at 406 Imam Haron Road in Lansdowne, and suits anyone who needs a prescription filled, chronic medication managed, or everyday health items bought outside standard trading hours.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://wecarepharmacy.co.za/urban-health-pharmacy-lansdowne/'), description_enriched_at = datetime('now') WHERE slug = 'urban-health-pharmacy-lansdowne' AND description = 'Urban Health Pharmacy is a 24-hour pharmacy in Lansdowne, dispensing prescription medicines and offering chronic medication management around the clock.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- urban-umami-century-city (researched)
UPDATE businesses SET description = 'Urban Umami is an Asian-fusion restaurant serving small plates, mains and desserts that combine Asian flavours with South African ingredients. The restaurant''s own information describes all-day dining alongside dedicated breakfast, lunch and dinner service, so customers can order a full meal or something lighter at almost any time.

The restaurant offers outside seating, Wi-Fi, secure parking and disabled access, catering to business diners working through a meal as well as families, couples and groups looking for a relaxed sit-down meal.

The restaurant is at 3 Energy Lane in the Bridgeways Precinct, Century City, and suits anyone looking for contemporary Asian-inspired dining with the flexibility of all-day service.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.umamirestaurant.co.za'), description_enriched_at = datetime('now') WHERE slug = 'urban-umami-century-city' AND description = 'Urban Umami is an Asian-inspired restaurant in the Bridgeways Precinct, Century City, serving all-day dining alongside a dedicated breakfast menu.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- virgin-active-okavango-crossing-kraaifontein (researched)
UPDATE businesses SET description = 'Virgin Active Okavango is a gym offering standard gym-floor training alongside express classes, Pilates and cycling sessions for members wanting a structured workout. Functional training is also available on-site, and the club''s own listing confirms personal training can be booked at an additional cost for members wanting one-on-one coaching.

The mix of self-directed gym-floor access and scheduled classes gives members a choice between training alone on the equipment or joining a timed group session, depending on what suits their day.

The gym is at Shop 17 in Okavango Crossing, on the corner of Langeberg Road and Okavango Road in Kraaifontein, and suits members working on general fitness, strength, weight management, functional fitness or sport-specific training.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.virginactive.co.za/gyms/okavango'), description_enriched_at = datetime('now') WHERE slug = 'virgin-active-okavango-crossing-kraaifontein' AND description = 'Virgin Active Okavango is a gym in the Okavango Crossing centre in Kraaifontein, offering fitness equipment and group exercise classes.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- wimpy-bothasig (researched)
UPDATE businesses SET description = 'Wimpy at Bothasig Square is a family restaurant serving all-day breakfasts, burgers, toasted sandwiches, grills, milkshakes, coffee and desserts, in keeping with the wider Wimpy menu. The branch''s own listing confirms delivery is available from this specific restaurant, alongside the usual dine-in and takeaway options, and gives its current operating hours.

Having delivery as well as a sit-down dining room means customers can choose between eating in at the centre or having a meal brought to them, rather than being limited to one option.

The restaurant is at Shop 9 in Bothasig Square, on the corner of Vryburger Avenue and Tafelberg Street in Bothasig, and suits families, individuals and local customers wanting breakfast, lunch, dinner or a casual meal.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://locations.wimpy.co.za/restaurants-BothasigSquare-WimpyBothasigMall'), description_enriched_at = datetime('now') WHERE slug = 'wimpy-bothasig' AND description = 'Wimpy is a family restaurant inside Bothasig Square, part of the national Wimpy chain, serving all-day breakfasts, burgers and grills.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- wimpy-paddocks-milnerton (researched)
UPDATE businesses SET description = 'Wimpy Paddocks is a family-friendly restaurant inside The Paddocks Shopping Centre, serving all-day breakfasts, burgers, toasted sandwiches, grills, milkshakes and coffee alongside other casual meals. The branch''s own page gives its specific operating hours and contact details separately from the chain''s general store-locator pages, confirming it as an active, currently trading restaurant.

Dine-in, takeaway and delivery are all offered from the restaurant, giving customers in the area more than one way to get a meal, whether that is sitting down for breakfast or ordering dinner to be delivered.

The restaurant is at Shop 13 in The Paddocks Shopping Centre on Racecourse Road, Milnerton, and suits families and casual diners looking for a relaxed meal at any time of day.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://location.wimpy.co.za/paddocks'), description_enriched_at = datetime('now') WHERE slug = 'wimpy-paddocks-milnerton' AND description = 'Wimpy Paddocks is a family-friendly Wimpy restaurant in The Paddocks Shopping Centre, Milnerton, serving classic breakfasts, burgers and comfort food.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- zoo-park-motors-kraaifontein (researched)
UPDATE businesses SET description = 'Zoo Park Motors is a Shell service station supplying Shell V-Power 95, Shell V-Power Diesel and Shell Diesel Extra, alongside a Select convenience shop for food, drinks and everyday items. The station''s own listing confirms a car wash, service bays and an ATM on site, giving motorists more than just a fuel stop.

The station operates 24 hours a day, making it a reliable option for fuel, a quick snack or a car wash outside normal business hours as well as during the day.

The station is at 135 Brighton Road in Kraaifontein, and suits motorists and local customers needing fuel, convenience purchases or basic vehicle services at any time.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://find.shell.com/za/fuel/10042563-zoo-park-motors/en_ZA'), description_enriched_at = datetime('now') WHERE slug = 'zoo-park-motors-kraaifontein' AND description = 'Zoo Park Motors is a Shell fuel station in Kraaifontein with a convenience shop and car wash, open 24 hours.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- anytime-fitness-sea-point-sea-point (researched)
UPDATE businesses SET description = 'Anytime Fitness Sea Point is a 24-hour gym giving members round-the-clock access to cardio and strength training equipment on Main Road. The club''s own information confirms scheduled classes alongside open gym-floor training, plus private showers and restrooms for members who want more than a basic access-only setup.

Membership also includes worldwide access to the Anytime Fitness network of gyms, letting members train at other branches while travelling rather than being limited to the Sea Point club alone.

The gym is at Marika Court, 142 Main Road in Sea Point, and suits members wanting flexible, round-the-clock training without being tied to set opening hours.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.anytimefitness.co.za/gyms/za-0004/cape-town-western-cape-8005/'), description_enriched_at = datetime('now') WHERE slug = 'anytime-fitness-sea-point-sea-point' AND description = 'Anytime Fitness Sea Point is a 24-hour gym on Main Road giving members round-the-clock access to cardio and strength training equipment.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- artvark-gallery-kalk-bay (researched)
UPDATE businesses SET description = 'Artvark Gallery in Kalk Bay is a classic and contemporary art gallery founded in 1991 in Johannesburg, built originally around a handmade cutlery range. The gallery relocated to Kalk Bay in 1998, where it established both the gallery and a manufacturing studio in Retreat for its steel range.

The gallery curates a mix of original sculpture, ceramics, paintings, prints and handcrafted steel panels, alongside distinctive custom steelwork and bold, expressive design pieces. It describes itself as a landmark destination for contemporary South African art on the Cape coast, and offers international shipping for buyers further afield.

The gallery is at 48 Main Road in Kalk Bay, and suits art lovers and collectors looking for original South African sculpture, ceramics and steel design work in one setting.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.artvark.org', '$[#]', 'https://www.artvark.org/about'), description_enriched_at = datetime('now') WHERE slug = 'artvark-gallery-kalk-bay' AND description = 'Artvark Gallery is a classic and contemporary art gallery on Main Road in Kalk Bay, also incorporating a café for visitors.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- azura-health-and-beauty-westlake (researched)
UPDATE businesses SET description = 'Azura Health and Beauty in Westlake Shopping Centre is a boutique skincare clinic combining advanced aesthetic technology with personalised care, aimed at long-term skin health rather than one-off treatments. The clinic frames healthy skin as the foundation of its approach, building each treatment plan around the client''s own skin journey.

The clinic serves clients from across the southern peninsula, including Muizenberg, Kalk Bay, Constantia and Steenberg, drawing on the area''s appeal as a base near hiking trails, restaurants, Chapman''s Peak Drive, Cape Point and the False Bay beaches.

The clinic is at Unit 26 in Westlake Shopping Centre on Westlake Drive, and suits clients looking for a personalised, technology-led approach to skincare and beauty treatments in the southern suburbs.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://azurahealthandbeauty.co.za'), description_enriched_at = datetime('now') WHERE slug = 'azura-health-and-beauty-westlake' AND description = 'Azura Health and Beauty is a health and beauty spa in Westlake Shopping Centre, offering skincare and beauty treatments in Westlake.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- blouberg-manor-bloubergstrand (researched)
UPDATE businesses SET description = 'Blouberg Manor is a boutique guesthouse in Bloubergstrand set within a restored 1947 Cape Dutch manor house, just moments from the beach. The property has seventeen individually designed suites, each reflecting a different cultural influence found in South Africa, several with balconies and views over Big Bay.

The guesthouse combines relaxed coastal living with personalised hospitality, aiming to offer uninterrupted ocean calm close to Blouberg''s shoreline. Its setting lets guests wake up near the water while staying within easy reach of the wider Cape Town area.

The guesthouse is at 6 Verkouteren Crescent in Bloubergstrand, and suits travellers looking for a characterful, design-led stay on the coast rather than a standard hotel room.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://bloubergmanor.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'blouberg-manor-bloubergstrand' AND description = 'Blouberg Manor is a boutique guesthouse in Bloubergstrand with individually decorated en-suite rooms, several with balconies and views over Big Bay.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- body20-riverlands-observatory (researched)
UPDATE businesses SET description = 'Body20 Riverlands is a franchise studio built around EMS (electrical muscle stimulation) personal training, with sessions lasting just 20 minutes rather than a full gym workout. The studio''s own description frames sessions around a client''s own goals, covering weight loss, toning, strength development and rehabilitation within that shorter format.

The short session length is aimed at people who want a structured, supervised workout without setting aside a long block of time at the gym, while still working toward a specific fitness or recovery goal.

The studio is at Shop G04 in Riverlands Mall, Observatory, and suits members looking for quick, goal-focused personal training sessions rather than an open gym-floor membership.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://body20.co.za/studio-riverlands.php'), description_enriched_at = datetime('now') WHERE slug = 'body20-riverlands-observatory' AND description = 'Body20 Riverlands is a franchise studio offering 20-minute EMS (electrical muscle stimulation) personal training sessions, located in Riverlands Mall in Observatory.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- byers-glass-wetton (researched)
UPDATE businesses SET description = 'Byers Glass is a glass merchant in Wetton listed under the windscreens and motor glass category, supplying and fitting glass for vehicles. The business is registered at its Wetton Road address with its own dedicated phone line, distinguishing it from a general hardware or building-glass supplier.

Focusing on vehicle glass means the business is set up for jobs such as replacing or repairing a windscreen or window rather than general glazing work, serving motorists who need a chip repaired or a pane replaced.

The business is at 132 Wetton Road in Wetton, Cape Town, and suits vehicle owners in the surrounding southern suburbs needing windscreen or motor glass work done.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://nearfinderza.com/en/business/wc/cape-town/glass-merchants/byers-glass_390128+3.html'), description_enriched_at = datetime('now') WHERE slug = 'byers-glass-wetton' AND description = 'Byers Glass is a glass merchant in Wetton, Cape Town, supplying and fitting glass for vehicles as well as other applications.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- candy-cartel-lentegeur (researched)
UPDATE businesses SET description = 'Candy Cartel is a confectionery and sweets shop in Lentegeur, listed as a general retailer stocking a variety of candy and confectionery products for customers in the area. The business has built a sizeable following on social media, with its Facebook page followed by more than 28,000 people, suggesting a steady base of regular, repeat customers beyond just passing trade.

Current business listings give the shop its own address, phone number and trading hours, confirming it as an active, locally contactable retailer with a fixed shopfront rather than an online-only or pop-up seller.

The shop is on Azalia Crescent in Lentegeur, and suits local customers, families and visitors looking for sweets and confectionery close to home without needing to travel to a bigger shopping centre.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://za.africabz.com/western-cape/candy-cartel-485204', '$[#]', 'https://www.facebook.com/p/Candy-Cartel-100063696634817/'), description_enriched_at = datetime('now') WHERE slug = 'candy-cartel-lentegeur' AND description = 'Candy Cartel is a wholesale sweets and confectionery shop in Lentegeur, selling bulk candy direct to the public at discounted prices.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- content-upgrade:capetown:012: 8 trading-hours updates (sourced from research, listing had none)
-- pick-n-pay-tyger-valley-bellville (hours)
UPDATE businesses SET hours = 'Mon-Sat 09:00-19:00, Sun 09:00-17:00' WHERE slug = 'pick-n-pay-tyger-valley-bellville' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- prima-hire-builders-plant-eerste-river (hours)
UPDATE businesses SET hours = 'Mon-Fri 07:30-16:45, Sat 07:30-11:45, Sun Closed' WHERE slug = 'prima-hire-builders-plant-eerste-river' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- steers-melkbosstrand (hours)
UPDATE businesses SET hours = 'Mon-Sun 10:00-21:00' WHERE slug = 'steers-melkbosstrand' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- stor-age-springfield-road-ottery (hours)
UPDATE businesses SET hours = 'Mon-Fri 08:00-17:00, Sat 09:00-12:00, Sun Closed' WHERE slug = 'stor-age-springfield-road-ottery' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- the-barbers-range-bothasig (hours)
UPDATE businesses SET hours = 'Mon-Thu 08:00-19:00, Fri 08:00-13:00, Sat 08:00-17:00, Sun 08:00-15:00' WHERE slug = 'the-barbers-range-bothasig' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- urban-health-pharmacy-lansdowne (hours)
UPDATE businesses SET hours = 'Open 24 hours' WHERE slug = 'urban-health-pharmacy-lansdowne' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- zoo-park-motors-kraaifontein (hours)
UPDATE businesses SET hours = 'Open 24 hours' WHERE slug = 'zoo-park-motors-kraaifontein' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- anytime-fitness-sea-point-sea-point (hours)
UPDATE businesses SET hours = 'Open 24 hours' WHERE slug = 'anytime-fitness-sea-point-sea-point' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
