-- content-upgrade:capetown:002: 20 descriptions (30 deferred, no SQL), generated by scripts/content-upgrade/to-sql.mjs
-- sneaker-box-kuils-river (researched)
UPDATE businesses SET description = 'Sneaker Box is an outlet footwear store inside Access Park Bellville, specialising in authentic Skechers and Anta footwear. Its range covers sneakers and athletic shoes for men, women and children, running from everyday casual styles through to performance-focused training shoes, alongside a selection of matching apparel.

As an outlet, the store is built around value, with discounts that can reach as much as 50% off regular retail prices on the brands it carries, making it a practical stop for families replacing school shoes, casual wearers after an everyday sneaker, and sports-minded shoppers after athletic footwear. Sneaker Box trades from Shop B19 at Access Park Bellville, 1 Van Riebeeck Road, Kuils River, within easy reach of shoppers across the northern suburbs.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://accessparkbellville.co.za/directory/sneaker-box/'), description_enriched_at = datetime('now') WHERE slug = 'sneaker-box-kuils-river' AND description = 'Sneaker Box is a footwear store inside Access Park, Kuils River.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- st-james-guesthouses-st-james (researched)
UPDATE businesses SET description = 'St James Guesthouses are two properties in the St James area on the False Bay coast of Cape Town, part of the Rovos Rail Group. The guesthouses are St James Manor and the Homestead Villa, both sea-facing and set in a suburb known for its Victorian bathing boxes, grand old houses and tidal pools.

Guests are a short walk from Kalk Bay harbour, where fresh fish is bought from local fishermen and restaurants serve home-style cooking and fine dining. Across the road from the guesthouses are the famous tidal pools and swimming beaches, and the historic promenade and mountain walks start close by. Land-based whale watching is a highlight in season, when whales come close to the shoreline.

The main road through to Kalk Bay is lined with antique shops, delis, sidewalk cafes, boutiques and art galleries, so a stay suits travellers who want a relaxed coastal base with the sea, the shops and the harbour all within easy reach.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.stjamesguesthouses.com/', '$[#]', 'https://www.stjamesguesthouses.com/about'), description_enriched_at = datetime('now') WHERE slug = 'st-james-guesthouses-st-james' AND description = 'St James Guesthouses offers accommodation on Main Road in St James.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- superspar-belhar-belhar (researched)
UPDATE businesses SET description = 'SUPERSPAR Belhar is a full-service supermarket trading inside Cavalier Shopping Centre, at the corner of Modderdam and Robert Sobukwe Road in Belhar. As part of the SPAR group''s SUPERSPAR format, the store carries the fuller range of fresh produce, groceries and household goods that distinguishes a SUPERSPAR from a smaller neighbourhood SPAR, giving shoppers a single stop for a full weekly trolley.

The branch keeps extended trading hours, open from 08:00 to 19:00 Monday to Saturday and from 08:00 to 18:00 on Sundays and public holidays, so shoppers can fit a grocery run around work or weekend plans. Serving residents and shoppers across Belhar and the surrounding Cape Town communities, it suits anyone doing a full household shop close to home.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.spar.co.za/home/store-view/superspar-belhar-western-cape'), description_enriched_at = datetime('now') WHERE slug = 'superspar-belhar-belhar' AND description = 'SUPERSPAR Belhar is a full-service supermarket inside Cavalier Shopping Centre, Belhar.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- superspar-kuilsrivier-kuils-river (researched)
UPDATE businesses SET description = 'SuperSpar Kuilsrivier is a full-range supermarket trading from the Aroma Centre on Van Riebeeck Road in Kuils River. The store covers the departments typical of a SPAR flagship, including a bakery, a butchery, fresh fruit and vegetables, a wide grocery and dairy aisle, health and beauty lines, stationery, hardware, and toys and other household goods, alongside an attached Tops liquor department for wine, beer and spirits.

With a full set of departments under one roof, the store suits both a full weekly household shop and quicker top-up visits, and it draws shoppers from Kuils River and neighbouring areas such as Blackheath. Reviewers often mention its busy parking area and large number of till points at peak times, reflecting how much trade the branch does.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://za.africabz.com/western-cape/superspar-17269', '$[#]', 'https://www.thinklocal.co.za/biz/superspar-kuilsriver-kuilsriver'), description_enriched_at = datetime('now') WHERE slug = 'superspar-kuilsrivier-kuils-river' AND description = 'SuperSpar Kuilsrivier is a supermarket in the Aroma Centre, Kuils River.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- the-board-shop-kommetjie (researched)
UPDATE businesses SET description = 'The Board Shop is a supplier and retailer of materials for kitchens and built-in cupboards, stocking boards, timber and general hardware for cabinet-makers, builders and home renovators. Alongside supplying the boards and panel products used in custom cabinetry, the business also carries the fittings and hardware needed to finish a cupboard or kitchen project.

The shop delivers its materials throughout Cape Town, which makes it a practical supplier for trade customers working across the city as well as homeowners tackling a renovation themselves. It trades from 11 C&D, Fish Eagle Park, Kommetjie Road in Kommetjie, open on weekdays and Saturday mornings, serving the Kommetjie and wider Cape Peninsula area.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://za.africabz.com/western-cape/the-board-shop-131344', '$[#]', 'https://theboardshop.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'the-board-shop-kommetjie' AND description = 'The Board Shop is a surf and skateboard retailer in Kommetjie.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- 41-on-cedar-thornton (researched)
UPDATE businesses SET description = '41 on Cedar is a bed and breakfast guest house on Cedar Road in Cape Town, listed as a three-star property. Guests rate it 4.5 out of 5 from 33 reviews on HotelPlanner, with check-in from 14:00 and check-out at 10:00.

The property sits within easy reach of several Cape Town landmarks, including Canal Walk shopping centre, Rhodes Memorial, the University of Cape Town, Newlands Stadium and Cape Town International Airport. City sights listed nearby include the Castle of Good Hope, the Groote Kerk, the District Six Museum and the Artscape Theatre Centre.

For visitors who want a base close to the city and its museums, the guest house offers bed and breakfast stays with nightly rates that vary by room type.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.hotelplanner.com/Hotels/303800/Reservations-41-on-Cedar-Bed-Breakfast-Cape-Town-41-Cedar-Rd-Town-7460'), description_enriched_at = datetime('now') WHERE slug = '41-on-cedar-thornton' AND description = '41 on Cedar is a bed and breakfast guest accommodation, in Thornton.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- clicks-howard-centre-pinelands (researched)
UPDATE businesses SET description = 'Clicks Howard Centre is a Clicks pharmacy and retail branch trading from Howard Centre in Pinelands. Alongside the general Clicks range of health, beauty and everyday retail products, the branch runs its own dispensing pharmacy and a separate in-store clinic, offering services such as health screenings and related clinic consultations during the clinic''s own set hours.

Having both a pharmacy and a clinic on site sets this branch apart from a standard Clicks store, giving Pinelands residents and shoppers at Howard Centre a single stop for prescriptions, clinic visits, and general health, beauty and household shopping. It suits anyone combining a pharmacy or clinic visit with an everyday Clicks shop.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://clicks.co.za/store/Pinelands/128'), description_enriched_at = datetime('now') WHERE slug = 'clicks-howard-centre-pinelands' AND description = 'Clicks is a pharmacy retailer trading from the Howard Centre in Pinelands.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- dis-chem-wynberg (researched)
UPDATE businesses SET description = 'Dis-Chem''s Wynberg store on Main Road is a pharmacy with a linked dispensary, click and collect service and an in-store clinic. The wider chain has been trading since 1978, and this branch is one of its stores offering dispensing and clinic services.

The clinic keeps set hours, open Monday to Friday until 17:30 and on alternate Saturdays until 15:00. The store also carries a wide range of beauty products, healthy food, sport supplements and well-being lines, with staff on hand for expert advice.

The store is at 222 Main Road in Wynberg, Cape Town, and suits anyone who needs prescriptions filled, a clinic visit or everyday health and beauty items close to home.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.dischem.co.za/wynberg-cape-town'), description_enriched_at = datetime('now') WHERE slug = 'dis-chem-wynberg' AND description = 'Dis-Chem is a pharmacy and health retailer on Main Road in Wynberg.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- food-concept-maitland-maitland (researched)
UPDATE businesses SET description = 'Food_concept Maitland is a casual restaurant and takeaway on Voortrekker Road in Maitland, with a menu that spans sushi, burgers, chicken, sausage, chips and salads. Its cuisine is listed across several styles, including American, African, sushi and Asian dishes, giving diners a broader choice than a single-cuisine takeaway.

The restaurant serves both lunch and dinner, making it suited to a midday meal as well as an evening order. Trading from 190 Voortrekker Road in Maitland, it suits diners who want to mix and match across a varied menu, from a quick burger and chips to a sushi order, in one sitting or across separate visits.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.tripadvisor.com/Restaurant_Review-g312659-d23912150-Reviews-Food_concept_Maitland-Cape_Town_Central_Western_Cape.html'), description_enriched_at = datetime('now') WHERE slug = 'food-concept-maitland-maitland' AND description = 'Food_concept Maitland is a takeaway restaurant on Voortrekker Road in Maitland.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- knead-bakery-panorama (researched)
UPDATE businesses SET description = 'Knead Bakery in Panorama is an artisan bakery and café built around handmade bread, made using traditional methods, natural yeasts and locally sourced, seasonal ingredients rather than mass-produced loaves. Panorama Healthcare Centre, where the bakery trades from, names bread as the business''s core speciality, setting it apart from a general café that happens to sell a few loaves on the side.

Alongside its bread, the bakery and café serves breakfast, lunch, brunch and coffee, making it a spot for a sit-down meal as well as a bread run. Trading from Panorama Healthcare Centre at the corner of Rothschild Boulevard and Hennie Winterbach Street, it suits local Panorama residents and café customers looking for freshly baked bread and a relaxed daytime menu.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.kneadbakery.co.za/knead-panorama', '$[#]', 'https://www.panoramahcc.co.za/tenants/knead-bakery/'), description_enriched_at = datetime('now') WHERE slug = 'knead-bakery-panorama' AND description = 'Knead Bakery is a bakery and cafe in Panorama Healthcare Centre, Panorama.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- pep-kuils-river (researched)
UPDATE businesses SET description = 'PEP in Voortrekker Centre is a value-priced clothing and general merchandise retailer, selling affordable clothing, footwear and household basics for the whole family. The store regularly issues its own in-store sale catalogue, giving shoppers a changing selection of discounted items to browse alongside the everyday range.

As part of the wider PEP retail network found across South African shopping centres, the Kuils River branch focuses on practical, low-cost options rather than big-name labels, drawing shoppers who want to stretch a household budget without compromising on the basics.

Trading from Shop 1 in Voortrekker Centre on Van Riebeeck Road, the store is open seven days a week, including Sunday mornings, making it an easy stop to fit around a weekend shopping trip in Kuils River.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.tiendeo.co.za/stores/cape-town/pep-stores-shop-voortrekker-centre-van-riebeeck-road-kuils-river-cape-town-western-cape/12268'), description_enriched_at = datetime('now') WHERE slug = 'pep-kuils-river' AND description = 'PEP is a value clothing and general merchandise retailer in Kuils River.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- petes-pizzas-kenridge (researched)
UPDATE businesses SET description = 'Pete''s Pizzas in Kenridge is a takeaway known for pizza baked in a wood-fired oven, and its menu also includes burgers, pasta, ribs and toasted sandwiches. The business also runs a branch at Uitzicht and posts specials for each site.

Specials run through the week. On Monday, two large Favourite pizzas or two 200g sirloin steak burgers come with medium chips, and on Wednesday two large Supreme pizzas or two toasted sandwiches come with small chips. On Sundays, a large pasta comes with a free garlic pita, or 400g of ribs with chips comes with any two medium pizzas.

The Kenridge branch is in IPIC Shopping Centre on Door De Kraal Avenue, in the Durbanville area, and suits a quick pizza or burger for a family meal or a takeaway. Menu prices are subject to change without notice.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.petespizzas.co.za'), description_enriched_at = datetime('now') WHERE slug = 'petes-pizzas-kenridge' AND description = 'Pete''s Pizzas is a wood-fired pizza takeaway inside IPIC Shopping Centre, Kenridge.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- rocomamas-rondebosch-rondebosch (researched)
UPDATE businesses SET description = 'RocoMamas Rondebosch is a burger and ribs restaurant in Riverside Mall on Main Road. Diners often order the chilli burgers, bacon and cheeseburgers, and the menu includes ribs, wings, waffles and milkshakes, with Death by Chocolate frequently mentioned by reviewers.

Visitors mention fast service, a peaceful atmosphere and reasonable prices, and the restaurant offers food delivery and holds a liquor licence. Google ratings average 4.3 out of 5 from more than 2,000 ratings, and Facebook reviews average 4.8 out of 5.

The restaurant is at Shop 37 in Riverside Mall, and suits a casual meal with friends or family in Rondebosch.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://restaurantguru.com/RocoMamas-Cape-Town-7'), description_enriched_at = datetime('now') WHERE slug = 'rocomamas-rondebosch-rondebosch' AND description = 'RocoMamas Rondebosch is a burger and ribs restaurant in Riverside Mall, Rondebosch.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- shoprite-kuils-river-2 (researched)
UPDATE businesses SET description = 'Shoprite Kuils River is a full-service supermarket on Van Riebeeck Road in Bosonia, combining a general grocery store with its own in-house bakery and deli counter. Shoppers can pick up fresh bread, prepared deli items and everyday groceries all under one roof, alongside the wider Shoprite range of household and food essentials.

The branch has built a reputation locally as an affordable, no-frills option for weekly shopping, with regular customers describing it as a community staple that gets the job done even when the aisles are busy. It trades Monday to Friday from 8am to 7pm, Saturdays from 7am to 6pm and Sundays from 7am to 3pm, giving shoppers a long window to fit a full grocery run around work and family commitments.

Trading inside Kuilsriver Shopping Centre, the store suits households doing a full grocery run as well as shoppers popping in for bread or a quick deli item.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://za.africabz.com/western-cape/shoprite-kuils-river-58310'), description_enriched_at = datetime('now') WHERE slug = 'shoprite-kuils-river-2' AND description = 'Shoprite Kuils River is a supermarket inside Kuilsriver Shopping Centre, Kuils River.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- tjopshop-parow-centre-parow (researched)
UPDATE businesses SET description = 'Tjopshop is a specialist butchery in Parow Centre known for its free-range Karoo lamb, with half-lamb packs and sausages among the products shoppers return for. Customers highlight the ethically sourced, grass-fed quality of the meat, with several describing it as restaurant-grade and among the best lamb they have bought in Cape Town.

The butchery also arranges delivery for orders, with reviewers praising prompt turnaround and efficient service when buying larger packs rather than visiting in person. That combination of quality sourcing and a delivery option has built up a loyal following, with some customers saying they plan to come back to try other cuts after a first order.

Trading from Shop F1-79 in Parow Centre, on the corner of Voortrekker Road and De La Rey Street in Parow, the butchery is a good option for anyone after properly sourced lamb rather than a standard supermarket cut.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://za.africabz.com/western-cape/tjopshop-416746'), description_enriched_at = datetime('now') WHERE slug = 'tjopshop-parow-centre-parow' AND description = 'Tjopshop is a butchery in Parow Centre specialising in free-range Karoo lamb.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- woolworths-fish-hoek-town-square-fish-hoek (researched)
UPDATE businesses SET description = 'Woolworths in Fish Hoek trades as a Woolworths Foods store, the chain''s food-focused format that concentrates on groceries, fresh produce, prepared meals and everyday essentials rather than a full department-store range. It gives Fish Hoek shoppers a dedicated grocery option within Town Square without the clothing and homeware floors found at larger Woolworths branches.

The store keeps long trading hours to suit a coastal community that shops throughout the week and over weekends, open from half past eight in the morning on weekdays, from eight on Saturdays, and from eight on Sundays too, each day running into the early evening.

Trading from Fish Hoek Town Square on Main Road, the store suits residents doing a regular grocery run as well as visitors picking up food for a day at the nearby beach.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://my-catalogue.co.za/stores/fish-hoek/woolworths/town-square-shopping-centre-main-rd'), description_enriched_at = datetime('now') WHERE slug = 'woolworths-fish-hoek-town-square-fish-hoek' AND description = 'Woolworths is a supermarket inside Fish Hoek Town Square in Fish Hoek.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- brackenfell-hardware-brackenfell (researched)
UPDATE businesses SET description = 'Brackenfell Hardware is a family-owned hardware store founded in 2021, with a focus on customer service and a range that serves both do-it-yourselfers and contractors. The shop stocks nuts and bolts, power and hand tools, paint, waterproofing materials, tile adhesives, plumbing fittings, electrical equipment, lawn care products and silicone sealants.

The store offers on-site paint mixing and spray-painting equipment, and it carries more than 20 respected brands, including Kress, Cat and Alpen. Staff are on hand for expert advice and project tips, and the business says it aims to offer the lowest prices in town.

The shop is at 55 Jacaranda Street in Protea Heights, Brackenfell, and is a practical stop for anyone starting a home project or restocking the toolbox.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://brackenfellhardware.co.za/', '$[#]', 'https://www.facebook.com/Brackenfellhardware/'), description_enriched_at = datetime('now') WHERE slug = 'brackenfell-hardware-brackenfell' AND description = 'Brackenfell Hardware is a hardware store serving the Protea Heights area of Brackenfell.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- footgear-eerste-river (researched)
UPDATE businesses SET description = 'Footgear in Eerste River is a dedicated footwear store stocking brands such as adidas, Asics, Converse, Crocs, Caterpillar, Diadora, Fila and Hi-Tec, with ranges for men, women and kids. Shoppers can find everyday sneakers, work boots and children''s shoes without needing to visit a full department store.

The branch trades inside the Pick n Pay Eerste Rivier Shopping Centre, alongside independent traders such as a biltong specialist and a fresh fish counter, giving shoppers a reason to combine a footwear errand with the rest of a grocery trip. It keeps regular weekday hours from morning into the early evening, shorter hours on Saturdays and a half-day on Sundays.

Trading from Shop 9 on Pella Road in Eerste River, the store suits families restocking school shoes or anyone after a specific sneaker brand close to home.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.footgear.co.za/stores/footgear-eerste-river/', '$[#]', 'https://eersteriviercentre.co.za/shop/'), description_enriched_at = datetime('now') WHERE slug = 'footgear-eerste-river' AND description = 'Footgear is a shoe store located inside Eerste Rivier Shopping Centre, Eerste River.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- anglo-auto-athlone (researched)
UPDATE businesses SET description = 'Anglo Auto is a pre-owned vehicle dealership in Athlone, trading in both modern and classic cars across its used and new vehicle categories. Buyers can browse the dealership''s current stock online before visiting, and finance can be arranged in-house through all major banks, with an online finance application for those who want to sort payment before coming in.

The dealership also advertises finance options that do not require a driver''s licence, a detail aimed at buyers who might otherwise struggle to arrange payment through standard channels. That combination of a varied stock list and flexible finance has made it a practical stop for buyers working to a budget rather than chasing a specific marque.

Anglo Auto trades from 35 Belgravia Road in Athlone, open Monday to Friday from eight in the morning to half past five, and Saturdays from eight until one, and suits buyers after a straightforward route into a pre-owned or classic vehicle with finance sorted on site.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://angloauto.co.za', '$[#]', 'https://angloauto.co.za/contact'), description_enriched_at = datetime('now') WHERE slug = 'anglo-auto-athlone' AND description = 'Anglo Auto is a second-hand vehicle dealership on Belgravia Road, in Athlone.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- abacas-electrical-solution-tafelsig (researched)
UPDATE businesses SET description = 'Abacas Solution is a 24-hour emergency electrician and plumbing business serving the Western Cape. The team handles electrical repairs, replacements and installations, and provides plumbing for burst pipes, geysers and other urgent work.

The business presents itself as licensed and insured, with more than 20 years of experience in the province. It stresses dependable and honest assessments, fair pricing and work that stands the test of time, and says it keeps up with current industry practice.

Based in Tafelsig, Mitchells Plain, the company is available around the clock to take emergency calls, which makes it a practical choice for households and businesses that cannot wait for a daytime appointment.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://abacassolution.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'abacas-electrical-solution-tafelsig' AND description = 'Abacas Electrical Solution is an electrical contractor based in Tafelsig, Mitchells Plain.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- content-upgrade:capetown:002: 6 trading-hours updates (sourced from research, listing had none)
-- dis-chem-wynberg (hours)
UPDATE businesses SET hours = 'Mon-Fri 09:00-19:00, Sat 09:00-17:00, Sun 09:00-17:00' WHERE slug = 'dis-chem-wynberg' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- pep-kuils-river (hours)
UPDATE businesses SET hours = 'Mon-Fri 08:30-17:30, Sat 08:00-13:00, Sun 09:00-13:00' WHERE slug = 'pep-kuils-river' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- shoprite-kuils-river-2 (hours)
UPDATE businesses SET hours = 'Mon-Fri 08:00-19:00, Sat 07:00-18:00, Sun 07:00-15:00' WHERE slug = 'shoprite-kuils-river-2' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- woolworths-fish-hoek-town-square-fish-hoek (hours)
UPDATE businesses SET hours = 'Mon-Fri 08:30-18:30, Sat 08:00-18:30, Sun 08:00-18:00' WHERE slug = 'woolworths-fish-hoek-town-square-fish-hoek' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- footgear-eerste-river (hours)
UPDATE businesses SET hours = 'Mon-Thu 09:00-18:00, Fri 08:30-18:00, Sat 08:30-17:00, Sun 09:00-15:00' WHERE slug = 'footgear-eerste-river' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- anglo-auto-athlone (hours)
UPDATE businesses SET hours = 'Mon-Fri 08:00-17:30, Sat 08:00-13:00, Sun Closed' WHERE slug = 'anglo-auto-athlone' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
