-- Disambiguates chain-branch listings (Clicks/KFC/PEP/Chicken Licken/
-- Dis-Chem/Mr Price/Woolworths) flagged by Google Search Console as
-- "Duplicate, Google chose different canonical" -- each was imported
-- with just the bare brand name, auto-numbered, indistinguishable from
-- its siblings. Folds each one's real (already-known, OSM-sourced)
-- street address into the name, matching the sasol-amkor-road-lyttelton
-- pattern, and regenerates the slug from its current (already correctly
-- reassigned) suburb. See scripts/disambiguate-chain-branches.mjs.

UPDATE businesses SET name = 'Clicks Stanza Bopape Street', slug = 'clicks-stanza-bopape-street-arcadia' WHERE slug = 'clicks-pretoria-central-3';
UPDATE businesses SET name = 'Clicks Madiba Street', slug = 'clicks-madiba-street-pretoria-central' WHERE slug = 'clicks-pretoria-central-4';
UPDATE businesses SET name = 'Clicks Bosman Street', slug = 'clicks-bosman-street-pretorius-park' WHERE slug = 'clicks-pretoria-central-5';
UPDATE businesses SET name = 'Clicks Belvedere Street', slug = 'clicks-belvedere-street-trevenna' WHERE slug = 'clicks-pretoria-central-9';
UPDATE businesses SET name = 'Clicks Pretorius Street', slug = 'clicks-pretorius-street-pretoria-central' WHERE slug = 'clicks-pretoria-central-11';
UPDATE businesses SET name = 'Clicks Bancor Avenue', slug = 'clicks-bancor-avenue-menlyn' WHERE slug = 'clicks-menlyn-2';
UPDATE businesses SET name = 'Clicks Lunnon Road', slug = 'clicks-lunnon-road-brooklyn' WHERE slug = 'clicks-waterkloof-3';
UPDATE businesses SET name = 'KFC Beatrix Street', slug = 'kfc-beatrix-street-trevenna', description = 'KFC Beatrix Street is a business on Beatrix Street in Trevenna, part of the Pretoria/Tshwane metro. Opening hours: Mo-Th 06:00-22:00; Fr-Sa 06:00-23:00; Su 06:00-22:00.' WHERE slug = 'kfc-pretoria-central-2';
UPDATE businesses SET name = 'KFC Pretorius Street', slug = 'kfc-pretorius-street-pretoria-central', description = 'KFC Pretorius Street is a business on Pretorius Street in Pretoria Central, part of the Pretoria/Tshwane metro. Opening hours: Mo-Su 00:00-24:00.' WHERE slug = 'kfc-pretoria-central-3';
UPDATE businesses SET name = 'KFC Lilian Ngoyi Street', slug = 'kfc-lilian-ngoyi-street-pretoria-central', description = 'KFC Lilian Ngoyi Street is a business on Lilian Ngoyi Street in Pretoria Central, part of the Pretoria/Tshwane metro. Opening hours: Mo-Th 06:00-22:00; Fr-Sa 06:00-23:00; Su 06:00-22:00.' WHERE slug = 'kfc-pretoria-central-5';
UPDATE businesses SET name = 'KFC Paul Kruger Street', slug = 'kfc-paul-kruger-street-pretorius-park', description = 'KFC Paul Kruger Street is a business on Paul Kruger Street in Pretorius Park, part of the Pretoria/Tshwane metro. Opening hours: Mo-Su 06:00-22:00.' WHERE slug = 'kfc-pretoria-central-6';
UPDATE businesses SET name = 'KFC Francis Baard Street', slug = 'kfc-francis-baard-street-pretoria-central', description = 'KFC Francis Baard Street is a business on Francis Baard Street in Pretoria Central, part of the Pretoria/Tshwane metro. Opening hours: Mo-Sa 06:00-21:00; Su 06:00-22:00.' WHERE slug = 'kfc-pretoria-central-8';
UPDATE businesses SET name = 'KFC Helen Joseph Street', slug = 'kfc-helen-joseph-street-pretoria-central', description = 'KFC Helen Joseph Street is a business on Helen Joseph Street in Pretoria Central, part of the Pretoria/Tshwane metro. Opening hours: Mo-Th 07:00-20:00; Fr-Sa 07:00-21:00; Su 08:00-19:00.' WHERE slug = 'kfc-pretoria-central-10';
UPDATE businesses SET name = 'KFC Francis Baard Street', slug = 'kfc-francis-baard-street-arcadia', description = 'KFC Francis Baard Street is a business on Francis Baard Street in Arcadia, part of the Pretoria/Tshwane metro. Opening hours: Mo-Th 06:00-22:00; Fr-Sa 06:00-23:00; Su 06:00-22:00.' WHERE slug = 'kfc-pretoria-central-11';
UPDATE businesses SET name = 'KFC Lynnwood Road', slug = 'kfc-lynnwood-road-lynnwood-ridge', description = 'KFC Lynnwood Road is a business on Lynnwood Road in Lynnwood Ridge, part of the Pretoria/Tshwane metro. Opening hours: Mo-Su 00:00-24:00.' WHERE slug = 'kfc-menlyn-2';
UPDATE businesses SET name = 'PEP Esselen Road', slug = 'pep-esselen-road-barclay-square', description = 'PEP Esselen Road is a business on Esselen Road in Barclay Square, part of the Pretoria/Tshwane metro. Opening hours: Mo-Fr 08:30-17:30; Sa 09:00-15:00; Su 09:00-13:00.' WHERE slug = 'pep-pretoria-central-2';
UPDATE businesses SET name = 'PEP Pretorius Street', slug = 'pep-pretorius-street-pretoria-central', description = 'PEP Pretorius Street is a business on Pretorius Street in Pretoria Central, part of the Pretoria/Tshwane metro. Opening hours: Mo 08:30-17:30; Tu 09:00-17:30; We-Fr 08:30-17:30; Sa 09:00-14:00.' WHERE slug = 'pep-pretoria-central-3';
UPDATE businesses SET name = 'PEP Church Street', slug = 'pep-church-street-pretoria-central', description = 'PEP Church Street is a business on Church Street in Pretoria Central, part of the Pretoria/Tshwane metro. Opening hours: Mo 08:30-17:30; Tu 08:00-17:30; We-Fr 08:30-17:30; Sa 09:00-14:00; Su 09:00-13:00.' WHERE slug = 'pep-pretoria-central-5';
UPDATE businesses SET name = 'PEP Bloed Street', slug = 'pep-bloed-street-pretoria-central', description = 'PEP Bloed Street is a business on Bloed Street in Pretoria Central, part of the Pretoria/Tshwane metro. Opening hours: Mo-Fr 09:00-18:00; Sa 09:00-17:00; Su 09:00-13:00.' WHERE slug = 'pep-pretoria-central-6';
UPDATE businesses SET name = 'PEP Schoeman Street', slug = 'pep-schoeman-street-pretoria-central', description = 'PEP Schoeman Street is a business on Schoeman Street in Pretoria Central, part of the Pretoria/Tshwane metro. Opening hours: Mo-Fr 08:30-17:30; Sa 09:00-14:00.' WHERE slug = 'pep-pretoria-central-7';
UPDATE businesses SET name = 'PEP Steve Biko Road', slug = 'pep-steve-biko-road-trevenna', description = 'PEP Steve Biko Road is a business on Steve Biko Road in Trevenna, part of the Pretoria/Tshwane metro. Opening hours: Mo-Tu 08:00-17:00; We 09:00-17:00; Th-Fr 08:00-17:00; Sa 09:00-14:00; Su 09:00-13:00.' WHERE slug = 'pep-pretoria-central-9';
UPDATE businesses SET name = 'PEP Bureau Avenue', slug = 'pep-bureau-avenue-pretoria-central', description = 'PEP Bureau Avenue is a business on Bureau Avenue in Pretoria Central, part of the Pretoria/Tshwane metro. Opening hours: Mo-Fr 08:00-17:00; Sa 08:00-13:00.' WHERE slug = 'pep-pretoria-central-11';
UPDATE businesses SET name = 'Chicken Licken Robert Sobukwe Street', slug = 'chicken-licken-robert-sobukwe-street-trevenna' WHERE slug = 'chicken-licken-pretoria-central-3';
UPDATE businesses SET name = 'Chicken Licken Pretorius Street', slug = 'chicken-licken-pretorius-street-pretoria-central' WHERE slug = 'chicken-licken-pretoria-central-7';
UPDATE businesses SET name = 'Chicken Licken Sisulu Street', slug = 'chicken-licken-sisulu-street-trevenna' WHERE slug = 'chicken-licken-pretoria-central-8';
UPDATE businesses SET name = 'Dis-Chem Pinaster Avenue', slug = 'dis-chem-pinaster-avenue-hazelwood' WHERE slug = 'dis-chem-menlyn-2';
UPDATE businesses SET name = 'Dis-Chem Atterbury Road', slug = 'dis-chem-atterbury-road-menlyn' WHERE slug = 'dis-chem-menlyn-3';
UPDATE businesses SET name = 'Dis-Chem Bronkhorst Street', slug = 'dis-chem-bronkhorst-street-waterkloof' WHERE slug = 'dis-chem-waterkloof-2';
UPDATE businesses SET name = 'Mr Price Madiba Street', slug = 'mr-price-madiba-street-pretoria-central', description = 'Mr Price Madiba Street is a business on Madiba Street in Pretoria Central, part of the Pretoria/Tshwane metro.' WHERE slug = 'mr-price-pretoria-central-2';
UPDATE businesses SET name = 'Mr Price Thabo Sehume Street', slug = 'mr-price-thabo-sehume-street-pretoria-central', description = 'Mr Price Thabo Sehume Street is a business on Thabo Sehume Street in Pretoria Central, part of the Pretoria/Tshwane metro.' WHERE slug = 'mr-price-pretoria-central-6';
UPDATE businesses SET name = 'Mr Price Atterbury Road', slug = 'mr-price-atterbury-road-menlyn', description = 'Mr Price Atterbury Road is a business on Atterbury Road in Menlyn, part of the Pretoria/Tshwane metro.' WHERE slug = 'mr-price-menlyn-2';
UPDATE businesses SET name = 'Woolworths Gordon Hood Avenue', slug = 'woolworths-gordon-hood-avenue-centurion', description = 'Woolworths Gordon Hood Avenue is a business on Gordon Hood Avenue in Centurion, part of the Pretoria/Tshwane metro.' WHERE slug = 'woolworths-centurion-2';
UPDATE businesses SET name = 'Woolworths Rabie Street', slug = 'woolworths-rabie-street-hennopspark', description = 'Woolworths Rabie Street is a business on Rabie Street in Hennopspark, part of the Pretoria/Tshwane metro.' WHERE slug = 'woolworths-centurion-3';
UPDATE businesses SET name = 'Woolworths Atterbury Road', slug = 'woolworths-atterbury-road-menlyn', description = 'Woolworths Atterbury Road is a business on Atterbury Road in Menlyn, part of the Pretoria/Tshwane metro.' WHERE slug = 'woolworths-menlyn-6';
