-- content-upgrade:pretoria:073: 44 descriptions (6 deferred, no SQL), generated by scripts/content-upgrade/to-sql.mjs
-- business-iq-buffelsdrift (researched)
UPDATE businesses SET description = 'Business IQ, also known as BusinessIQ Consulting, is a management consultancy whose team brings together more than 30 years of combined experience in sourcing, human resources and financial services. Its sourcing work involves evaluating a company''s requirements and screening candidates so the business gets the skills it needs to improve its performance, while its HR solutions are designed through a diagnostic approach rather than a standard template.

The firm also handles payroll, tax and financial projects, which it presents as part of one combined service so that each client is advised on the business as a whole. Its stated approach is to partner with clients and draw on their expertise to produce solutions that support growth and change. The firm is based on Buffelsdrift Street in Erasmusrand, Pretoria, and suits companies that want sourcing, HR and payroll support from a single consultancy rather than several separate providers.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://za.linkedin.com/company/businessiq-consulting'), description_enriched_at = datetime('now') WHERE slug = 'business-iq-buffelsdrift' AND description = 'BusinessIQ Consulting is a small management consulting firm based in Erasmusrand, Pretoria, founded in 2014, offering HR consulting, tax and international tax structuring, industrial psychology, sourcing and headhunting, employee benefits, and financial services.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- business-triggers-centurion-central (researched)
UPDATE businesses SET description = 'Business Triggers is an alternative finance provider for South African small and medium enterprises, structuring purchase order financing, invoice discounting and secured and unsecured business loans. It also arranges specialty funding for coal and chrome supply contracts, provided the business holds a confirmed off-take agreement or supply contract to back the deal. Purchase orders it funds can come from private companies, government departments, municipalities or state-owned entities, and funding amounts range from R70,000 up to R5 million.

To place each deal, the company works with a network of investors rather than a single funding source, matching the size and structure of a facility to the client''s contract. Business Triggers is based at Central Park in Highveld Techno Park, Centurion, and it suits SMMEs that need working capital unlocked against a confirmed order or contract rather than conventional collateral-based lending.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://businesstriggers.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'business-triggers-centurion-central' AND description = 'Business Triggers is a Centurion-based alternative finance provider for South African SMMEs, offering purchase order funding, invoice discounting, and secured and unsecured business loans, including specialty financing for coal and chrome supply contracts.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- cash-crusaders-east-lynne-east-lynne (researched)
UPDATE businesses SET description = 'Cash Crusaders East Lynne is a branch of the Cash Crusaders store chain, trading from Shop 4 at East Park Centre on Baviaanspoort Road in East Lynne. Its range covers cellular phones including secondhand phones, TV, audio and video, computers, gaming, DJ and PA equipment, musical instruments, appliances, power tools, cameras, car audio, toys and watches.

The store also takes items in from customers, with its website promoting the top prices paid, and offers loans, loan extensions and a six-month lay-by for shoppers who want to spread the cost of a purchase. Trading hours are Monday to Friday from 9am to 5:30pm, Saturday from 9am to 3pm and Sunday from 9am to 1pm, and the branch can be reached on WhatsApp. It suits shoppers in East Lynne looking for electronics, appliances or tools, or for a quick sale of items they no longer need, and its listing points customers to nearby branches in Kolonnade, Silverton and Hillcrest.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://cashcrusaders.co.za/storedetails?location=EastLynne'), description_enriched_at = datetime('now') WHERE slug = 'cash-crusaders-east-lynne-east-lynne' AND description = 'Cash Crusaders East Lynne is a buy-sell-trade retailer at East Park Shopping Centre, dealing in electronics, cellphones, appliances, tools and other second-hand goods, and also offering pawn loans through its Crusaders Pawn partner.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- centurion-plumbers-centurion-blue-valley-golf-estate (researched)
UPDATE businesses SET description = 'Centurion Plumbers is a plumbing business founded in 2015 that works across the Centurion area. Its team handles emergency plumbing services around the clock, along with pipe repair and replacement to fix leaks, water heater installation, drain cleaning to clear blockages, and fixture repair and installation, from faucet repairs to new fittings. The company describes its plumbers as dedicated to excellence and customer satisfaction.

Customers can request a quote for each service through the company''s website, and the business is open 24 hours a day, every day, so urgent callers can get help at any time. Based in Rooihuiskraal at Blue Valley Golf Estate, it serves homeowners and businesses in Centurion who need dependable plumbing repairs and installations.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://centurionplumbers.africa/'), description_enriched_at = datetime('now') WHERE slug = 'centurion-plumbers-centurion-blue-valley-golf-estate' AND description = 'Centurion Plumbers is a plumbing company based in Rooihuiskraal, Centurion, offering 24-hour emergency plumbing, pipe repair and replacement, water heater installation, drain cleaning, and sewer line services. The company was established in 2015.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- chamberlain-montana-famous-for-hardware-since-1903-montana-gardens (researched)
UPDATE businesses SET description = 'Chamberlain Montana is a branch of the Chamberlain hardware chain, which has traded in South Africa since 1903 under FH Chamberlain Trading and is headquartered in Johannesburg. The Montana branch operates as a builders'' yard, handling bulk and direct sales of building materials, hardware and tools alongside a garden-centre range of plants and outdoor products. In-store services include paint mixing to match a customer''s chosen colour, and board cutting and edging for customers building or renovating their own projects.

The store trades from the corner of Dr Swanepoel Road and 3rd Avenue in Montana, Pretoria, and is open Monday to Friday from 7:30am to 5pm, Saturday from 8am to 3pm and Sunday from 9am to 1pm. It suits builders, contractors and home owners who want building materials, hardware, paint and garden supplies from a single yard.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.chamberlains.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'chamberlain-montana-famous-for-hardware-since-1903-montana-gardens' AND description = 'Chamberlain Montana is a branch of Chamberlain, a South African hardware, paint and building supplies chain trading since 1903 under FH Chamberlain Trading, headquartered in Johannesburg. The Montana Megastore branch opened in 2007.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- charming-wool-accessories-garsfontein-smallholdings (researched)
UPDATE businesses SET description = 'Charming Wool & Accessories is a specialist yarn and wool retailer trading online and from a store in Garsfontein, Pretoria. Its range covers real wool and cotton yarns in a wide choice of colours, together with the needles, hooks and other accessories knitters and crocheters need to complete a project. The store stocks established yarn brands including Elle, Kismet, Stylecraft, Vinnis and Nurturing Fibres, and is a stockist for African Expressions.

Staff are on hand to advise customers on choosing the right yarn, weight and colour for a pattern, whether they are buying in person or ordering online. The store trades from Mary Lynn Square in Garsfontein Village on Serene Street, Garsfontein, and suits knitters and crocheters, from beginners to experienced hobbyists, looking for quality yarn and accessories in one place.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.charmingwool.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'charming-wool-accessories-garsfontein-smallholdings' AND description = 'Charming Wool & Accessories is an online and Garsfontein-based retailer of yarn and wool for knitting and crochet, stocking a range of brands including Elle, Kismet, Stylecraft, Vinnis, Nurturing Fibres and African Expressions.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- cloud-accounting-pty-ltd-irene (researched)
UPDATE businesses SET description = 'Cloud Accounting is a Sage and Pastel accounting software specialist in Irene, Pretoria, that sells, installs and supports Sage software for businesses of different sizes. Its product range runs from Sage Business Cloud Accounting and Sage 50 Pastel Start and Core for small businesses, through Sage 50 Pastel Plus and Sage 200 Evolution for medium businesses, to Sage 200 Evolution with advanced add-on modules for larger companies, with Sage payroll and HR products also covered.

Its services include Sage software setup and configuration, upgrades, data conversions and customised documents and reports, along with practical on-site training for factory-floor, accounting and management staff. Remote support is offered with modern tools so clients avoid travel costs, and the firm runs project management for turnkey implementations. The company offers a free requirements assessment to help clients choose a product, which suits businesses that want a Sage package chosen, set up and supported by one local team.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.cloudacc.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'cloud-accounting-pty-ltd-irene' AND description = 'Cloud Accounting (Pty) Ltd is a Sage software reseller and consulting firm based in Irene, offering Sage Business Cloud, Sage 50, and Sage Evolution sales, installation, training, cloud migration, and monthly bookkeeping services.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- cloverfield-designer-jewellery-pierre-van-ryneveld-park (researched)
UPDATE businesses SET description = 'Cloverfield Designer Jewellery is a custom jewellery business founded in 2020 that designs and makes bespoke pieces around each client''s story, style and special moments. Its work covers pieces for engagements, weddings, anniversaries and milestones, and each design is made to be unique, using quality precious metals and gemstones. The business''s pricing page lists 9ct gold pieces, available in yellow, white and rose gold, from R8,500, and sterling silver pieces from R3,500.

Final prices depend on the chosen design, gemstones, gold weight and level of craftsmanship, so each commission is priced individually. The business is based in Pierre van Ryneveld Park in Centurion, and it suits couples and individuals who want a piece with personal meaning rather than a mass-produced design.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.cloverfieldjewellery.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'cloverfield-designer-jewellery-pierre-van-ryneveld-park' AND description = 'Cloverfield Designer Jewellery, in Pierre van Ryneveld Park, Centurion, specializes in custom jewelry design and manufacturing, particularly wedding rings and bands, including redesigning existing pieces with sentimental value, with consultations available via WhatsApp.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- coffee-on-18th-rietondale (researched)
UPDATE businesses SET description = 'Coffee on 18th is a coffee shop and café in Rietondale, Pretoria, serving coffee, cold drinks and light snacks in a casual setting. Beyond its everyday trade, the venue is available for hire for private functions, and it also hosts its own events, making it as much a small events venue as a neighbourhood coffee stop.

The café is on 18th Avenue in Rietondale, within about two kilometres of Steve Biko Academic Hospital and roughly a kilometre from Rietondale Primary School. It is open Monday to Friday from 7am to 5pm and Saturday from 8am to 3pm, closed on Sundays, and suits locals looking for a casual coffee, a bite to eat, or a venue to hire for a small gathering.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://wanderlog.com/place/details/3303485/coffee-on-18th'), description_enriched_at = datetime('now') WHERE slug = 'coffee-on-18th-rietondale' AND description = 'Coffee on 18th is a coffee shop in Rietondale, Pretoria, serving house-roasted coffee, cooked breakfasts, quiches, pancakes and sandwiches with free parking and outdoor seating; open Mon-Fri 7am-5pm and Sat 8am-3pm, closed Sundays.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- colour-hub-brummeria (researched)
UPDATE businesses SET description = 'Colour Hub is a printing, branding and manufacturing business in Pretoria that has operated since 2015, offering signage, outdoor and indoor displays, textile printing, laser cutting and CNC work, vehicle wraps and decals, and digital printing. Its product range also includes custom mats, promotional gifts, branded gazebos, pop-up banners, golf and polo shirts and aircon or inverter covers, which customers can order through its online shop.

The company says it serves businesses, home owners and institutions alike, and its site presents it as a branding and crafting business for both trade and private clients. It is based at Scientia Techno Park on Meiring Naude Road in Scientia, Pretoria, and suits companies that need signage, vehicle branding or promotional clothing produced in one place.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.colourhub.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'colour-hub-brummeria' AND description = 'Colour Hub has provided printing, branding and manufacturing services - including signage, vehicle branding, textile printing and laser cutting - for over 10 years, with clients including RE/MAX, Nissan, Ford and Audi.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- constantia-liquor-cellars-blue-bottle-liquors-constantia-park (researched)
UPDATE businesses SET description = 'Constantia Liquor Cellars trades under the Blue Bottle Liquors banner, part of a buying cooperative of independently owned liquor stores across South Africa. The Constantia Park store carries a curated selection of wines alongside a strong range of craft beers, as well as the spirits and other drinks a liquor store typically stocks, giving shoppers a tighter, more selective range than a generic bottle store.

Customers can shop in store or have orders delivered the same day, which suits those who want their wine or beer brought to them rather than collected. The store trades from the Gebou Building on Langenhoven Street in Constantia Park, Pretoria, and is open Monday to Saturday from 9am to 6:30pm. It is a good fit for shoppers who want a considered wine and craft beer selection backed by quick local delivery.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://bluebottleliquors.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'constantia-liquor-cellars-blue-bottle-liquors-constantia-park' AND description = 'This Constantia Park store trades under the Blue Bottle Liquors banner, part of the Blue Bottle Group, a buying cooperative of independent liquor store owners in South Africa selling wine, beer, and spirits.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- coolblast-window-solar-panel-cleaning-kloofsig (researched)
UPDATE businesses SET description = 'Coolblast Window & Solar Panel Cleaning is a professional cleaning service based in Lyttelton Manor, Centurion, specialising in window cleaning and solar panel cleaning for homes and businesses. Its process uses eco-friendly cleaning solutions designed to lift dirt and grime without damaging panels or glass, and for solar installations the cleaning method is designed to support panel performance and extend their working lifespan.

Before any job, the company provides an on-site estimate so customers know the cost upfront rather than being quoted sight unseen. It trades from Celliers Lane in Lyttelton Manor and is open Monday to Friday from 8am to 5pm. It suits home owners and businesses who want their windows or solar panels professionally cleaned, including those wanting to protect the return on a solar investment.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://coolblast.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'coolblast-window-solar-panel-cleaning-kloofsig' AND description = 'Coolblast Window & Solar Panel Cleaning is based in Lyttelton Manor, Centurion, providing solar panel cleaning using reverse osmosis water and eco-friendly, chemical-free techniques, along with exterior window cleaning, for clients across Gauteng.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- copalcor-trading-group-pretoria-hermanstad (researched)
UPDATE businesses SET description = 'Copalcor Trading Group''s Pretoria branch is a metal supplier trading from Hermanstad, Pretoria, as part of the wider Copalcor group. The group manufactures and supplies copper, brass and aluminium products, and the Pretoria branch draws on that specialisation to supply these non-ferrous metals to customers in the area.

The branch is based at Kuper Legh Industrial Park, on the corner of E''skia Mphahlele Drive and Moot Street in Hermanstad, Pretoria, and keeps weekday trading hours. It suits businesses and tradespeople in and around Pretoria who need copper, brass or aluminium stock supplied locally rather than ordered from a national depot.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.copalcor.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'copalcor-trading-group-pretoria-hermanstad' AND description = 'Copalcor Trading Group''s Pretoria branch, based in Hermanstad, distributes copper, brass and aluminium semi-finished products manufactured by Copalcor, South Africa''s largest producer of non-ferrous metal products, including busbar systems and earthing protection solutions.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- copperleaf-spa-gym-copperleaf-golf-estate (researched)
UPDATE businesses SET description = 'Copperleaf Spa & Gym is the spa and fitness facility at Copperleaf Golf and Country Estate in Centurion, offering a spa treatment menu alongside a fully equipped gym. It forms part of a wider estate that also includes an 18-hole Ernie Els golf course, a café and bar, conference facilities, bicycle trails, tennis courts and a swimming pool, giving residents a full range of leisure facilities on their doorstep.

Access to the spa and gym is for residents and members of the estate rather than the general public. The facility is on Ernie Els Boulevard within Copperleaf Golf and Country Estate, Centurion, and suits residents who want to combine a gym session or spa treatment with the estate''s other golf, dining and leisure amenities.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.copper-leaf.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'copperleaf-spa-gym-copperleaf-golf-estate' AND description = 'Copperleaf Spa & Gym is the spa and fitness facility at Copperleaf Golf and Leisure Estate in Centurion, offering a spa treatment menu alongside a fully equipped gym for estate members and guests.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- coreformation-irene (researched)
UPDATE businesses SET description = 'CoreFormation is a performance psychology consultancy in Irene Security Estate, Centurion, that applies researched psychological techniques to improve performance in the workplace. Its work covers four service areas: individual performance, group performance, company performance and sport performance, and it works with individuals, groups, companies and sports teams.

The firm''s premise is that a business has to develop its people as well as its technical skills, and its psychologists are trained to study behaviour, analyse thinking patterns and modify interaction styles to create change. It describes its approach as business performance psychology, combining strategic positive psychology with approaches underpinned by science. It suits organisations and teams that want to build a stronger mind-set alongside their existing skill-set.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://coreformation.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'coreformation-irene' AND description = 'CoreFormation is a performance psychology consulting firm based in Irene Security Estate, Centurion, that works with individuals, groups, companies and sport teams to apply psychological techniques to improve mindset, behaviour and organisational performance.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- coreworks-consulting-bryntirion (researched)
UPDATE businesses SET description = 'Coreworks Consulting is a skills development consultancy in Pretoria whose team describes itself as skills development architects, focused on tailored training, expert guidance and workforce development. Its services cover skills development and SETA compliance, HR consultancy, B-BBEE and employment equity support, training and development, accreditation and regulatory support, and integrated workforce development solutions.

The firm says it bridges the gap between potential and performance by carrying out training needs analyses and designing learning and development programmes for each client''s workforce, with sector-specific knowledge behind its methods. It works with organisations across diverse sectors, and it is based on Pretorius Street in Arcadia, Pretoria. It suits employers who need SETA and B-BBEE compliance handled alongside their training.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://coreworksconsulting.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'coreworks-consulting-bryntirion' AND description = 'Coreworks Consulting is a business consulting firm in Arcadia, Pretoria, specializing in skills development, SETA compliance, HR consultancy, and B-BBEE and employment equity support, serving industries including technology, healthcare, manufacturing, and financial services.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- craftpro-industrial-workwear-safety-supplier-erasmuskloof (researched)
UPDATE businesses SET description = 'CraftPro is a South African supplier of personal protective equipment and industrial workwear, trading online and from Erasmuskloof in Pretoria. Its store describes the range as PPE and workwear built for real-world South African conditions, covering technical workwear, hi-visibility reflective clothing, rainwear, overalls and shirts, and a women''s workwear line sold as Crafted for Her.

Safety footwear is a major category, with brands including Sigma, Pioneer, DOT, Altitude and Interceptor. The store also stocks hand, ear, head, face and eye protection, from gloves and earplugs to hard hats, face shields and welding helmets, along with fall protection, harnesses and lanyards, respiratory protection and disposable coveralls, gloves and aprons. It suits businesses and individuals who need workplace protective gear from one supplier.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.craftpro.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'craftpro-industrial-workwear-safety-supplier-erasmuskloof' AND description = 'CraftPro is an online and Erasmuskloof-based supplier of industrial workwear and safety equipment, offering technical and hi-visibility clothing, safety boots, PPE, and security uniforms at wholesale prices with bulk order delivery for businesses.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- crawford-international-pretoria-lukasrand (researched)
UPDATE businesses SET description = 'Crawford International Pretoria provides private education from pre-primary through preparatory and college level, covering Grade 0000 to Grade 12. The school is part of ADvTECH''s Schools Division, one of South Africa''s largest private education groups, which gives it the backing of a larger network alongside its own campus and teaching staff.

Sports facilities on campus include cricket and soccer fields, tennis, netball and basketball courts, and a 25-metre heated swimming pool used alongside a separate training pool; the college phase also has its own technology centre. The school is based at 555 Sibelius Street in Lukasrand, Pretoria, and suits families looking for a single private school that carries pupils from their first years of schooling through to matric.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.crawfordinternational.co.za/pretoria'), description_enriched_at = datetime('now') WHERE slug = 'crawford-international-pretoria-lukasrand' AND description = 'Crawford International Pretoria is a private, co-educational school in Lukasrand offering pre-primary, primary and secondary IEB-curriculum education for pupils aged 3 to 18, with sports facilities including a swimming pool and cricket field.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- credo-business-college-lynnwood-glen (researched)
UPDATE businesses SET description = 'Credo Business College is an accredited distance learning college in Lynnwood Glen, Pretoria, offering accounting qualifications for learners who are new to accounting as well as people already working in the field. Its course list covers Accounting Technician (AT(SA)) certificates at NQF levels 3 to 5, plus public sector accounting and local government accounting qualifications and FET certificates at NQF level 4.

The college says its courses are accredited by one of the world''s leading accountancy bodies, and that it has been helping learners since 2008. Its delivery model combines distance learning with one-on-one support and live online sessions, with a flexible schedule. It is based in Lynnwood Bridge Office Park on Daventry Street, and it suits people who want a recognised accounting certificate that they can study around work.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://credobusinesscollege.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'credo-business-college-lynnwood-glen' AND description = 'An accredited distance learning college offering SAICA-accredited Accounting Technician certificates at NQF levels 3 to 5, including Public Sector and Local Government Accounting qualifications, via flexible online study with three intakes a year.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- csi-security-clydesdale (researched)
UPDATE businesses SET description = 'CSI Security, which stands for Complete Security Intelligence, is a security company in Pretoria that protects homes, estates and businesses. Its services include 24/7 armed response, close protection, on-site manned guarding, security systems and monitoring, tracking and recovery, and area closure specialist work. The company says it assesses each situation carefully before recommending a solution.

Its service is built on rapid armed response, highly trained security personnel and advanced security equipment, and it says its proactive approach helps prevent incidents before they happen. The firm operates around the clock from its office on Church Avenue in Lynnwood, Pretoria. It suits households, estates and businesses that want dependable security across Pretoria and the surrounding areas.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.csisecuritysa.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'csi-security-clydesdale' AND description = 'CSI Security (Complete Security Intelligence), based in Lynnwood, Pretoria, provides 24/7 armed response, close protection, manned guarding, and security systems including CCTV, alarms and access control, along with tracking and recovery services.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- ctmm-solutions-eco-park (researched)
UPDATE businesses SET description = 'CTMM Solutions is an SAP consulting firm founded in 2017 that provides end-to-end ERP solutions, covering implementation, support, upgrades, consultancy and training. Its core SAP modules are SAP EAM for plant maintenance and enterprise asset management, SAP PS for project systems, and SAP Projects and Portfolio Management, and its SAP services include design and development, solution support and coaching.

The company says it follows industry best-practice standards when implementing business solutions, and it avoids unnecessary customisation of standard SAP content. It is based on Witch-Hazel Street in Eco Park, Centurion, and suits organisations that run SAP for plant maintenance, project systems or portfolio management and need both implementation and ongoing support.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://ctmm-solutions.com/'), description_enriched_at = datetime('now') WHERE slug = 'ctmm-solutions-eco-park' AND description = 'CTMM Solutions, based in Eco Park, Centurion and established in 2017, is an ERP consulting firm specialising in SAP EAM (Plant Maintenance), SAP PS and SAP PPM, offering implementation, support, upgrades and training.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- cubbs-foods-elardus-park (researched)
UPDATE businesses SET description = 'Cubbs Foods is a family-run South African maker of party dip mixes and salad dressing mixes, operating since 1993 from Elardus Park in Pretoria. Its range is split into traditional and smooth and creamy party dips, plus creamy and vinaigrette dressings, and products such as the Onion and Garlic and Guacamole dips are sold in packs of twelve 15g sachets.

Each mix is made to be finished at home with a base such as cream cheese, sour cream, olive oil and vinegar, fresh avocado, or milk and mayonnaise, so that a fresh dip or dressing can be on the table in about five minutes, according to the company. The company says it uses no fillers and calls its party dip a premium favourite that has been on supermarket shelves since 1993. It suits hosts who want a quick dip or dressing for a gathering.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.cubbs.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'cubbs-foods-elardus-park' AND description = 'Cubbs Foods is a South African manufacturer and distributor of party dip mixes and salad dressing sachets, operating since 1993 and stocked at major retailers including Checkers, Pick n Pay, Spar, and Walmart.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- dafron-villieria-villieria (researched)
UPDATE businesses SET description = 'Dafron Security & Defence is an electronic security equipment supplier that sells to both trade and retail customers, operating from the Neuway Building on the corner of 24th Avenue and Pierneef Street in Villieria, Pretoria. The company specialises in electric fencing and perimeter control equipment, automation systems for domestic and commercial markets, access control equipment, CCTV and related products, intruder detection systems, intercom and communication products, and remote control security lighting.

Its stated mission is to distribute and market only the best products available locally and internationally, and it describes a vision of forming joint ventures with local and international security equipment manufacturers. The company backs its suppliers with in-house training and with technical, design and costing support suited to local market conditions, and it also offers repairs. It suits trade and retail buyers who want a range of security products from one local distributor.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.dafron.co.za/about-us'), description_enriched_at = datetime('now') WHERE slug = 'dafron-villieria-villieria' AND description = 'Dafron Security & Defence is a Pretoria-based electronic security retailer supplying home automation systems, smart security cameras, wireless alarm systems, smart switches and intercom or access control products to trade and retail customers.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- damp-proofing-specialists-gauteng-elardus-park (researched)
UPDATE businesses SET description = 'Damp Proofing Specialists is a waterproofing and damp-proofing contractor that has served Gauteng since 2000, with more than 25 years of experience. Its services include rising damp treatment and repair, wall damp proofing, torch-on sheet membrane waterproofing for flat roofs, decks and balconies, tile and concrete roof repairs, basement and cellar waterproofing with tanking and drainage, and polyurethane liquid waterproofing membranes.

The company says it is trained and certified by Derbigum and applies Derbigum waterproofing systems to the manufacturer''s installation standards. Its work carries a 10-year guarantee that is insurance-backed on all jobs. The business is based in Elardus Park, Pretoria, with its office open Monday to Friday from 8am to 5pm, and it serves residential and commercial property owners with damp and leak problems.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.dampproofingspecialists.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'damp-proofing-specialists-gauteng-elardus-park' AND description = 'Damp Proofing Specialists is a Gauteng-based waterproofing and damp-proofing contractor offering rising damp treatment, torch-on waterproofing, roof repairs, basement and cellar waterproofing, and polyurethane coatings, with work backed by a 10-year insurance-backed guarantee.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- dc-lubricants-pty-ltd-shere (researched)
UPDATE businesses SET description = 'DC Lubricants is a lubricant supplier based on Wapadrand Road in Wapadrand, Pretoria. It supplies engine oils, gear and transmission oils, greases, coolants and antifreeze, and hydraulic oils, and it is an accredited reseller of Shell, Caltex, Engen, Valvoline, Fuchs and Autolube products, so customers can choose from several major lubricant brands in one place.

The company says that choosing the right lubricant is essential, and it offers expert advice to help customers find a tailor-made solution that meets component specifications. It describes its products as premium at affordable prices, with trustworthy service and a quick turnaround in emergencies. It suits motorists, workshops and businesses that need reliable lubricants, including bulk supply, with trade pricing available.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.dclubricants.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'dc-lubricants-pty-ltd-shere' AND description = 'DC Lubricants is a Wapadrand-based lubricant supplier to the transport, industrial and mining sectors, and an authorised reseller of Autolube, Fuchs, Valvoline, Shell, Engen and Caltex lubricant, grease, coolant and hydraulic oil products.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- die-ho-rskool-wonderboom-wonderboom (researched)
UPDATE businesses SET description = 'Die Hoërskool Wonderboom is a public high school in Wonderboom-Suid, Pretoria, organised with dedicated administration, finance, sport, culture, marketing and counselling functions to support its learners and the wider school community. This structure means each area of school life, from sports teams to pastoral counselling, is coordinated by its own function rather than left to the classroom alone.

The school day runs from 7:25am to 2:05pm, Monday to Friday, giving structure to the academic and extramural programme for its pupils. The school is based at 1050 Steve Biko-Rylaan in Wonderboom-Suid, Pretoria, and suits families in the area looking for a public high school with organised sport, culture and support services alongside its academics.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.wonnies.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'die-ho-rskool-wonderboom-wonderboom' AND description = 'Die Hoerskool Wonderboom is an Afrikaans-medium high school in Wonderboom, Pretoria, serving grades 8 to 12, with facilities including a gymnasium, a high-performance development centre, a multi-functional sports facility, and a school cafeteria.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- die-kantoor-pub-restaurant-de-wilgers (researched)
UPDATE businesses SET description = 'Die Kantoor Pub & Restaurant is a pub and restaurant in Die Wilgers, Pretoria, serving casual dining that ranges from burgers, ribs and tramezzini to pizza, salads and chicken dishes. It operates as a sports bar, with big screens for live sports and a programme of live entertainment that includes a recurring Thursday quiz night and live music.

The venue offers dine-in and takeaway service, with outdoor seating, table reservations and delivery for customers who would rather eat at home. It trades from the Willow Way Shopping Centre on Lynnwood Road in Die Wilgers, and suits groups and regulars looking for pub food, a drink and a big screen for the game, or a seat at the Thursday quiz night.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.facebook.com/DieKantoorPub/'), description_enriched_at = datetime('now') WHERE slug = 'die-kantoor-pub-restaurant-de-wilgers' AND description = 'Die Kantoor Pub & Restaurant is a pub and restaurant in Willow Way Shopping Centre, Die Wilgers, serving pub-style food such as ribs, burgers and tramezzinis alongside drinks, live music and big-screen sports.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- dikolobe-attorneys-inc-pretoria-central (researched)
UPDATE businesses SET description = 'Dikolobe Attorneys Inc is a law firm founded in 2017 and based in Protea Towers on Paul Kruger Street in Pretoria Central. The firm describes itself as engaged in research and development on various aspects of the law, with a team of staff from different backgrounds. Its listed practice areas include divorce and maintenance matters, litigation, labour and employment, real estate and intellectual property work.

The firm says it aims to move each matter along an appropriate timescale, give cost-effective guidance and support throughout, and keep complications to a minimum. It also highlights sensitivity in delicate negotiations and clear communication and reporting adapted to each client''s needs. It suits individuals and businesses in Pretoria who want a legal consultation with a firm that is aware of the practical concerns behind each matter.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://admin364900.wixstudio.com/dikolobe-attorneys/about', '$[#]', 'https://www.facebook.com/dikolobeattorneys/'), description_enriched_at = datetime('now') WHERE slug = 'dikolobe-attorneys-inc-pretoria-central' AND description = 'Dikolobe Attorneys Inc is a Pretoria Central law firm founded in 2017, handling divorce, maintenance, custody and eviction matters alongside labour disputes, civil and commercial claims, RAF claims, and contract drafting and negotiation.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- djr-strydom-professional-land-surveyors-tijger-valley (researched)
UPDATE businesses SET description = 'DJR Strydom Professional Land Surveyors is a land surveying firm established on 1 April 2007 and based in Pretoria. Its services include cadastral surveys, legal cadastral surveys, topographical surveys, engineering surveys, sectional title surveys and aerial photogrammetry. The firm describes itself as a leader in land surveying and engineering surveys.

The office is in Gauteng, but the company says most of its work is carried out in other provinces and African countries, so clients outside the Pretoria area are regularly served. Its founder is a professionally registered land surveyor with the South African Geomatics Council and the South African Geomatics Institute. It suits developers, property owners and engineers who need a registered surveyor for boundaries, sectional titles, site mapping or aerial survey work.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.djrstrydom.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'djr-strydom-professional-land-surveyors-tijger-valley' AND description = 'A professional land surveying firm founded in 2007, offering cadastral, topographical, engineering and sectional-title surveys as well as aerial photogrammetry, based in Pretoria East and operating across South Africa and other African countries.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- dkm-property-development-pty-ltd-midfields-estate (researched)
UPDATE businesses SET description = 'DKM Property Development is a civil engineering, building contracting and property development company established in 2014. It describes itself as a 100% Black-owned company and specialises in commercial, retail, industrial, government and residential construction. Its services include project management, plan drafting and submission, and construction work across these sectors.

The company provides quotations at no cost, and it drafts and submits plans that are approved by local authorities. Its services also include an independent engineer who stamps plans for council, site inspections and the issuing of a certificate. The business is based on Highlands Estate in Mooikloof Ridge, Pretoria, and it suits clients who want one firm to handle engineering, building and plan approval for a development.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://dkmpd.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'dkm-property-development-pty-ltd-midfields-estate' AND description = 'A 100% Black-owned civil engineering, building contracting and property development company established in 2014, based at Mooikloof Ridge, Pretoria, offering commercial, retail, industrial, government and residential construction along with plan drafting and submission.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- doppio-zero-southdowns-southdowns (researched)
UPDATE businesses SET description = 'Doppio Zero Southdowns is a branch of the Doppio Zero casual dining chain, trading from Shop 52 in the Southdowns Shopping Centre on Karee Street in Irene. The restaurant is known for its signature wood-fired oven and has an onsite bakery that bakes freshly baked breads and pastries for the restaurant.

The branch offers a relaxed outdoor seating area, weather permitting, and a baby-friendly atmosphere with a baby chair and kids menu. Bookings are accepted, parking is available on site within the shopping centre, and the restaurant has wheelchair access through the front entrance and wheelchair restroom facilities. Its trading hours are Sunday and Monday from 7am to 9pm, Tuesday to Thursday from 7am to 10pm, and Friday and Saturday from 7am to 10:30pm, so it suits families and groups who want a relaxed meal near home.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://doppio.co.za/restaurant/irene/'), description_enriched_at = datetime('now') WHERE slug = 'doppio-zero-southdowns-southdowns' AND description = 'Doppio Zero Southdowns is a branch of the Doppio Zero casual dining chain in Southdowns Retail Centre, Irene, Centurion, featuring a wood-fired oven and an onsite bakery for freshly baked breads and pastries.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- dr-rebuilds-donkerhoek (researched)
UPDATE businesses SET description = 'DR Rebuilds is a machine rebuild and refurbishment business on Plot 41 in Donkerhoek, Pretoria East. It specialises in rebuilding, refurbishing and overhauling heavy-duty machinery, with a focus on drill rigs. The business was founded in 2019 and grew out of Hyperion Drilling and Manufacturing, which has been building drill rigs since 2008, after the demand for older rigs to be renovated became clear.

The company says it has completed more than 15 major rebuilds since opening, along with many smaller repairs and maintenance jobs. It works alongside Hyperion Drilling and Krios Engineering, which helps it keep up with the latest improvements in the field. It suits owners of drill rigs and other heavy machinery who need an older machine rebuilt, refurbished or repaired.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://drrebuilds.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'dr-rebuilds-donkerhoek' AND description = 'DR Rebuilds is a machine rebuild and refurbishment business based on Plot 41, Donkerhoek, in Pretoria East, founded in 2019 by Kenny Truter to specialize in the rebuilding, refurbishment and overhauling of machinery.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- dr-siakam-l-inc-pretoria-central (researched)
UPDATE businesses SET description = 'This private gynaecology and obstetrics practice in Pretoria is run by an obstetrician and gynaecologist who works full time in the practice. Its services cover obstetrics, including pregnancy care, and gynaecology for problems not related to pregnancy. The practice''s background includes postgraduate training in obstetrics and gynaecology, a diploma from the College of Obstetricians and Gynaecologists of South Africa, and minimal access (laparoscopic) surgery training.

Fertility management is also part of the practice, with training in assisted reproductive technology and clinical embryology at a fertility centre in Chennai, India. The website says the practice cares for couples facing fertility problems alongside general obstetric and gynaecological care. It suits women who want a practice focused on pregnancy, gynaecological treatment or fertility support in Pretoria, and bookings can be made through the website.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.drsiakam.co.za/about'), description_enriched_at = datetime('now') WHERE slug = 'dr-siakam-l-inc-pretoria-central' AND description = 'Dr L Siakam is an obstetrician and gynaecologist with a special interest in fertility, offering pregnancy care, minimally invasive laparoscopic surgery and assisted reproductive technology at Mediclinic Muelmed Hospital and other Pretoria facilities.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- dw-outdoor-marketing-woodhill-golf-estate (researched)
UPDATE businesses SET description = 'DW Outdoor Marketing is a billboard advertising company with more than 15 years in the industry, operating billboard sites in premium locations across Gauteng and the Western Cape. Its offering covers a range of billboard formats to suit different budgets and locations, along with structure design, installation and ongoing site maintenance, so clients can book a site without managing the physical structure themselves.

Its site locations include Woodlands, Woodhill, Lynnwood, Dely Road and Garsfontein in Pretoria, along with sites on the N4, Nellmapius, the R21 and Solomon Mahlangu. The company''s office is at 30 Wanderers Crescent in Woodhill Estate, Pretoria, and it suits advertisers who want outdoor billboard space in established, high-traffic locations without handling the structure or site maintenance themselves.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://dwoutdoormarketing.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'dw-outdoor-marketing-woodhill-golf-estate' AND description = 'DW Outdoor Marketing is a billboard advertising company that has operated for over 15 years, providing premium billboard sites, structure design, installation and site maintenance for advertisers across Gauteng and the Western Cape.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- ear-institute-lynnwood-menlyn (researched)
UPDATE businesses SET description = 'Ear Institute Lynnwood is a branch of the Ear Institute, a South African audiology network that has operated since 1975. The Lynnwood branch offers hearing tests, hearing aids including Phonak devices, paediatric audiology, tinnitus management, hearing protection, wax removal and hearing aid maintenance. The network also covers cochlear implants and medical aid benefits for hearing care.

The team describes its audiologists as caring, and says it extends the life of hearing aids with professional cleaning and servicing. The branch is at 76 Alcade Road in Lynnwood Manor, Pretoria, and suits anyone looking for a hearing test or hearing aids in Pretoria, from children to adults, with appointments requested through the branch page.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://earinstitute.co.za/branch/ear-institute-lynnwood/'), description_enriched_at = datetime('now') WHERE slug = 'ear-institute-lynnwood-menlyn' AND description = 'Ear Institute Lynnwood is a branch of the Ear Institute, a South African audiology network operating since 1975, offering hearing tests, hearing aid fittings (including Phonak devices), and free in-house hearing aid cleaning.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- easy-steel-structures-kirkney (researched)
UPDATE businesses SET description = 'Easy Steel Structures is a Pretoria-based construction company, registered as Easy Steel Structures (Pty) Ltd, with more than 20 years of industry experience. It offers steel structures and rigging, concrete work including columns, slabs and floors, ground works that prepare the foundation for a project, and airless spray painting for interior, exterior and roof surfaces, along with liquid rubber sealing.

The company also provides property development such as renovations and new factory construction, project management for timely completion, and new home construction built from the ground up. It describes itself as a trusted partner in steel construction and building projects, and says it delivers quality workmanship at good value. The business is based at Zandpark on Richards Bay Avenue in Kirkney, Pretoria West, and it suits clients who need steel, concrete and building work handled by one contractor.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.easysteel.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'easy-steel-structures-kirkney' AND description = 'Easy Steel Structures is a Pretoria-based construction company with over 20 years in the industry, offering steel structures and rigging, concrete work, foundation and ground preparation, property development, and airless spray painting services.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- electroweb-pty-ltd-koedoespoort (researched)
UPDATE businesses SET description = 'Electroweb (Pty) Ltd is a South African manufacturer of electronic inverters, LED products, lighting assemblies and heating products. The company was established in 1990, when it started out as a small 60 square-metre operation with just four employees, and has grown over more than three decades into a substantially larger manufacturing facility serving its product range to the market today.

The company remains an active, registered private company, trading from Blesbok Avenue in Koedoespoort Industrial, Pretoria. Its product line, spanning inverters, LED lighting assemblies and heating equipment, suits businesses, installers and resellers who want electronic and electrical products manufactured by an established South African company rather than sourced from an importer.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.ccbc.co.za/component/mtree/manufacturing/manufacturing-electrical/206-electroweb'), description_enriched_at = datetime('now') WHERE slug = 'electroweb-pty-ltd-koedoespoort' AND description = 'Electroweb (Pty) Ltd is a Koedoespoort Industrial manufacturer established in 1990, originally specialising in electrical and electronic equipment for the rail industry before expanding into LED lighting technology in partnership with Seoul Semiconductor.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- elev8web-web-design-seo-pretoria-heatherview (researched)
UPDATE businesses SET description = 'Elev8Web is a web design and SEO agency in Pretoria that builds custom websites for businesses across Gauteng. Its services are web design, web development, SEO services, website maintenance and local SEO. The agency describes its approach as combining strategic web design, high-performance development and SEO into digital platforms that look good and perform well, and its site cites a 90+ PageSpeed score.

Its maintenance service covers ongoing updates, backups and security to keep a website reliable after launch, while its local SEO work aims to make a business more visible when customers search for its services in its area. The agency''s office is at 90 First Avenue in Karenpark, Pretoria. It suits businesses that want a website built to attract customers and support measurable growth online.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://elev8web.agency/'), description_enriched_at = datetime('now') WHERE slug = 'elev8web-web-design-seo-pretoria-heatherview' AND description = 'Elev8Web is a Pretoria-based web design and SEO agency offering custom website design and development, WordPress builds, technical and local SEO, and website maintenance for businesses across Gauteng, including Pretoria, Johannesburg and Centurion.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- elevate-webdev-wierdapark (researched)
UPDATE businesses SET description = 'Elevate WebDev is a digital solutions company in Wierdapark, Centurion, that creates professional websites, games and apps, media and content, and marketing for businesses, organisations and individuals across South Africa. The company says it serves clients locally and internationally, and its work is organised across five specialist divisions: web development and design, media and content creation, marketing, games and apps, and a training centre.

The training side offers courses in digital skills, which the company presents as career-focused training for people who want to build their own digital expertise. Its approach is to design each solution around the client''s goals, whether that means strengthening an online presence, promoting a business or bringing a creative idea to life. The company is based at Susan Street in Wierdapark, and it suits businesses and individuals who want one team to handle their digital needs.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.elevate.web.za/'), description_enriched_at = datetime('now') WHERE slug = 'elevate-webdev-wierdapark' AND description = 'Elevate WebDev is a Centurion-based digital solutions company offering web development and design, game and app development, promotional video and content creation, social media marketing, and training courses and internships in digital skills.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- elikai-printing-doornpoort (researched)
UPDATE businesses SET description = 'Elikai Printing is a printing and branding business in Doornpoort, Pretoria. It offers signage for businesses, events and promotions, vehicle branding from door branding and partial wraps to full vehicle wraps, and embroidery for uniforms, caps and corporate clothing. It also prints garments using DTF and UV DTF transfers, and produces wide-format solvent prints for banners, vinyl and advertising displays.

The business also supplies business cards, flyers and branded marketing material, along with custom sublimation, engraving, stickers and personalised gifts. It says it combines creative design, professional printing and personal service, and it describes its work as premium quality with detailed finishing. It suits businesses, events and individuals who want branded products made to their own design.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.elikaiprintingsa.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'elikai-printing-doornpoort' AND description = 'Elikai Printing is a Doornpoort-based printing and branding company offering signage, vehicle branding and wraps, embroidery, DTF/UV DTF garment printing, solvent printing for banners, business printing, and custom sublimation and engraving products.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- elna-rudman-brokers-cc-wingate-park (researched)
UPDATE businesses SET description = 'This independent short-term and life insurance brokerage in Wingate Park, Pretoria, has more than 30 years of experience. It places cover with insurers including Santam, Auto & General, Discovery Insure and Momentum Short-Term, and it says it only partners with high-end, ethical insurers so that cover is robust and reliable. Its services also include will writing and updating, and full insurance administration from first contact onwards.

The brokerage states that it is fully compliant with the FAIS law and regulated by the FSCA and FIC, and that all underwriting is completed at the start of a policy rather than at claims stage. Clients speak directly with a knowledgeable advisor rather than a call centre, and the firm offers multiple quote options and a smooth claims process. It is open Monday to Friday from 8am to 4:30pm, and it suits people who want personal advice on short-term and life cover.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.elnarudman.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'elna-rudman-brokers-cc-wingate-park' AND description = 'Elna Rudman Brokers CC is an independent short-term and life insurance brokerage in Wingate Park, established in 1998, placing cover with insurers such as Santam, Auto & General, Discovery Insure and Momentum Short-Term.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- elso-viljoen-associates-monument-park (researched)
UPDATE businesses SET description = 'Elso Viljoen & Associates is a law firm in Monument Park, Pretoria, that provides specialised legal representation to individuals and companies. Its practice areas include civil, criminal, commercial, contractual, family, insurance, labour, municipal and property law, and its speciality is criminal defence litigation. The firm is assisted by a team of attorneys, advocates and an immigration expert, and it also handles immigration matters.

The firm describes itself as a dynamic and quality-driven practice that works to high ethical and professional standards, with an environment of service excellence. Its website presents the firm as a guide through the South African legal system for both individuals and companies. It suits people in Pretoria who need court representation or legal advice across these practice areas, including immigration.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://evalaw.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'elso-viljoen-associates-monument-park' AND description = 'Elso Viljoen & Associates is a Monument Park law firm specialising in criminal defence litigation, established in 2014, also handling immigration matters with a team of attorneys, advocates and an immigration law expert.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- enact-consulting-erasmia (researched)
UPDATE businesses SET description = 'Enact Consulting is a female-owned legal and consulting practice in Erasmia, Centurion, that helps individuals clear their records and document their status. Its services include expungement applications to remove qualifying criminal records, presidential pardons for serious offences that do not qualify for expungement, police clearance certificates, apostilles, authentication and notary services, and sworn translation for official documents.

The practice also handles family law, labour law, divorce, commercial law, immigration and conveyancing matters. It assists with letters of non-impediment, unabridged birth and marriage certificates, retention of citizenship, registration of foreign and local marriages or divorces, surname changes after marriage or divorce, and fast-tracking of existing applications. It is based in Shop 4 on Bruno Street and is open Monday to Thursday from 8am to 5pm and on Friday from 8am to 2pm, and it suits people applying for work, studying, travelling or rebuilding after a past mistake.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://enactconsulting.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'enact-consulting-erasmia' AND description = 'Enact Consulting is a legal and attorneys practice in Erasmia handling family law, labour law, divorce, commercial law, immigration and conveyancing matters, including expungement applications, police clearance certificates and document notarising/apostille services.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- engel-v-lkers-pretoria-sterrewag (researched)
UPDATE businesses SET description = 'Engel & Völkers Pretoria operates as Engel & Völkers Waterkloof, part of the international Engel & Völkers real estate network. The office covers residential properties, investment properties, luxury homes and commercial space, with agents serving Waterkloof, Groenkloof, Brooklyn, Lynnwood, Menlo Park, Hazelwood, Constantia Park and other Pretoria suburbs, and working with clients in both Afrikaans and English.

The office is based at 85 George Storrar Drive in Groenkloof, Pretoria, and is open Monday to Friday from 8am to 5pm. It suits buyers, sellers and investors across these eastern Pretoria suburbs who want an agency that can place a listing with an international property brand while working locally across several price points, from standard homes to luxury and commercial property.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.engelvoelkers.com/en-za/waterkloof/'), description_enriched_at = datetime('now') WHERE slug = 'engel-v-lkers-pretoria-sterrewag' AND description = 'Engel & Völkers Pretoria is a real estate agency on George Storrar Drive, Groenkloof, offering residential sales, rentals and property management services as part of the global Engel & Völkers network.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- content-upgrade:pretoria:073: 3 trading-hours updates (sourced from research, listing had none)
-- chamberlain-montana-famous-for-hardware-since-1903-montana-gardens (hours)
UPDATE businesses SET hours = 'Mon-Fri 07:30-17:00, Sat 08:00-15:00, Sun 09:00-13:00' WHERE slug = 'chamberlain-montana-famous-for-hardware-since-1903-montana-gardens' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- coffee-on-18th-rietondale (hours)
UPDATE businesses SET hours = 'Mon-Fri 07:00-17:00, Sat 08:00-15:00, Sun Closed' WHERE slug = 'coffee-on-18th-rietondale' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- constantia-liquor-cellars-blue-bottle-liquors-constantia-park (hours)
UPDATE businesses SET hours = 'Mon-Sat 09:00-18:30' WHERE slug = 'constantia-liquor-cellars-blue-bottle-liquors-constantia-park' AND (hours IS NULL OR length(trim(hours)) < 3)
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
