-- owner-written:pretoria: 26 descriptions, generated by scripts/content-upgrade/owner-sql.mjs
-- beautiful-escape-health-and-beauty-rooihuiskraal-north (owner)
UPDATE businesses SET description = 'Beautiful Escape Health and Beauty is a beauty and aesthetic clinic at X36, InsideOut Campus in the Rockfields Precinct, on the corner of Tshiomate Street and Lenchen Avenue in Rooihuiskraal, Centurion. The clinic offers facials, skincare treatments, dermaplaning and microdermabrasion alongside makeup services, operating from a boutique-style treatment space within the Rockfields development.

Clients book facial and skin-focused treatments individually or as part of a wider beauty routine, with makeup application also available for special occasions and events. The Rockfields Precinct location places the clinic within a mixed commercial campus in Centurion''s Rooihuiskraal area, convenient for appointments booked alongside other errands nearby in the same precinct.', description_enriched_at = datetime('now') WHERE slug = 'beautiful-escape-health-and-beauty-rooihuiskraal-north' AND description = 'Beautiful Escape Health and Beauty is a health, beauty and aesthetic clinic inside Rockfields Commercial Village in Rooihuiskraal North, offering facials, dermaplaning, microdermabrasion and makeup services in a boutique, luxury-style setting.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- carls-coffee-kilner-park (owner)
UPDATE businesses SET description = 'Carl''s Coffee is a coffee roastery and cafe at 295 Galway Avenue, Bronberrick, Centurion. The business has roasted, brewed and supplied coffee for roughly 20 years, sourcing green coffee beans from six different coffee-growing regions and roasting them on site, with regular quality testing throughout the process.

Alongside its roasting operation, the Centurion cafe serves coffee and breakfast for dine-in, takeout and delivery, giving customers a sit-down option as well as coffee to go. The combination of in-house roasting and a working cafe counter means customers can taste beans in the very same location where they are sourced, tested and roasted, rather than buying beans that were roasted somewhere else entirely.', description_enriched_at = datetime('now') WHERE slug = 'carls-coffee-kilner-park' AND description = 'Carls Coffee is a coffee shop and roastery in Kilner Park, Pretoria, known for freshly roasted coffee and small meals including pies, with indoor and outdoor seating for dine-in or takeout.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- code-masters-it-support-pretoria-blue-valley-golf-estate (owner)
UPDATE businesses SET description = 'Code Masters is an IT support and software development company based at 257 Jean Avenue, Building 5, Central Office Park, Centurion, serving clients across Centurion, Pretoria, Johannesburg and wider South Africa. Its services include custom software development, managed IT support, data recovery, website development, cybersecurity and cloud hosting, alongside AI-driven solutions.

For Pretoria clients specifically, Code Masters provides proactive system monitoring, helpdesk and onsite support, cybersecurity protection, data backups and disaster-recovery planning. The combination of development and support services lets the company handle both the custom software a business runs on and the day-to-day IT infrastructure that keeps that business running.', description_enriched_at = datetime('now') WHERE slug = 'code-masters-it-support-pretoria-blue-valley-golf-estate' AND description = 'Code Masters provides outsourced IT support and managed IT services - including cybersecurity, helpdesk support and cloud solutions - across Pretoria, Centurion and Johannesburg, with over 25 years in the industry.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- boomslope-south-africa-pty-ltd-zwartkop (owner)
UPDATE businesses SET description = 'Boomslope South Africa is a tree-services business operating across Pretoria and Johannesburg, offering tree pruning, tree cutting and tree removal alongside hedge trimming and general garden services. The company also handles load dressing, refuse removal and furniture removal for clients who need site clearance done at the same time as tree work.

Boomslope has more than ten years of tree-felling experience, operates on a 24-hour availability basis and carries full insurance cover for its crews and equipment on every job. Quotations are arranged directly with customers across its Gauteng service area, covering both Pretoria and Johannesburg, rather than from a single public-facing branch.', description_enriched_at = datetime('now') WHERE slug = 'boomslope-south-africa-pty-ltd-zwartkop' AND description = 'Boomslope South Africa is a fully insured tree service company based in Centurion, offering tree felling, tree and stump removal, pruning, palm work, hedge trimming, and garden site clearance across Gauteng.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- colbyn-guest-lodge-colbyn (owner)
UPDATE businesses SET description = 'Colbyn Guest Lodge is a self-catering guest lodge at 107 Amos Street, Colbyn, Pretoria, made up of three separate double-storey buildings with 14 rooms in total, including 12 private self-catering en-suite units alongside other suite types. The main guest house building dates back to 1941, while the current buildings, decor and landscaping were established from 1996, and the family running the lodge has hosted guests since 1998.

Facilities include Wi-Fi, secure parking, breakfast and meals on request, shuttle services, touring assistance and a small conference facility for meetings or functions. The lodge has been rated Safe by the United Nations and has been selected to host diplomatic guests.', description_enriched_at = datetime('now') WHERE slug = 'colbyn-guest-lodge-colbyn' AND description = 'Colbyn Guest Lodge is a self-catering guest lodge in Colbyn, Pretoria, with 12 private en-suite units ranging from studio rooms to larger family suites, and facilities for conferencing and small functions.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- andr-du-preez-architects-murrayfield (owner)
UPDATE businesses SET description = 'Andre du Preez Architects is listed as an architecture firm, with its address given as 156 Ezra Road, in the Murrayfield suburb of Pretoria, postal code 0184. Within Pretoria''s business directories, the practice is categorised specifically as an Architecture Firm rather than under a broader engineering, surveying or construction heading, placing it among the city''s dedicated architectural practices by classification rather than by any other professional grouping.

The firm''s listed address sits within Murrayfield, an established suburb east of Pretoria''s city centre, and Andre du Preez Architects operates from that Ezra Road address as its place of business, with no second branch or additional location recorded for the practice.', description_enriched_at = datetime('now') WHERE slug = 'andr-du-preez-architects-murrayfield' AND description = 'André du Preez Architects is a Murrayfield, Pretoria architecture firm established in 1980 (originally as Du Preez and Snyders), specialising in lifestyle homes, townhouses, offices and redesigns of non-viable commercial buildings.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- apple-tree-fresh-food-market-elarduspark-elardus-park (owner)
UPDATE businesses SET description = 'Apple Tree Fresh Food Market trades from The Park Shopping Centre in Elardus Park, Pretoria. As a fresh-food retailer, it stocks fresh fruit and vegetables alongside a hot deli counter, bakery products, imported food items, dry goods and household essentials, covering most of a household''s everyday grocery needs under one roof.

The Park Shopping Centre location gives the store a fixed, centre-based presence rather than a free-standing street address, with shoppers accessing it as part of a wider visit to the centre. The combination of fresh produce, deli and bakery sections alongside general grocery and household lines makes it a convenient stop for nearby Elardus Park residents doing a full weekly shop.', description_enriched_at = datetime('now') WHERE slug = 'apple-tree-fresh-food-market-elarduspark-elardus-park' AND description = 'Apple Tree Fresh Food Market is a fresh produce store at The Park Shopping Centre in Elardus Park, Pretoria, stocking fruit and vegetables alongside dairy, cold meats, pasta and canned goods.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- asglo-logistics-bergtuin (owner)
UPDATE businesses SET description = 'Asglo Logistics is a specialised logistics and installation company founded in 2008, based at 325 Zasm Street, Waltloo, Pretoria. Its specialised work centres on mobile ATM trailers, vaults and safes, including the rigging of drop-down units, installation of vault and fire doors, and turnkey construction of ATM cubicles for its customers.

Beyond ATM-related work, Asglo handles long-haul transportation, demountable vault installation, waste removal and other construction-related installations for its clients. The company operates branches in Johannesburg, Pretoria, Cape Town, Durban, Bloemfontein and Polokwane, and delivers across Southern Africa, including cross-border deliveries within the SADC region, out of its Waltloo head office base.', description_enriched_at = datetime('now') WHERE slug = 'asglo-logistics-bergtuin' AND description = 'ASGLO Logistics is a specialised logistics and rigging company headquartered in Waltloo, transporting mobile ATM trailers, vaults and safes and installing vault and fire doors, with seven branches across South Africa.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- assured-real-estate-consulting-irene-farm-villages (owner)
UPDATE businesses SET description = 'Assured Real Estate Consulting is an independent property valuation and asset-enhancement consultancy at 13 Via Latina Crescent, Irene, Hub-X Office Block, Pretoria 0157, established in 2015. The firm provides property advisory services to developers, financiers, property managers and owners, working across three divisions: Advisory, Research and Development, and Commercial Management.

Its team of experienced valuers, researchers and project managers holds registrations with SACPVP, RICS and SACPCMP, supporting services that include immovable and movable property valuations, feasibility studies, due diligence, business valuations, market research and market indexing, financial modelling, and both commercial and project management work carried out for its clients.', description_enriched_at = datetime('now') WHERE slug = 'assured-real-estate-consulting-irene-farm-villages' AND description = 'Assured Real Estate Consulting is an independent property valuation and asset-enhancement advisory firm based in Irene Farm Villages, Centurion, having worked on projects spanning airports, ports, rural development and urban regeneration.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- boutel-projects-rietvalleirand (owner)
UPDATE businesses SET description = 'Boutel Projects (Pty) Ltd is a construction and infrastructure-development company established in 2013, with its Pretoria office at 217 Jochem Street, Rietvalleirand. The company is 51% majority black-owned and focuses on property development and construction management for both public- and private-sector clients across the commercial, residential and industrial sectors.

Boutel has undertaken projects worth up to R300 million per year, with quality, safety, time and cost management named as central focuses of how it delivers each project. Its completed and ongoing work includes hotels, shopping centres, apartment blocks and houses, reflecting a portfolio that spans the hospitality, retail and residential construction sectors.', description_enriched_at = datetime('now') WHERE slug = 'boutel-projects-rietvalleirand' AND description = 'Boutel Projects is a construction company founded in 2013, based in Rietvalleirand, Pretoria, specialising in commercial and medium-sized industrial construction, with a portfolio including hotels, shopping centres, apartments and residential developments.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- bp-eldo-glen-eldo-lakes-estate (owner)
UPDATE businesses SET description = 'BP Eldo Glen is a 24-hour fuel station on the corner of Willem Botha Street and Wierda Road in Eldo Glen, Centurion, offering fuel and diesel together with an on-site car wash and convenience shop. The station serves as a round-the-clock stop for motorists in the Eldo Glen and Eldoraigne area.

Alongside the fuel and convenience offering, the site includes a Wild Bean Cafe for coffee and food, and a Pick n Pay Express component for grocery and convenience shopping, letting customers combine refuelling with a food or grocery stop in a single visit without needing to drive elsewhere for either one.', description_enriched_at = datetime('now') WHERE slug = 'bp-eldo-glen-eldo-lakes-estate' AND description = 'BP Eldo Glen is a 24-hour fuel station on the corner of Willem Botha Street and Wierda Road in Eldo Glen, Centurion, with a convenience store and car wash on site.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- bradlows-wonderpark-karenpark (owner)
UPDATE businesses SET description = 'Bradlows Wonderpark is a furniture and home-decor store at Shop 502A in Wonderpark Shopping Centre, Karenpark, located at the centre''s Food Court entrance. Bradlows is a long-established South African furniture retailer, and this branch stocks ranges for the bedroom, kitchen, dining room, living room and bathroom, alongside storage and lighting products for other parts of the home.

The Food Court entrance location makes the store easy to find for shoppers already visiting Wonderpark Shopping Centre, and its combined furniture and decor ranges let customers furnish multiple rooms of a home from a single branch visit rather than travelling between separate specialist stores.', description_enriched_at = datetime('now') WHERE slug = 'bradlows-wonderpark-karenpark' AND description = 'Bradlows Wonderpark is a JD Group furniture and appliance store at Wonderpark Shopping Centre in Karenpark, Akasia, offering bedroom, kitchen, dining, living room, and appliance ranges with delivery and in-store shopping.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- brittech-pty-ltd-kosmosdal (owner)
UPDATE businesses SET description = 'Brittech (Pty) Ltd is a specialist industrial company based at Unit 3, Midway Industrial Park, corner of Samrand Avenue and Coqui Francolin Street, Kosmosdal, trading Monday to Friday from 07:30 to 16:00. The company focuses on linear screens and horizontal belt filters, equipment used in mineral processing and similar industrial applications.

Brittech has built its position as a leader in on-site service for this equipment, specialising in solving the technical and operational problems that arise with horizontal belt filters and linear screens in the field. The company highlights its safety record and compliance with customer safety standards as part of how it carries out that on-site work.', description_enriched_at = datetime('now') WHERE slug = 'brittech-pty-ltd-kosmosdal' AND description = 'Brittech (Pty) Ltd is a Centurion-based industrial engineering company specializing in horizontal belt filters, linear screens, and tracking systems used in mineral processing, along with on-site technical servicing of this equipment.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- catersales-pty-ltd-hermanstad (owner)
UPDATE businesses SET description = 'Catersales (Pty) Ltd is a catering business based at 463 Taljaard Street, Hermanstad, Pretoria, providing customisable menus for weddings, corporate events and private parties. Clients can tailor the menu to the type of event they are hosting, rather than choosing from a single fixed catering package.

The business accepts payment by NFC, credit card and debit card, and has attracted recent customer reviews reflecting ongoing trading activity at the Hermanstad address. Catersales operates as a catering-for-events company rather than as a supplier of catering equipment, groceries or packaging, with its core business built around planning and delivering menus for scheduled functions.', description_enriched_at = datetime('now') WHERE slug = 'catersales-pty-ltd-hermanstad' AND description = 'Catersales (Pty) Ltd is a Hermanstad-based supplier of catering equipment, groceries, packaging, and cleaning products for the catering trade, and also offers customizable catering menus for weddings, corporate events, and parties.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- checkers-hyper-centurion (owner)
UPDATE businesses SET description = 'Checkers Hyper Centurion is a Checkers Hyper-format supermarket at Shop 4A, Centurion Mall, Gordon Hood Road, Centurion, built around a large, spacious store layout with extended weekday and weekend trading hours. The store carries an extensive range of stock, including ready-made food, bakery products, pies and cookies.

Alongside the main supermarket floor, the branch includes a separate Checkers LiquorShop and a MediRite pharmacy component, and a substantial toy section gives the store a wider range than a standard-format supermarket typically carries. The combination of grocery, liquor, pharmacy and toy sections under one roof reflects the larger Hyper-format footprint of this particular branch.', description_enriched_at = datetime('now') WHERE slug = 'checkers-hyper-centurion' AND description = 'Checkers Hyper (also known as Checkers Hyper FX Centurion) is a large-format supermarket at Centurion Mall on Gordon Hood Avenue, selling groceries, clothing and a TechX electronics department, with Sixty60 delivery.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- clicks-gezina-galleries-gezina (owner)
UPDATE businesses SET description = 'Clicks Gezina Galleries is a Clicks retail branch at Shop 26, Gezina Galleries, Michael Brink Street, Gezina, Pretoria, trading on weekdays, Saturdays and Sundays. As part of the national Clicks chain, the branch offers pharmacy, healthcare and beauty products alongside homeware and gift lines.

The store includes an in-store pharmacy for prescription and over-the-counter medicines, consistent with the Clicks chain''s standard store format found at its branches nationally across South Africa. Its position inside Gezina Galleries gives shoppers pharmacy and beauty access as part of a wider visit to the shopping centre, with trading hours extending across the full week, including Sundays.', description_enriched_at = datetime('now') WHERE slug = 'clicks-gezina-galleries-gezina' AND description = 'Clicks Gezina Galleries is a health and beauty retailer inside Gezina Galleries, offering pharmacy, healthcare and beauty products alongside homeware and gifts, with an in-store pharmacy for prescription and over-the-counter medicines.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- cartrack-pretoria-bryntirion (owner)
UPDATE businesses SET description = 'Cartrack''s Pretoria branch operates from Shop 8, Menlyn Motor City, Garsfontein Road, Newlands, Pretoria, and is listed on Cartrack''s own website among its Gauteng service centres. Cartrack is a vehicle-tracking and fleet-management company, and this branch handles tracking-device installation and vehicle-security services for customers in the surrounding area.

Being based at Menlyn Motor City places the branch within an established motor-trade precinct on Garsfontein Road, alongside other vehicle-related businesses, making it a practical stop for fitting or servicing a tracking unit. The branch forms part of Cartrack''s wider national network of service centres rather than operating as a standalone outlet.', description_enriched_at = datetime('now') WHERE slug = 'cartrack-pretoria-bryntirion' AND description = 'Cartrack is a global vehicle tracking and fleet management company offering GPS tracking, stolen vehicle recovery, telematics and fleet management software; this branch operates from Menlyn Motor City on Garsfontein Road.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- consult-erasmusrand-erasmusrand (owner)
UPDATE businesses SET description = 'Consult Erasmusrand operates as part of the Consult by Momentum franchise network, with financial adviser Dereck Antunes serving as the practice''s Franchise Principal and Adviser. The practice provides financial advisory services spanning life insurance, health insurance, wealth management, retirement planning, wills planning, financial planning and small-business insurance cover, drawing on Momentum''s broader financial services backing and administration.

Antunes and the practice serve clients across the Pretoria Metropolitan area, offering a single point of contact for insurance and long-term financial planning needs. The Erasmusrand-branded practice suits individuals, families and small business owners looking to consolidate their insurance and investment planning with one adviser.', description_enriched_at = datetime('now') WHERE slug = 'consult-erasmusrand-erasmusrand' AND description = 'Financial adviser Dereck Jaun Antunes practices as Consult Erasmusrand under Momentum Consult (Pty) Ltd, an authorised financial services provider (FSP5503), offering financial planning, investment, insurance, and fiduciary services in Erasmusrand, Pretoria.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- crazy-plastics-centurion-celtisdal (owner)
UPDATE businesses SET description = 'Crazy Plastics Centurion trades from Shop 7 and 8 at Raslouw Lifestyle Centre on Hendrik Verwoerd Drive in Centurion, confirmed as a current tenant of the centre and listed on the Crazy Plastics chain''s own store directory. The store forms part of the wider Crazy Plastics retail chain, selling household, kitchen, storage and garden plastic products at discount prices to shoppers in the area.

The Centurion branch is open Monday to Friday from 8:30am to 6pm, Saturdays from 8:30am to 4:30pm, and Sundays from 9am to 3pm, giving weekday and weekend shoppers in Celtisdal and the wider Centurion area easy access to its homeware and plastics range.', description_enriched_at = datetime('now') WHERE slug = 'crazy-plastics-centurion-celtisdal' AND description = 'Crazy Plastics Centurion is a discount homeware and plastics store at Raslouw Lifestyle Centre in Celtisdal, Centurion, part of the Crazy Plastics chain selling household, kitchen, storage and garden plastic products.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- dante-personnel-recruitment-tijger-valley (owner)
UPDATE businesses SET description = 'Dante Personnel Recruitment is a South African recruitment company founded in 1996 and headquartered in Pretoria, with its office at Building 76, Tijger Valley Office Park on Silverlakes Road in Silverlakes. The company''s core specialties include permanent placements, temporary placements and disability placements, and it also provides contract placements, response-management, project-recruitment and vendor-on-site recruitment services for client businesses across a range of sectors.

Operating both nationally and internationally, the Pretoria office has built up recruitment experience since 1996, matching candidates with employers through a mix of permanent, temporary and contract placement models. Its vendor-on-site and project-recruitment offerings serve businesses in and around Tijger Valley and Silverlakes that need placement support beyond standard permanent hiring.', description_enriched_at = datetime('now') WHERE slug = 'dante-personnel-recruitment-tijger-valley' AND description = 'Dante Personnel Recruitment is a national recruitment consultancy operating from Tijger Valley Office Park, specialising in permanent, temporary and disability placements across sectors such as mining, engineering, technical, IT and finance.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- debonairs-pizza-gezina-gezina (owner)
UPDATE businesses SET description = 'Debonairs Pizza Gezina trades from Shop 41 inside Gezina Galleries, a branch confirmed on the Debonairs franchise''s official branch locator as a current, active store. The branch offers in-store collection and delivery, and it serves the full Debonairs pizza range, including the Triple-Decker line and the budget-friendly Real Deal range, alongside catering orders prepared for larger groups and gatherings.

Set up as a family-friendly restaurant and takeaway rather than a delivery-only outlet, the Gezina branch supports online ordering for home delivery as well as walk-in customers collecting their order in person. It serves the Gezina community and surrounding areas from its location inside Gezina Galleries on the corner of Michael Brink and Frederika Streets.', description_enriched_at = datetime('now') WHERE slug = 'debonairs-pizza-gezina-gezina' AND description = 'Debonairs Pizza Gezina is a pizza takeaway and delivery outlet inside Gezina Galleries, known for its Triple-Decker pizzas and the budget-friendly Real Deal range, available for dine-in, takeaway or online delivery.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- debonairs-pizza-philip-nel-park (owner)
UPDATE businesses SET description = 'Debonairs Pizza Philip Nel Park trades from the corner of Trans Oranje and Morkel East Streets, confirmed as a current, active branch on the Debonairs franchise''s official location page rather than only a Facebook listing. The branch offers in-store collection, delivery and online ordering, with cashless and contactless payment accepted at the till for customers who prefer not to pay with cash.

Its menu highlights the budget-friendly Real Deal pizza range alongside PizzaWraps and a dedicated chicken-pizza selection, in addition to the franchise''s standard sides and extras. The branch serves takeaway, in-store collection and delivery customers throughout Philip Nel Park and the surrounding Pretoria area each week.', description_enriched_at = datetime('now') WHERE slug = 'debonairs-pizza-philip-nel-park' AND description = 'Debonairs Pizza Philip Nel Park is a branch of the South African pizza franchise founded in 1991, known for its Triple-Decker pizza and sides available for delivery, takeaway or in-store ordering.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- deltaerp-wapadrand (owner)
UPDATE businesses SET description = 'DeltaERP is a business-management software product provided by DataSaint, a company that has operated since 1985. Over four decades DataSaint grew from a small business supplying turnkey solutions into a supplier of configurable business solutions, and the DeltaERP product line carries that history forward through modules built to support day-to-day business processes and information management.

DataSaint''s offices are based at Wapadrand Office Park, Block A, on Kingbolt Crescent in Wapadrand, Pretoria, and the company invites enquiries directly about specific DeltaERP modules or a product demonstration. The Wapadrand office serves businesses in Pretoria and beyond that are looking for a long-established, locally developed alternative to off-the-shelf business software.', description_enriched_at = datetime('now') WHERE slug = 'deltaerp-wapadrand' AND description = 'DeltaERP, provided by DataSaint (Pty) Ltd under the Matrix Design Africa umbrella, is a cost-effective, intelligent ERP solution designed for capital-intensive industries, integrating modules to support business processes and information management.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- dlamini-n-attorneys-brooklands-lifestyle-estate (owner)
UPDATE businesses SET description = 'Dlamini N Attorneys is an active Centurion law firm founded by attorney Nolizwi Dlamini, practising from 75 Bothrill Avenue in Centurion. The firm''s practice areas cover divorce and family law, deceased estates and wills, criminal litigation and defence, civil litigation, contract law and commercial law, with the firm describing its approach as personalised legal support and representation for each client.

Clients can reach the practice by telephone or WhatsApp, and the firm is open Monday to Friday from 9am to 5pm. Based in Centurion, Dlamini N Attorneys serves individuals and businesses across the wider Pretoria area needing assistance with family, criminal, civil or commercial legal matters.', description_enriched_at = datetime('now') WHERE slug = 'dlamini-n-attorneys-brooklands-lifestyle-estate' AND description = 'Dlamini N Attorneys is a Centurion-based law firm practising in divorce and family law, deceased estates and wills, criminal litigation, civil litigation and contract law, offering in-person, phone and video consultations.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- effective-solar-trading-wonderboom (owner)
UPDATE businesses SET description = 'Effective Solar Trading is a solar energy company based at 158 Waterhout Street in Wonderboom, Pretoria, and it operates across South Africa rather than being limited to the local area. The business is classified within the solar installation industry as handling smaller solar installations, with battery storage forming part of its offering alongside the installation itself.

For its installations, Effective Solar Trading works with Znshine PV-Tech solar panels together with Deye and Sunsynk inverters, established brands within the South African solar and battery-storage market. Based in Wonderboom, the company serves customers looking for a smaller-scale solar and battery-backup setup rather than a large commercial or utility-scale system.', description_enriched_at = datetime('now') WHERE slug = 'effective-solar-trading-wonderboom' AND description = 'Effective Solar Trading is a solar energy company based in Wonderboom, Pretoria, providing residential and commercial solar solutions ranging from basic starter systems to full off-grid power systems, including battery backup.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- eskort-store-centurion-rooihuiskraal (owner)
UPDATE businesses SET description = 'Eskort Store Centurion is a butchery branch of the Eskort chain, confirmed by Eskort''s own official store locator to trade from 2 Old Johannesburg Road, Rooihuiskraal, Centurion, rather than the address previously listed. The store serves the local Centurion community with the full Eskort product range of fresh and smoked pork products, including bacon and sausage.

Beyond its retail trade, the store supports local organisations including Moeggesukkel and the Louis Botha Children''s Home, along with surrounding schools in the Rooihuiskraal area. The branch is open Monday to Friday from 9am to 5pm, Saturdays from 8am to 4pm, and Sundays from 9am to 1pm, serving Rooihuiskraal and the wider Centurion community throughout the week.', description_enriched_at = datetime('now') WHERE slug = 'eskort-store-centurion-rooihuiskraal' AND description = 'Eskort Store Centurion is a branch of the Eskort butchery chain, stocking fresh and smoked pork products including bacon and sausage, with online orders available for delivery via Mr D Food.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
