-- owner-written:pretoria: 2 descriptions, generated by scripts/content-upgrade/owner-sql.mjs
-- dezis-pets-hermanstad (owner)
UPDATE businesses SET description = 'Dezi''s Pets is a local pet-supplies shop at 653 Meyer Street, Wonderboom South, Pretoria, offering food, toys and grooming supplies for dogs, cats and birds. It serves local pet owners and families looking for everyday pet food, toys, grooming products and other pet-care essentials, rather than stocking supplies for only one type of animal. The shop supports in-store shopping with card and tap-to-pay payments, and the premises are wheelchair accessible. Dezi''s Pets has built up a sizeable base of local customer reviews and a generally positive reputation in the area. It suits Wonderboom South residents and nearby pet owners who want a friendly, local pet-supply shop for regular pet-care needs rather than travelling to a larger chain store.', description_enriched_at = datetime('now') WHERE slug = 'dezis-pets-hermanstad' AND description = 'Dezi''s Pets is a pet shop in Hermanstad, Pretoria, on Van Der Hoff Road.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- flight-centre-waterkloof (owner)
UPDATE businesses SET description = 'Flight Centre Brooklyn Mall is a travel agency at Shop 16, Brooklyn Mall, 338 Bronkhorst Street, Brooklyn, Pretoria, helping customers plan and book flights, holidays, tours and full travel packages. Its consultants work directly with customers to compare options, build itineraries and arrange travel, rather than simply selling airline tickets over the counter. The branch serves leisure travellers, families and tourists planning a holiday, as well as business travellers who need flights, accommodation or a full itinerary arranged. As part of Flight Centre''s national South African network, it gives customers access to the brand''s travel deals and expertise while being able to speak to a consultant in person at Brooklyn Mall. It suits anyone in the Brooklyn area who wants hands-on help planning a trip rather than booking everything online alone.', description_enriched_at = datetime('now') WHERE slug = 'flight-centre-waterkloof' AND description = 'Flight Centre is a travel agency operating from Shop 16 in Brooklyn Mall, Brooklyn.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
