-- owner-written:pretoria: 4 descriptions, generated by scripts/content-upgrade/owner-sql.mjs
-- sheraton-pretoria-pretoria-central (owner)
UPDATE businesses SET description = 'CT Hotel Pretoria is a five-star hotel in Arcadia, Pretoria, that previously traded as the Sheraton Pretoria Hotel before the property was rebranded under its current name. The hotel offers a choice of room types, together with an outdoor swimming pool, a gym, Wi-Fi throughout the building and on-site parking for guests.

The property remains in Arcadia and continues to operate at the same five-star standard it held under its previous name. Guests who knew the hotel as the Sheraton Pretoria Hotel will find it trading today as CT Hotel Pretoria, with its pool, gym, Wi-Fi and parking facilities still in place.', description_enriched_at = datetime('now') WHERE slug = 'sheraton-pretoria-pretoria-central' AND description = 'Sheraton Pretoria is a 175-room five-star hotel in Arcadia that opened in 1999, offering conference venues, an outdoor pool, gym, spa, and a restaurant and bar near the Union Buildings.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- solar4you-constantia-park (owner)
UPDATE businesses SET description = 'Solar4You is a solar installation company based in Constantia Park, Pretoria. Current solar-industry listings describe it as an installer of working solar power systems for residential and commercial properties, and a separate installer listing offers free quotations for both residential and commercial solar projects before any installation begins. Industry listings also credit the company with around 15 years of experience in the solar installation field.

The business operates from 505 Robert Craib Street in Constantia Park and is open Monday to Thursday from 8am to 5pm, and on Fridays until 2pm. It serves homeowners and businesses in the Constantia Park area looking to install a working solar power system on their property.', description_enriched_at = datetime('now') WHERE slug = 'solar4you-constantia-park' AND description = 'Solar4You has designed and installed residential and commercial solar power systems, including panels, inverters, batteries and solar geysers, since 2008, and holds a patent on its own solar geyser design.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- tech-tech-bryntirion (owner)
UPDATE businesses SET description = 'Tech-Tech is an IT support and managed-services provider based at 339 Hilda Street in Hatfield, Pretoria, an address confirmed by more than one current online business directory. The company offers remote assistance together with on-site technicians who attend to IT needs directly, providing IT solutions geared toward the everyday requirements of its business clients.

Directory listings put the business at a 5-star overall rating from 27 customer reviews, with 26 rated five stars and one rated four stars. Businesses in and around Hatfield needing IT support can draw on both the remote-assistance and on-site technician services the company offers from its Hatfield base.', description_enriched_at = datetime('now') WHERE slug = 'tech-tech-bryntirion' AND description = 'Tech-Tech is an IT consulting and support company serving Pretoria, offering managed IT services, cybersecurity, Microsoft 365 support and voice/data connectivity for businesses that want a single IT partner.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- tshwaneng-construction-sinoville (owner)
UPDATE businesses SET description = 'Tshwaneng Construction is a construction and maintenance company based at 174 Blyde Avenue in Sinoville, Pretoria, with a team of 11 to 50 employees serving both residential and business clients. Services include roof waterproofing, gutters and fascia boards, ceilings, painting, home restoration, built-in cupboards, paving, tiling, fencing, boundary walls, drywalling and general home repairs, as well as the construction of homes and offices.

An independent business directory lists the company as having served the Sinoville area since at least the 1980s, while its LinkedIn profile gives a 2006 founding date, so the exact history is best read as approximate. Either way, the company works across domestic, private, commercial and industrial markets from its Sinoville base.', description_enriched_at = datetime('now') WHERE slug = 'tshwaneng-construction-sinoville' AND description = 'Tshwaneng Construction is a building contractor in Sinoville that has provided professional construction services since 1985, specialising in house extensions, renovations and building work for domestic, commercial and industrial clients.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
