-- owner-written:pretoria: 12 descriptions, generated by scripts/content-upgrade/owner-sql.mjs
-- luxman-upholstery-eersterust (owner)
UPDATE businesses SET description = 'Luxman Upholstery is a furniture repair and restoration business operating from 428 John Sydney Drive in Eersterust, Pretoria. The workshop repairs and restores furniture to extend the life of existing pieces, offering headboard upholstery, dining-chair upholstery, lounge-suite upholstery and vehicle upholstery for cars, bakkies and other vehicles.

Simple repairs are typically completed within one to two days, while full reupholstery work and antique restoration projects take between one and three weeks depending on the piece. The business serves homes and businesses across Pretoria East, Centurion, Hatfield, Brooklyn, Arcadia, Sunnyside, Menlo Park and other surrounding suburbs, and gives customers an honest assessment when a piece is not worth repairing rather than taking on unnecessary work.', description_enriched_at = datetime('now') WHERE slug = 'luxman-upholstery-eersterust' AND description = 'Luxman Upholstery restores and reupholsters furniture and vehicle interiors, handling everything from antique furniture restoration to modern furnishings and auto upholstery, and serves customers across Pretoria East, Centurion and surrounding suburbs.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- lyttelton-engravers-lyttelton (owner)
UPDATE businesses SET description = 'Lyttelton Engravers is an engraving and trophy business trading from Shop 01, 162 Cradock Avenue in Lyttelton Manor, Centurion. The shop engraves a range of items and produces customised trophies and keepsakes, including pieces made to order for events and branding projects.

Customers can shop in-store, arrange collection or request delivery, making the business a practical option for anyone needing engraved items, trophies or personalised keepsakes. Listings for the shop differ slightly on the exact street number, and while one directory recorded it as closed at the time it was checked, a separate, more current listing still shows it operating, so its day-to-day trading status should be confirmed directly with the shop before visiting.', description_enriched_at = datetime('now') WHERE slug = 'lyttelton-engravers-lyttelton' AND description = 'Lyttelton Engravers has operated for more than 10 years, offering laser engraving and precision-crafted trophies, medals, plaques and corporate gifts, as well as custom name tags, Perspex displays and rubber stamps.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- lyttelton-fresh-produce-housewives-market-kloofsig (owner)
UPDATE businesses SET description = 'Lyttelton Fresh Produce Housewives Market is a fresh-produce retailer trading from Government Road at 102 Napier Road in Lyttelton Manor, Centurion. The market focuses on fresh fruit and vegetables alongside daily household essentials and deli products, with an emphasis on quality produce at competitive prices.

Local household shoppers can buy everyday fresh food in person, and delivery is available for customers placing orders from off-site. The market is open Monday to Friday from 7:30am to 6pm, Saturdays from 7:30am to 6:30pm and Sundays from 7:30am to 2pm, giving Lyttelton Manor residents a consistent neighbourhood option for fresh grocery shopping throughout the week.', description_enriched_at = datetime('now') WHERE slug = 'lyttelton-fresh-produce-housewives-market-kloofsig' AND description = 'Lyttelton Fresh Produce Housewives Market has been trading fresh fruit and vegetables in Lyttelton Manor since 1965, also stocking daily essentials and deli items with delivery available seven days a week.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- machidi-events-lotus-gardens (owner)
UPDATE businesses SET description = 'Machidi Events is an event-management business based at 894 Abelmosk Avenue in Lotus Gardens, Pretoria. The business plans weddings, birthdays and other celebrations, offering bespoke decor, tailored catering and full event coordination, including themed and traditional ceremonies.

It works with individuals and groups organising weddings, birthday celebrations, themed parties and traditional events who need decor, catering and coordination handled together. At the time of review, Machidi Events held 12 reviews and a 5.0 rating, though it does not currently have an official website, so customers are best served contacting the business directly to discuss packages for an upcoming celebration.', description_enriched_at = datetime('now') WHERE slug = 'machidi-events-lotus-gardens' AND description = 'Machidi Events plans and decorates weddings, birthday celebrations and other special occasions from Lotus Gardens, offering event decor and catering with close attention to detail for both themed and traditional functions.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- magnum-safes-koedoespoort (owner)
UPDATE businesses SET description = 'Magnum Safes manufactures and supplies security and custom safes from its premises at 17 Steenbok Street in Koedoespoort Industrial, Pretoria. Its product range includes security safes, strongroom doors and cladded strongroom doors, raised-discharge boxes, counter and wall discharge boxes, and custom safes, including models built specifically for rifle storage.

The business serves both security-industry customers and private individuals needing secure storage, from standalone safes to full strongroom installations. Its own website confirms the strongroom-door range as part of its current product line, making Magnum Safes a relevant supplier for households, businesses and security contractors in the Koedoespoort area looking for locally manufactured security and safe-storage equipment.', description_enriched_at = datetime('now') WHERE slug = 'magnum-safes-koedoespoort' AND description = 'Magnum Safes is a safe manufacturer in Koedoespoort Industrial, founded in 1988, that builds standard and custom safes, including rifle safes and strongroom doors, manufactured to comply with South African legislation.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- mandco-granite-tombstones-factory-hesteapark (owner)
UPDATE businesses SET description = 'M and Co Granite Tombstones manufactures and sells granite tombstones from 22 Diamant Street in Klerksoord AH, Akasia. The business maintains a current product catalogue listing multiple tombstone models and prices under the Mandco Granite Tombstones name, rather than relying only on a directory listing, and provides contact details directly on that catalogue for enquiries.

It serves individuals and families purchasing memorial and cemetery tombstones, offering a choice of granite designs to suit different budgets and preferences. Customers can reach the business directly to discuss model options, pricing and cemetery requirements before placing an order, making it a practical local source for memorial stonework for families in Akasia and the wider Pretoria area.', description_enriched_at = datetime('now') WHERE slug = 'mandco-granite-tombstones-factory-hesteapark' AND description = 'MandCO Granite Tombstones, founded in 2019 as one of the youngest black female-owned brands in the granite industry, manufactures and supplies tombstones in-house at its Pretoria factory using locally sourced granite.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- mashudu-and-co-pty-ltd-thatchfield-estate (owner)
UPDATE businesses SET description = 'Mashudu and Co (Pty) Ltd is a 100% black-owned software-development company and IT outsourcing provider, based at 471B Bushwillow Avenue in Thatchfield Glen, Centurion. The business is a Level 1 B-BBEE contributor and a certified Microsoft Silver Partner, with Microsoft technologies identified as a specific area of expertise.

It develops software products and services aimed at helping organisations improve their business capabilities, and provides IT outsourcing support alongside its development work. Mashudu and Co serves organisations across sectors that need software-development or IT-outsourcing solutions, and its Mustek business profile records the company as established in 2017, giving it close to a decade of operating history in the Centurion area.', description_enriched_at = datetime('now') WHERE slug = 'mashudu-and-co-pty-ltd-thatchfield-estate' AND description = 'Mashudu and Co (Pty) Ltd is a 100% black-owned software development and IT outsourcing company established in 2017, holding Level 1 B-BBEE contributor status and certification as a Microsoft Silver Partner.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- matzbo-advisory-services-leeuwfontein (owner)
UPDATE businesses SET description = 'Matzbo Advisory Services is a financial-services and business-accounting company operating from Plot 120, Leeuwfontein Estate in Roodeplaat, Pretoria. It is an authorised financial-services provider registered with SAIBA and works with CIPC on business registrations, offering financial advice, bookkeeping, financial statements and annual returns.

The company also handles SARS compliance, UIF and tax matters for its clients, serving business clients and organisations that need accounting, compliance, financial-advisory or business-registration support in one place. According to its LinkedIn profile, Matzbo Advisory Services is privately held, founded in 2019 and employs between two and ten people, operating as a small, Pretoria-headquartered advisory practice from its Roodeplaat base.', description_enriched_at = datetime('now') WHERE slug = 'matzbo-advisory-services-leeuwfontein' AND description = 'Matzbo Advisory Services, headquartered in Leeuwfontein Estate, Roodeplaat, is a licensed financial services provider offering business registrations, bookkeeping, financial advice and SARS and UIF compliance support for startups and established businesses.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- meniko-records-management-services-kloofsig (owner)
UPDATE businesses SET description = 'Meniko Records Management Services is an IT and information-governance company based at Fountain Square, 78 Kalkoen Street in Monument Park, Pretoria. Established in 2004, it is a Level 1 B-BBEE IT company specialising in data governance, records management and enterprise data management for organisations that need to control and protect their information.

Its services include business-process automation, electronic document and records management, POPIA and privacy compliance, structured data management, analytics and image processing and digitisation, and it holds Level 400 OpenText partner certification in the SADC region. In 2025, Meniko was awarded a SANParks tender for the digitisation and scanning of records over three years, independent evidence that the company remains actively trading and winning institutional work.', description_enriched_at = datetime('now') WHERE slug = 'meniko-records-management-services-kloofsig' AND description = 'Meniko Records Management Services has specialised in data governance and records management since 2004, offering tailored solutions for document and electronic records management, image processing, scanning and data life cycle management.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- muthray-associates-inc-valhalla (owner)
UPDATE businesses SET description = 'Muthray & Associates Inc. is a professional legal firm headquartered at 7 Vindhella Road in Valhalla, Centurion. Founded in 2006, the firm has built up more than 20 years of experience and is fully B-BBEE compliant, offering legal solutions across a broad range of matters with an emphasis on client relationships and practical, ongoing support.

Its LinkedIn profile specifically identifies criminal law, family law, legal representation and divorce as areas of speciality, serving individuals and other clients who need representation or legal advice. From its Valhalla base, Muthray & Associates is positioned to assist clients across Centurion and the wider Pretoria area with both court representation and day-to-day legal guidance.', description_enriched_at = datetime('now') WHERE slug = 'muthray-associates-inc-valhalla' AND description = 'Muthray & Associates Inc. is an attorneys'' firm in Valhalla, Centurion, with over 20 years'' experience across all aspects of the law, providing legal solutions with prompt, clear communication to clients.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- netbrake-dynamic-brake-testing-equipment-donkerhoek (owner)
UPDATE businesses SET description = 'NetBrake Dynamic Brake Testing Equipment develops dynamic brake-testing equipment for the mining, transport, workshop and rail sectors, operating from 79 Touleier Street in Donkerhoek, Gauteng. Its current range includes portable brake testers, vehicle brake-testing equipment and a dedicated model built for rail and locomotive applications, supporting brake testing, vehicle diagnostics, telemetry and test-report generation.

The company serves mining operations, heavy-industry and transport fleets, workshops and rail operators that need brake-testing and compliance equipment, with more than 400 units deployed since 2017 and equipment aligned to the ISO 3450 standard. Beyond equipment supply, NetBrake offers certified training, calibration and 24/7 technical support, backing its products with ongoing service for operators across the industries it supplies.', description_enriched_at = datetime('now') WHERE slug = 'netbrake-dynamic-brake-testing-equipment-donkerhoek' AND description = 'A manufacturer and supplier of dynamic brake testing equipment for the mining and industrial safety sector, based in Kleinfontein, Donkerhoek, with more than 200 units sold across Southern Africa since 2017.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- one-g-services-pty-ltd-shere (owner)
UPDATE businesses SET description = 'One G Services (Pty) Ltd is a property consulting and development management services company with an office at Lombardy Business Park, Block 4, Unit 55 and 56, Graham Road in Pretoria. The business guides housing and property-development projects from concept through to completion, and also provides ongoing property and asset-management services once a project is complete.

It serves property-development and property-management clients who need assistance running a development project as well as businesses needing continuous asset care for completed properties. One G Services'' contact page has remained online for several years, and current local business information confirms the company is still represented at its Graham Road office in Pretoria.', description_enriched_at = datetime('now') WHERE slug = 'one-g-services-pty-ltd-shere' AND description = 'One G Services is a specialist property and infrastructure development consultancy established in 2010, based at Lombardy Business Park, with a team covering project management, financial management, engineering and town planning.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
