-- Round-5 batch (efficiency-focused re-run, strict 2-independent-source
-- verification with branch-specific matching). Every entry verified
-- against 2+ independent, branch-appropriate sources with mandatory
-- phone+address. Covers Savannah Mall, Game Centre, Checkers Centre and
-- Mall of the North tenant sweeps.

-- Savannah Mall (fauna-park) tenants

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('american-swiss-savannah-mall-fauna-park', 'American Swiss', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop 24, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '015 296 0837', NULL, NULL, 'American Swiss is a jewellery retailer selling rings, watches and accessories, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shops/", "https://www.tiendeo.co.za/stores/polokwane/american-swiss-savannah-mall-cnr-grimm-thabo-mbeki-street/75940"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'american-swiss-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'jewellers'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('cash-crusaders-savannah-mall-fauna-park', 'Cash Crusaders', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop G10-G11, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '015 023 1049', NULL, NULL, 'Cash Crusaders is a second-hand goods and pawnbroking retailer buying and selling electronics, tools and other merchandise, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shops/", "https://cashcrusaders.co.za/locate-a-store/store/308/Cash%20Crusaders%20Savannah%20Mall"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'cash-crusaders-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('capitec-bank-savannah-mall-fauna-park', 'Capitec Bank', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop G35, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '0860 102 043', NULL, NULL, 'Capitec Bank is a retail bank branch offering everyday banking, savings and lending services, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shops/", "https://www.cylex.net.za/company/capitec-bank-polokwane-savannah-mall-23614270.html"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'capitec-bank-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'banks-atms'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('fnb-bank-savannah-mall-fauna-park', 'FNB Bank', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop G34, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '015 296 9800', NULL, NULL, 'FNB (First National Bank) is a retail bank branch offering everyday banking services and an ATM, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shops/", "https://www.cylex.net.za/company/fnb-savannah-23842229.html"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'fnb-bank-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'banks-atms'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('markham-savannah-mall-fauna-park', 'Markham', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop 43-44, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '015 296 4508', NULL, NULL, 'Markham is a men''s fashion retailer selling clothing, footwear and accessories, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shops/", "https://www.tiendeo.co.za/stores/polokwane/markham-savannah-mall-cnr-grimm-thabo-mbeki-street/72776"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'markham-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('miladys-savannah-mall-fauna-park', 'Milady''s', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop 35-36, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '015 296 0000', NULL, NULL, 'Milady''s is a women''s fashion retailer selling clothing and accessories, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shops/", "https://www.yep.co.za/biz/store/miladys-savannah-mall/296829"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'miladys-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('mtn-savannah-mall-fauna-park', 'MTN', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop 64, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '083 869 6931', NULL, NULL, 'MTN is a mobile network operator store selling cellphone contracts, devices and accessories, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shops/", "https://www.mtn.co.za/home/coverage/store/mtn-store-savanna-mall"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'mtn-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'mobile-phones'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('pep-savannah-mall-fauna-park', 'PEP', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop 79, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '0860 900 100', NULL, NULL, 'PEP is a value clothing and homeware retailer, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shop/79/", "https://www.facebook.com/PEPPolokwaneSavannahMall/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'pep-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('pep-home-savannah-mall-fauna-park', 'PEP Home', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop 38, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '0860 900 100', NULL, NULL, 'PEP Home is a value homeware retailer selling household goods and linen, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shops/", "https://www.tiendeo.co.za/stores/polokwane/pep-home-shop-savannah-mall-corner-thabo-mbeki-grimm-street/71325"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'pep-home-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('pick-n-pay-liquor-savannah-mall-fauna-park', 'Pick ''n Pay Liquor', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop 1, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '015 296 1278', NULL, NULL, 'Pick n Pay Liquor is a liquor store selling wine, beer and spirits, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shop/pick-n-pay-liquor/", "https://www.shopshours.co.za/pick-n-pay-liquor/polokwane/c-57f3ca1147d677c3b27af499"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'pick-n-pay-liquor-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'liquor-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('pna-savannah-mall-fauna-park', 'PNA', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop 46, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '015 296 4090', NULL, NULL, 'PNA is a stationery, books, and arts & crafts retailer, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shops/", "https://www.yep.co.za/biz/store/pna-savannah/322277"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'pna-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'books-stationery'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('rage-savannah-mall-fauna-park', 'Rage', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop 27, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '015 296 0210', NULL, NULL, 'Rage is a footwear and fashion retailer specialising in women''s shoes and clothing, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shop/27/", "https://polokwane.infoisinfo.co.za/card/rage/306937"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'rage-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sleepmasters-savannah-mall-fauna-park', 'Sleepmasters', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop G20, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '010 133 1176', NULL, NULL, 'Sleepmasters is a bedding retailer selling beds, mattresses and bedroom furniture, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shop/g20/", "https://www.tiendeo.co.za/stores/polokwane/sleepmasters-shop-g-savannah-mall-cnr-thabo-mbeki-and-grimm-street/75973"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'sleepmasters-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sport-scene-savannah-mall-fauna-park', 'Sport Scene', (SELECT id FROM suburbs WHERE slug = 'fauna-park'), (SELECT id FROM shopping_centers WHERE slug = 'savannah-mall-fauna-park'), 'Shop 25, Savannah Mall, Cnr Grobler St & Grid Rd, Fauna Park, Polokwane', '015 296 0970', NULL, NULL, 'Sport Scene is a sportswear and sneaker retailer selling footwear, apparel and accessories from brands including Nike and adidas, trading from Savannah Mall.', NULL, NULL, '["https://savannahmall.co.za/shop/25/", "https://www.yep.co.za/biz/store/iyp/10217814_2"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'sport-scene-savannah-mall-fauna-park'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

-- Game Centre (polokwane-central) tenants

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('the-crazy-store-game-centre-polokwane-central', 'The Crazy Store Game Centre', (SELECT id FROM suburbs WHERE slug = 'polokwane-central'), (SELECT id FROM shopping_centers WHERE slug = 'game-centre-polokwane-central'), 'Shop 002A, Game Centre, Market St, Polokwane, 0699', '087 135 8770', NULL, NULL, 'The Crazy Store is a discount variety retailer selling household, gardening, toy and gift items, trading from Game Centre.', NULL, NULL, '["https://www.tiendeo.co.za/stores/polokwane/crazy-store-market-st-shop-game-centre-polokwane-south-africa/7409", "https://za.near-place.com/the-crazy-store-polokwane-game-centre-market-st-shop-3-game-centre-polokwane"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'the-crazy-store-game-centre-polokwane-central'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('rage-game-centre-polokwane-central', 'Rage Game Centre', (SELECT id FROM suburbs WHERE slug = 'polokwane-central'), (SELECT id FROM shopping_centers WHERE slug = 'game-centre-polokwane-central'), 'Shop 0006, Game Centre, Cnr Hospital & Kerk Street, Polokwane, 0699', '015 297 3510', NULL, NULL, 'Rage is a fashion retailer selling women''s footwear, clothing and accessories, trading from Game Centre.', NULL, NULL, '["https://www.tiendeo.co.za/stores/polokwane/rage", "https://www.shopshours.co.za/rage/polokwane"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'rage-game-centre-polokwane-central'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('rochester-game-centre-polokwane-central', 'Rochester Game Centre', (SELECT id FROM suburbs WHERE slug = 'polokwane-central'), (SELECT id FROM shopping_centers WHERE slug = 'game-centre-polokwane-central'), 'Shop 0021, Game Centre, Cnr Hospital and Kerk Street, Polokwane, 0700', '087 463 0102', NULL, NULL, 'Rochester is a furniture retailer selling lounge, dining and bedroom suites, trading from Game Centre.', NULL, NULL, '["https://www.rochester.co.za/store/rochester-polokwane", "https://my-catalogue.co.za/stores/polokwane/rochester/game-centre-cnr-hospital-and-kerk-st"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'rochester-game-centre-polokwane-central'), (SELECT id FROM categories WHERE slug = 'furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('united-furniture-outlets-game-centre-polokwane-central', 'United Furniture Outlets Game Centre', (SELECT id FROM suburbs WHERE slug = 'polokwane-central'), (SELECT id FROM shopping_centers WHERE slug = 'game-centre-polokwane-central'), 'Shop 0018B, Game Centre, Cnr Hospital and Kerk Street, Polokwane, 0699', '015 023 0708', NULL, NULL, 'United Furniture Outlets (UFO) is a furniture and household appliance retailer, trading from Game Centre.', NULL, NULL, '["https://www.unitedfurnitureoutlets.co.za/stores/polokwane-game-centre/", "https://www.brabys.com/za/limpopo/polokwane/u-f-o-united-furniture-outlets"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'united-furniture-outlets-game-centre-polokwane-central'), (SELECT id FROM categories WHERE slug = 'furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('superspar-game-centre-polokwane-central', 'SUPERSPAR Game Centre', (SELECT id FROM suburbs WHERE slug = 'polokwane-central'), (SELECT id FROM shopping_centers WHERE slug = 'game-centre-polokwane-central'), 'Shop 0012, Game Centre, Cnr Hospital and Market Street, Polokwane, 0699', '015 297 4679', NULL, NULL, 'SUPERSPAR is a full-line supermarket selling groceries, fresh produce, bakery and butchery items, trading from Game Centre.', NULL, NULL, '["https://my-catalogue.co.za/stores/polokwane/spar/game-shopping-centre-corner-hospital-and-market-str", "https://www.tiendeo.co.za/polokwane/spar"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'superspar-game-centre-polokwane-central'), (SELECT id FROM categories WHERE slug = 'supermarkets-groceries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('real-fish-and-chips-game-centre-polokwane-central', 'Real Fish and Chips Game Centre', (SELECT id FROM suburbs WHERE slug = 'polokwane-central'), (SELECT id FROM shopping_centers WHERE slug = 'game-centre-polokwane-central'), 'Shop 5C, Game Centre, Cnr Hospital & Kerk Street, Polokwane', '071 418 9820', NULL, NULL, 'Real Fish and Chips is a fast-food takeaway selling fried fish, chips and chicken, trading from Game Centre.', NULL, NULL, '["https://www.realfishandchips.co.za/real-fish-and-chips-stores/", "https://restaurantguru.com/REAL-Fish-Chicken-and-Chips-Polokwane"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'real-fish-and-chips-game-centre-polokwane-central'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('tops-game-centre-polokwane-central', 'Tops at Spar Game Centre', (SELECT id FROM suburbs WHERE slug = 'polokwane-central'), (SELECT id FROM shopping_centers WHERE slug = 'game-centre-polokwane-central'), 'Shop 0010, Game Centre, Cnr Hospital and Market Street, Polokwane, 0699', '015 297 4679', NULL, NULL, 'Tops at Spar is a liquor store selling beer, wine and spirits, trading from Game Centre alongside SUPERSPAR.', NULL, NULL, '["https://my-catalogue.co.za/stores/polokwane/tops-at-spar/game-shopping-centre-corner-hospital-and-market-str", "https://www.tiendeo.co.za/polokwane/spar-tops"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'tops-game-centre-polokwane-central'), (SELECT id FROM categories WHERE slug = 'liquor-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('maxis-game-centre-polokwane-central', 'Maxi''s Game Centre', (SELECT id FROM suburbs WHERE slug = 'polokwane-central'), (SELECT id FROM shopping_centers WHERE slug = 'game-centre-polokwane-central'), 'Shop 0017, Game Centre, Cnr Hospital & Market Street, Polokwane, 0699', '015 297 1943', NULL, NULL, 'Maxi''s is a family sit-down restaurant serving breakfast, grills and light meals, trading from Game Centre.', NULL, NULL, '["https://za.near-place.com/maxis-polokwane", "https://www.yep.co.za/biz/store/maxis-restaurant/340576"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'maxis-game-centre-polokwane-central'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

-- Checkers Centre (polokwane-central) tenant

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('ackermans-checkers-centre-polokwane-central', 'Ackermans Checkers Centre', (SELECT id FROM suburbs WHERE slug = 'polokwane-central'), (SELECT id FROM shopping_centers WHERE slug = 'checkers-centre-polokwane-central'), 'Shop 22, Checkers Centre, Grobler Street, Polokwane, 0700', '015 291 1028', NULL, NULL, 'Ackermans is a value clothing retailer selling affordable fashion for women, kids and babies, trading from Checkers Centre.', NULL, NULL, '["https://www.tiendeo.co.za/stores/polokwane/ackermans", "https://my-catalogue.co.za/stores/polokwane/ackermans/polokwane-checkers-centre-grobler-str"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'ackermans-checkers-centre-polokwane-central'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

-- Mall of the North (bendor) tenants (47 of 58 leads -- excludes 11 that
-- relied only on generic, non-location-specific tiendeo.co.za matches)

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('at-home-mall-of-the-north-bendor', '@home', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L14, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 0980', NULL, NULL, '@home is a home decor and furniture retailer offering furniture, homeware and decor, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/at-home-mall-of-the-north-cnr-r-n-interchange-bendor/15673"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'at-home-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('ackermans-mall-of-the-north-bendor', 'Ackermans', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L53, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1051', NULL, NULL, 'Ackermans is a value fashion retailer offering clothing, footwear and homeware for the family, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/ackermans"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'ackermans-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('african-bank-mall-of-the-north-bendor', 'African Bank', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L43a, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1421', NULL, NULL, 'African Bank is a retail bank branch offering personal banking and loan services, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://mycityinfo.co.za/places/south-africa/limpopo/polokwane/finance/african-bank-mall-of-the-north/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'african-bank-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'banks-atms'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('aldo-mall-of-the-north-bendor', 'ALDO', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U45, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '087 164 1188', NULL, NULL, 'ALDO is an international footwear and accessories retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.yellosa.co.za/company/789126/aldo-mall-of-the-north"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'aldo-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('amarillo-spur-mall-of-the-north-bendor', 'Amarillo Spur', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U102, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1377', NULL, NULL, 'Amarillo Spur is a Spur-branded family steakhouse restaurant, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://crave.co.za/establishment.asp?est=16713"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'amarillo-spur-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('american-swiss-mall-of-the-north-bendor', 'American Swiss', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U41, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 0976', NULL, NULL, 'American Swiss is a jewellery and watch retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://nearfinderza.com/en/business/lp/polokwane/watchmakers/american-swiss-mall-of-the-north_63071+2.html"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'american-swiss-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'jewellers'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('archive-mall-of-the-north-bendor', 'Archive', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U75, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 0951', NULL, NULL, 'Archive is a premium sneaker and streetwear retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://bash.com/store/archive-mall-of-the-north-polokwane-limpopo-0699/061173"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'archive-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('babies-r-us-mall-of-the-north-bendor', 'Babies R Us', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U68, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '087 234 8532', NULL, NULL, 'Babies R Us is a baby products and gear retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.babiesrus.co.za/mall-of-the-north"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'babies-r-us-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('bathu-mall-of-the-north-bendor', 'Bathu', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U18, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '010 271 4598', NULL, NULL, 'Bathu is a South African sneaker brand retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.bathu.co.za/pages/stores"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'bathu-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('biltong-pret-mall-of-the-north-bendor', 'Biltong Pret', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L74, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '061 559 6012', NULL, NULL, 'Biltong Pret is a biltong and dried-meat products retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.searchinafrica.com/business/6025029/south-africa/limpopo/polokwane/bendor/n1/biltong-retailers/biltong-pret"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'biltong-pret-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'butcheries'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('birkenstock-mall-of-the-north-bendor', 'Birkenstock', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U64, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '010 085 0734', NULL, NULL, 'Birkenstock is a footwear retailer specialising in Birkenstock sandals and shoes, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.bizcommunity.com/article/birkenstock-debuts-in-limpopo-with-new-sustainable-store-concept-066735a"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'birkenstock-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('bogart-man-mall-of-the-north-bendor', 'Bogart Man', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U46, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '087 625 0442', NULL, NULL, 'Bogart Man is a menswear fashion retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.bogartman.com/pages/mall-of-the-north"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'bogart-man-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('brazilia-mall-of-the-north-bendor', 'Brazilia', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L18a, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '087 820 1877', NULL, NULL, 'Brazilia is a swimwear and beachwear retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.shopbrazilia.com/pages/storelocations"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'brazilia-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('browns-jewellers-mall-of-the-north-bendor', 'Browns Jewellers', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U47, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1441', NULL, NULL, 'Browns Jewellers is a jewellery and diamond retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://brownsjewellers.com/StoreLocator"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'browns-jewellers-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'jewellers'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('burger-king-mall-of-the-north-bendor', 'Burger King', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U69a, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 541 0200', NULL, NULL, 'Burger King is a fast-food burger restaurant, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.burgerking.co.za/store-locator/store/25477/mall-of-the-north-shopping-centre--polokwane--limpopo--699"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'burger-king-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('capitec-bank-mall-of-the-north-bendor', 'Capitec Bank', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L42, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '087 756 0613', NULL, NULL, 'Capitec Bank is a retail bank branch offering personal and business banking services, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/capitec-bank-shop-l-mall-of-the-north-bendor-extention-protea-south/63240"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'capitec-bank-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'banks-atms'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('cappuccinos-mall-of-the-north-bendor', 'Cappuccinos', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U104, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 880 0298', NULL, NULL, 'Cappuccinos is an Italian-style café and pizzeria restaurant, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/cappuccinos-shop-u-mall-of-the-north-shopping-centre-corner-of-n-r-bendor/35806"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'cappuccinos-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('cardies-mall-of-the-north-bendor', 'Cardies', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L71, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1319', NULL, NULL, 'Cardies is a gifting, stationery and home decor retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://cardies.co.za/pages/mall-of-the-north"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'cardies-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'general-retail'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('contempo-mall-of-the-north-bendor', 'Contempo', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L58, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '013 880 1667', NULL, NULL, 'Contempo is a women''s fashion retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://contemposhop.co.za/storelocator/mall-of-the-north"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'contempo-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('cotton-on-mall-of-the-north-bendor', 'Cotton On', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U65, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '087 563 3199', NULL, NULL, 'Cotton On is a casual fashion and accessories retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/cotton-on"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'cotton-on-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('dis-chem-mall-of-the-north-bendor', 'Dis-Chem', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L73, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 0300', NULL, NULL, 'Dis-Chem is a pharmacy and health, beauty and wellness retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/dischem"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'dis-chem-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'pharmacies'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('hm-mall-of-the-north-bendor', 'H&M', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U59, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '064 758 2419', NULL, NULL, 'H&M is an international fashion clothing retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.hm.com/za/store-locator/south-africa/polokwane/mall-of-the-north/"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'hm-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('identity-mall-of-the-north-bendor', 'Identity', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U13, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '087 757 0165', NULL, NULL, 'Identity is a menswear fashion retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/identity"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'identity-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('incredible-connection-mall-of-the-north-bendor', 'Incredible Connection', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L26, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 0800', NULL, NULL, 'Incredible Connection is an electronics, computers and appliances retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/incredible-connection"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'incredible-connection-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'electronics-appliances'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('kurt-geiger-mall-of-the-north-bendor', 'Kurt Geiger', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U23, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '010 493 4194', NULL, NULL, 'Kurt Geiger is a footwear and accessories retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/kurt-geiger"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'kurt-geiger-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('levis-mall-of-the-north-bendor', 'Levi''s', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U17, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1225', NULL, NULL, 'Levi''s is a denim and casual clothing retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/levis"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'levis-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('mr-price-mall-of-the-north-bendor', 'Mr Price', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U62, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '087 049 6816', NULL, NULL, 'Mr Price is a fashion clothing and accessories retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/mr-price"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'mr-price-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('mr-price-home-mall-of-the-north-bendor', 'Mr Price Home', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L68, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1019', NULL, NULL, 'Mr Price Home is a homeware and decor retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/mr-price-home"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'mr-price-home-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('mr-price-sport-mall-of-the-north-bendor', 'Mr Price Sport', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U78, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '087 750 8655', NULL, NULL, 'Mr Price Sport is a sportswear and sports equipment retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/mr-price-sport"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'mr-price-sport-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('nedbank-mall-of-the-north-bendor', 'Nedbank', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U1, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 0160', NULL, NULL, 'Nedbank is a retail bank branch offering personal and business banking services, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/nedbank"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'nedbank-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'banks-atms'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('old-khaki-mall-of-the-north-bendor', 'Old Khaki', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U81a, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1068', NULL, NULL, 'Old Khaki is a casual outdoor-lifestyle fashion retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/old-khaki"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'old-khaki-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('pep-home-mall-of-the-north-bendor', 'PEP Home', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L16, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1069', NULL, NULL, 'PEP Home is a value homeware retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/pep-home"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'pep-home-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'furniture-homeware'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('polo-mall-of-the-north-bendor', 'Polo', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U52, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1162', NULL, NULL, 'Polo is a premium fashion clothing retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.polo.co.za/polo-mall-of-the-north"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'polo-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('postnet-mall-of-the-north-bendor', 'Postnet', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L4, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '087 310 6013', NULL, NULL, 'Postnet is a courier, printing and business services outlet, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/postnet"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'postnet-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'printing-services'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('rochester-mall-of-the-north-bendor', 'Rochester', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L16a, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '087 463 0340', NULL, NULL, 'Rochester is a menswear fashion retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/rochester"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'rochester-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('skechers-mall-of-the-north-bendor', 'Skechers', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L49, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 140 0120', NULL, NULL, 'Skechers is a footwear retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/skechers"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'skechers-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sorbet-mall-of-the-north-bendor', 'Sorbet', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L79, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1279', NULL, NULL, 'Sorbet is a beauty, nail and spa salon, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/sorbet"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'sorbet-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'beauty-hair-salons'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('spec-savers-mall-of-the-north-bendor', 'Spec-Savers', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L39, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1018', NULL, NULL, 'Spec-Savers is an optometry and eyewear practice, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/spec-savers"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'spec-savers-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'opticians'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sportscene-mall-of-the-north-bendor', 'Sportscene', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U90, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 0921', NULL, NULL, 'Sportscene is a sneaker and street fashion retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/sportscene"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'sportscene-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sterns-mall-of-the-north-bendor', 'Sterns', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U83, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 0936', NULL, NULL, 'Sterns is a jewellery and watch retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/sterns"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'sterns-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'jewellers'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('studio-88-mall-of-the-north-bendor', 'Studio 88', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U36, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1298', NULL, NULL, 'Studio 88 is a footwear and sneaker retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/studio-88"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'studio-88-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('sunglass-hut-mall-of-the-north-bendor', 'Sunglass Hut', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U95a, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '021 267 2821', NULL, NULL, 'Sunglass Hut is a sunglasses and eyewear retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/sunglass-hut"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'sunglass-hut-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'opticians'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('tekkie-town-mall-of-the-north-bendor', 'Tekkie Town', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L18, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '087 802 8417', NULL, NULL, 'Tekkie Town is a footwear retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/tekkie-town"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'tekkie-town-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('telkom-mall-of-the-north-bendor', 'Telkom', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L51, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1229', NULL, NULL, 'Telkom is a telecommunications retail store, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/telkom"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'telkom-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'mobile-phones'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('the-body-shop-mall-of-the-north-bendor', 'The Body Shop', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U27, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1219', NULL, NULL, 'The Body Shop is a beauty and cosmetics retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/the-body-shop"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'the-body-shop-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'beauty-hair-salons'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('timberland-mall-of-the-north-bendor', 'Timberland', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U55, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '010 006 9308', NULL, NULL, 'Timberland is a footwear and outdoor apparel retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/timberland"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'timberland-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('totalsports-mall-of-the-north-bendor', 'Totalsports', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U93, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 0914', NULL, NULL, 'Totalsports is a sportswear and sports footwear retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/totalsports"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'totalsports-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'shoe-stores'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('truworths-elements-mall-of-the-north-bendor', 'Truworths Elements', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop U12f, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '081 171 0162', NULL, NULL, 'Truworths Elements is a women''s fashion clothing retailer, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/truworths"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'truworths-elements-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'fashion-clothing'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('vodacom-shop-mall-of-the-north-bendor', 'Vodacom Shop', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L56, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '015 265 1457', NULL, NULL, 'Vodacom Shop is a mobile network retail store, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/vodacom"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'vodacom-shop-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'mobile-phones'), 1);

INSERT OR IGNORE INTO businesses (slug, name, suburb_id, shopping_center_id, address, phone, website, email, description, lat, lng, source_urls, status, origin) VALUES
('wimpy-mall-of-the-north-bendor', 'Wimpy', (SELECT id FROM suburbs WHERE slug = 'bendor'), (SELECT id FROM shopping_centers WHERE slug = 'mall-of-the-north-bendor'), 'Shop L12, Mall of the North, Munnik Ave, Bendor, Polokwane, 0699', '076 556 7486', NULL, NULL, 'Wimpy is a family restaurant serving breakfasts, burgers and grills, trading from Mall of the North.', NULL, NULL, '["https://mallofthenorth.co.za/stores/", "https://www.tiendeo.co.za/stores/polokwane/wimpy"]', 'published', 'agent_research');
INSERT OR IGNORE INTO business_categories (business_id, category_id, is_primary) VALUES ((SELECT id FROM businesses WHERE slug = 'wimpy-mall-of-the-north-bendor'), (SELECT id FROM categories WHERE slug = 'restaurants-takeaways'), 1);
