-- content-upgrade:polokwane:016: 17 descriptions (33 deferred, no SQL), generated by scripts/content-upgrade/to-sql.mjs
-- arabela-legacy-lodge-makhadzi-cloud-lodge-dalmada (researched)
UPDATE businesses SET description = 'Arabela Legacy Lodge, also known as Makhadzi Cloud Lodge, is a guesthouse in Dalmada, about 14 km from the Polokwane Game Reserve. It is set in a garden with an outdoor swimming pool, and its rooms are air-conditioned, with free private parking on site.

Guests can ask for an iron and ironing board when needed, and they may bring their own ready-made food, which suits travellers who want to self-cater. Staff speak English, Xhosa and Zulu, and guests who want to change their checkout time can ask reception, though a fee may apply. The lodge is at Plot 21 Dalmada Road, a practical base for visitors who want a garden stay close to the Game Reserve and the city.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://makhadziclouds.inn.fan/'), description_enriched_at = datetime('now') WHERE slug = 'arabela-legacy-lodge-makhadzi-cloud-lodge-dalmada' AND description = 'Arabela Legacy Lodge, also known as Makhadzi Cloud Lodge, is a guesthouse in Dalmada set in a garden with an outdoor swimming pool, air-conditioned rooms and free private parking.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- crystal-coffee-shop-polokwane-central (researched)
UPDATE businesses SET description = 'Crystal Coffee Shop on Marshall Street in Polokwane Central is a coffee shop that hosts bridal and baby showers, small weddings and functions, and business lunches. The shop specialises in cakes for all occasions, and it has an on-site hair and beauty salon, so visitors can combine a coffee with a treatment.

Customers can order with roadside or in-store collection, and the business says it aims to turn special moments into beautiful memories. Its Facebook page has more than 2,000 followers and lists the shop as a place for functions as well as everyday coffee. The shop suits families planning a baby shower, a small wedding or a business lunch in the city centre.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.facebook.com/p/Crystal-Coffee-Shop-100063594938093/'), description_enriched_at = datetime('now') WHERE slug = 'crystal-coffee-shop-polokwane-central' AND description = 'Crystal Coffee Shop on Marshall Street hosts bridal and baby showers, small weddings and functions and business lunches, and offers custom cakes alongside an on-site hair and beauty salon.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- dalmada-storage-dalmada (researched)
UPDATE businesses SET description = 'Dalmada Storage offers secure self-storage units, storage containers and shaded parking at its premises in Dalmada, Polokwane. The business says it provides safe, reliable and affordable storage for individuals, families and businesses, and it also hires out shipping containers.

Short-term storage during a move, long-term business storage and secure parking for vehicles, trailers, caravans and equipment are all offered. The company says it has built a reputation over many years for trusted security, excellent service and customer satisfaction. Its facility is kept clean, well maintained and professionally managed, and the business has served Polokwane''s storage needs for more than 10 years from Plot 36/1, Dalmada.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.dalmada-storage.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'dalmada-storage-dalmada' AND description = 'Dalmada Storage offers secure self-storage units, shaded parking and shipping container hire from its Dalmada premises, and has served Polokwane''s short- and long-term storage needs for over 10 years.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- diamond-inc-attorneys-bendor (researched)
UPDATE businesses SET description = 'Diamond Incorporated is a law firm in Bendor, Polokwane, that provides a wide range of legal services and handles High Court and Magistrate''s Court litigation. The firm''s fields include personal injury claims, corporate and commercial law, and business rescue matters.

The firm describes its team as experienced and says it aims to give clients sound advice and the best service possible. The practice was established in 1976, according to its listing, and it serves individuals and companies that need advice across most areas of law. The website says the firm can assist with all aspects of the law and has ample experience in the fields it lists. Its office is at 2a Pierre Street in Bendor, Polokwane.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.diamondinc.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'diamond-inc-attorneys-bendor' AND description = 'Diamond Inc Attorneys is a Bendor law firm established in 1976, handling personal injury claims, High Court and Magistrate Court litigation, corporate and commercial law, and business rescue matters.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- evn-africa-polokwane-central (researched)
UPDATE businesses SET description = 'EVN Africa is a multidisciplinary engineering consultancy in Polokwane Central, with fields that include water supply, regional planning, townships, sanitation, structural and agricultural engineering, and roads. Its services include civil, structural, water and sanitation design, and roads and infrastructure design.

The company says it is also active in project and construction management, and its associated companies cover electrical engineering and environmental services. Its work runs from pre-site appraisal through to construction monitoring, so clients can keep one consultant on a project from start to finish. The website lists its fields of specialisation and group companies in one place, so prospective clients can see the disciplines it covers. The office is at 30 Schoeman Street in Polokwane Central.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.yellosa.co.za/company/148527/evn-africa', '$[#]', 'https://www.evn.co.za'), description_enriched_at = datetime('now') WHERE slug = 'evn-africa-polokwane-central' AND description = 'EVN Africa is a multidisciplinary engineering consultancy in Polokwane Central, providing civil, structural, water & sanitation and roads & infrastructure design services from pre-site appraisal through to construction monitoring.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- florapark-comprehensive-high-school-flora-park (researched)
UPDATE businesses SET description = 'Florapark Comprehensive High School is a public secondary school in Flora Park, offering CAPS-aligned schooling from the Senior Phase in Grades 8 and 9 through the FET phase to matric in Grade 12. The school''s website describes a new site with a school mobile app and a digital library available to learners.

Matric learners can use the Grade 12 resources section, which includes past papers, study guides and examination guides, along with information on bursaries and a university brochure. The school credits its educators for the hard work they put in every day, and it shares its events, such as a 2025 gala dinner, in a gallery of photos. The school is at 244 Suid Street in Flora Park.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://fchs.co.za'), description_enriched_at = datetime('now') WHERE slug = 'florapark-comprehensive-high-school-flora-park' AND description = 'Florapark Comprehensive High School is a public secondary school in Flora Park offering CAPS-aligned schooling from the Senior Phase (Grade 8-9) through the FET phase to matric (Grade 12).' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- georeen-guest-house-sterpark (researched)
UPDATE businesses SET description = 'Georeen Guest House is a nine-room guesthouse in Sterpark, Polokwane, with en-suite rooms that are individually decorated. Guests can relax by the outdoor swimming pool or in the garden, and a daily breakfast is served in the dining area. The website includes a gallery of the rooms and grounds, so visitors can see the garden and pool before they book.

The guesthouse says it takes pride in its warm welcome, service and hospitality, and its owner greets guests personally as a friendly hostess. The findmy listing says the house offers good value for money, which suits visitors who want a comfortable base in Polokwane. The guesthouse is at 8 Regulus Avenue in Sterpark.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.georeenguesthouse.co.za', '$[#]', 'https://www.findmy.co.za/services/business/georeen-guest-house/40271'), description_enriched_at = datetime('now') WHERE slug = 'georeen-guest-house-sterpark' AND description = 'Georeen Guest House is a 9-room guest house in Sterpark with en-suite, individually decorated rooms, an outdoor swimming pool and garden, and daily breakfast served in its dining area.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- greener-tidings-garden-centre-bendor (researched)
UPDATE businesses SET description = 'Greener Tidings Garden Centre, inside The Farmyard Trading Post in Bendor, is a plant nursery and landscaping specialist. It offers plants, pots, garden accessories and garden decor, along with professional landscaping and waterwise planting advice.

The centre says it was awarded best garden centre in South Africa, and it reports first place for best inspirational displays, second place for its food gardening department and third place for best staff. Its website describes knowledgeable staff and a wide variety of plants, and the centre aims to give Polokwane gardeners the best advice at hand. The centre is at 2 Knottrox Avenue, Bendor Extension 115.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.greenertidings.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'greener-tidings-garden-centre-bendor' AND description = 'Greener Tidings Garden Centre, inside The Farmyard Trading Post in Bendor, is a plant nursery and landscaping specialist offering pots, garden decor, waterwise planting advice and outdoor landscaping services.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- m-n-m-guesthouse-mankweng (researched)
UPDATE businesses SET description = 'M n M Guesthouse offers seven individually decorated guestrooms near the University of Limpopo and Paledi Mall in Mankweng, with free Wi-Fi, free parking and a 24-hour front desk. Each stay includes a cooked breakfast, and the guesthouse says it offers a clean and crisp environment for guests travelling for business or leisure.

The business runs two guesthouses, one in Polokwane Central and one in Turfloop, Mankweng. Its motto is Mi casa es su casa, and staff speak English, Xhosa, Zulu and Afrikaans and can point guests to the places to visit around Polokwane. The Mankweng guesthouse is at 1338 Mamadimo Park on the R71.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://mnmguesthouse.co.za'), description_enriched_at = datetime('now') WHERE slug = 'm-n-m-guesthouse-mankweng' AND description = 'M n M Guesthouse offers seven individually decorated guestrooms near the University of Limpopo and Paledi Mall, with free WiFi, free parking, a 24-hour front desk and cooked breakfast.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- madithapa-sandblasting-painting-roodepoort-polokwane (researched)
UPDATE businesses SET description = 'Madithapa Sandblasting & Painting is a family-owned painting contractor that has served the Polokwane area for more than 20 years. The company describes itself as dedicated to preserving the life of physical assets with high-quality paints and durable coatings, and it offers sandblasting alongside painting.

Its work covers residential, commercial and government painting contracts of any size, and client testimonials on its website praise the attention to detail, professionalism and workmanship. Consultation on how a project comes together is also part of the service, and its testimonials come from construction companies and property developers it has worked with on several projects. The business is based at Plot 12 in Roodepoort, Polokwane.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://madithapa.co.za'), description_enriched_at = datetime('now') WHERE slug = 'madithapa-sandblasting-painting-roodepoort-polokwane' AND description = 'Madithapa Sandblasting & Painting is a family-owned painting contractor that has served the Polokwane area for over 20 years, handling residential, commercial and government painting contracts of any size.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- mavuna-netshimbupfe-inc-polokwane-central (researched)
UPDATE businesses SET description = 'Mavuna & Netshimbupfe Inc is a law firm in Polokwane established in 2020, which describes itself as a 100% black women-owned firm. The firm lists a broad range of practice areas, including conveyancing, notarial services, deceased estates, divorce and family law, labour law and property law.

Its areas also include commercial and company law, wills and trusts, Road Accident Fund claims, debt collection, and litigation in the High Court and the Magistrates'' Court. Clients can use the firm for general legal advice across these fields. The listing also includes company registrations, notarial work and partnership agreements among its practice areas, and the office is at 28A Bodenstein Street in Polokwane.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.attorneys.co.za/CompanyHomePage.asp?CompanyID=1720'), description_enriched_at = datetime('now') WHERE slug = 'mavuna-netshimbupfe-inc-polokwane-central' AND description = 'Mavuna & Netshimbupfe Inc is a 100% black women-owned law firm established in 2020, offering conveyancing, notarial and litigation services alongside general legal advisory from its Bodenstein Street office.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- meason-construction-maintenance-polokwane-central (researched)
UPDATE businesses SET description = 'Meason Construction & Maintenance has operated since 2007, offering construction for commercial and residential buildings, along with plumbing, carpentry, electrical and solar work. The company describes itself as trading across Limpopo, the Western Cape and the Eastern Cape. Its electrical team has experience installing, repairing and maintaining systems linked to the solar industry.

Its maintenance services include waterproofing for external walls, facades and roofs, including roof rubber and other acrylic roof solutions, and it also builds, repairs and treats roofs and thatch structures. The business is a preferred service provider for several major insurance companies, according to its listing. Its Polokwane Central office is at 68A Hoog Street.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://meason.co.za'), description_enriched_at = datetime('now') WHERE slug = 'meason-construction-maintenance-polokwane-central' AND description = 'Meason Construction & Maintenance has provided plumbing, carpentry, electrical and general building maintenance services in Polokwane since 2007, and is a preferred service provider for several major insurance companies.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- mosate-lodge-hospark (researched)
UPDATE businesses SET description = 'Mošatê Lodge is a four-star accommodation and conference venue on the corner of Grobler and Dorp Streets in Hospital Park, Polokwane. The lodge describes its rooms as beautifully appointed and designed for relaxation, and it offers a serene retreat for guests visiting for business or leisure.

For business travellers, the lodge has conferencing facilities for meetings and events, and its website lets visitors view the rooms, host a conference or make a reservation directly. The lodge presents itself as a home away from home in Limpopo, which makes it a practical choice for visitors who want four-star comfort and professional conference facilities in one place.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.mosate.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'mosate-lodge-hospark' AND description = 'Mosate Lodge is a guest lodge and conference venue on the corner of Grobler and Dorp Street in Hospital Park, Polokwane, offering guest accommodation alongside event and conference facilities.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- nandos-polokwane-cbd-polokwane-central (researched)
UPDATE businesses SET description = 'Nando''s Polokwane CBD is a flame-grilled PERi-PERi chicken restaurant on Schoeman Street in Polokwane Central, close to the CBD tennis courts and Peter Mokaba Stadium. The restaurant serves Portuguese-inspired chicken, and it is open for dine-in, collection and delivery. The listing describes a spacious dining room.

The branch lists Wi-Fi, an alcohol licence and a generator among its amenities. Other Nando''s branches at Savannah Mall, Mall of the North, Paledi Mall and Thornhill are listed as nearby options for customers who want to eat at another location. The branch is at 60 Schoeman Street in Polokwane Central. Its page has separate call, delivery and collection links, so customers can order ahead or get in touch with the restaurant directly.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.nandos.co.za/eat/restaurant/polokwane-cbd'), description_enriched_at = datetime('now') WHERE slug = 'nandos-polokwane-cbd-polokwane-central' AND description = 'Nando''s Polokwane CBD, on Schoeman Street in the city centre, is the largest Nando''s outlet in Limpopo, serving the chain''s signature flame-grilled Portuguese-style chicken in a spacious dining room.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- nguni-grill-bendor (researched)
UPDATE businesses SET description = 'Nguni Grill is a family restaurant and bar on Morris Street in Bendor, Polokwane, serving breakfast, lunch and dinner. Its menu covers an exceptional range of steaks, burgers, ribs, pizza and other specialty dishes, and the restaurant says it offers great service, great food and great value.

The bar serves cocktails and beer, and the restaurant takes reservations by phone for a preferred party size and time. The business has served Polokwane since 2009, and its menu includes breakfast, burgers, steaks, sushi and grill platters. The restaurant is at 28 Morris Street in Bendor. Its website has a gallery and a feedback form, so diners can share how the food and service went.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.ngunigril.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'nguni-grill-bendor' AND description = 'Nguni Grill is a restaurant and bar on Morris Street in Bendor that has served Polokwane since 2009, with a menu spanning breakfast, burgers, steaks, sushi and grill platters.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- plumber-polokwane-polokwane-central (researched)
UPDATE businesses SET description = 'Plumber Polokwane is a plumbing service in Polokwane Central that offers residential and commercial plumbing to people across Polokwane and the surrounding areas. Its services include geyser installation and repair for electric, gas and solar geysers, blocked drains, leak detection and water tank installation.

The team also handles emergency plumbing, general plumbing, water meter installation and general maintenance, with emergency callouts for urgent faults. The business presents itself as affordable and reliable, and it invites customers to call for a quote before work starts. Its website lists leak detection and blocked drains alongside geyser work, so one plumber covers the main household jobs. The office is at Unit 12, 51 Biccard Street in Polokwane Central.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.plumberpolokwane.co.za'), description_enriched_at = datetime('now') WHERE slug = 'plumber-polokwane-polokwane-central' AND description = 'Plumber Polokwane is a plumbing service in Polokwane Central offering geyser installation and repair (electrical, gas and solar), leak detection and drain unblocking, alongside general maintenance and emergency callouts.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- pratt-luyt-de-lange-bendor-park (researched)
UPDATE businesses SET description = 'Pratt Luyt & De Lange is one of the oldest established law firms in Polokwane, with a history dating back to 1908. The firm serves companies, individuals, financial institutions and government, and it says it provides tailor-made solutions across different fields of law.

Its practice covers conveyancing, commercial law, litigation and deceased estates, and the firm says it is recognised for its professionalism and its ability to assist clients. Its staff undergo ongoing training, which the firm says keeps the team fast and efficient, and it says its commitment to clients is rooted in both its professional and administrative staff. The office is at 20 Watermelon Street in Bendor Park.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.prattluyt.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'pratt-luyt-de-lange-bendor-park' AND description = 'Pratt Luyt & De Lange is a long-established Polokwane law firm tracing its history back to 1908, with a practice focused on conveyancing, commercial law, litigation and deceased estates.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
