-- content-upgrade:polokwane:019: 15 descriptions (35 deferred, no SQL), generated by scripts/content-upgrade/to-sql.mjs
-- rix-pawnshop-cc-annadale (researched)
UPDATE businesses SET description = 'Rix Pawnshop is a family-owned pawnbroker on Witklip Street in Annadale, Polokwane, operating since 2015 and centrally located in the city. It buys, sells and pawns pre-owned and new goods, including pool table equipment, catering equipment, furniture, electronics and tools.

The shop says it buys almost anything and pays cash for goods. Customers can send a photo through WhatsApp for an offer, or ask the team to visit within Polokwane at no charge, and the shop also lends cash against goods. It describes its transactions as professional, friendly, discreet and confidential, and it is licensed under the Second-Hand Goods Act and is a registered member of the National Credit Regulator.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.rixpawnshop.co.za/', '$[#]', 'http://www.rixpawnshop.co.za/about'), description_enriched_at = datetime('now') WHERE slug = 'rix-pawnshop-cc-annadale' AND description = 'Rix Pawnshop cc is a pawnbroker on Witklip Street in Annadale that buys, sells and pawns second-hand goods, and also supplies new and used catering equipment, electronics and pool table spares.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- s-a-compressor-care-futura (researched)
UPDATE businesses SET description = 'SA Compressor Care sells, installs and services air compressors of all major brands, with its services covering repairs, 24-hour standby support, field services and the installation of pneumatic pipelines. The company also offers on-site pressure testing, the repair and supply of rockdrills and paving breakers, and the repair of high-pressure mobile and piston compressors.

Its list of services includes the repair and servicing of refrigerant and desiccant dryers, and the business gives technical advice on all aspects of compressed air. Its compressor hire fleet has a wide range of mobile and electrical rental units available. The company''s website lists sales, repairs and services on Kaeser products, and it is based in Polokwane.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://sacompressor.co.za/'), description_enriched_at = datetime('now') WHERE slug = 's-a-compressor-care-futura' AND description = 'S A Compressor Care sells, installs and services air compressors of all major brands from its Futura premises, offering repairs, 24-hour standby support, pneumatic pipeline installation and a compressor hire fleet.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- the-red-bin-ladine (researched)
UPDATE businesses SET description = 'The Red Bin is a rubble and waste removal service in Ladine, Polokwane, offering residential, commercial, industrial and construction rubble and waste removal in and around Polokwane, Tzaneen and Louis Trichardt. It is a division of the BF Petroleum Group, and its service runs from receiving an order through to disposing of the waste in a responsible manner.

Customers can order a skip, and the company says it tailors its solutions to each client''s needs. Its website describes a simple booking process, with clients calling the business and the team collecting the waste. The company is based at 124 Blaauwberg Street in Ladine, Polokwane.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://theredbin.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'the-red-bin-ladine' AND description = 'The Red Bin is a rubble and waste removal service in Ladine, Polokwane, part of the BF Petroleum Group, offering residential, commercial, industrial and construction waste collection with fast turnaround times.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- beauty-matters-eduan-park (researched)
UPDATE businesses SET description = 'Beauty Matters is a medical aesthetics clinic and spa in Eduan Park, Polokwane, dedicated to women''s beauty and wellbeing. It offers medical anti-ageing treatments, including laser hair removal, facial rejuvenation and skin resurfacing, alongside micro-needling, chemical peels and dermaplaning.

The clinic also offers a full range of body treatments, manicures, pedicures and signature treatments, and it sells a Lamelle skincare range that clients can use at home. Clients on its website praise the clinic''s professionalism, cleanliness and punctuality, and they describe the staff as friendly and knowledgeable. Clients can reserve a treatment through the website''s Make a Booking button. The clinic is at 214 Potgieter Avenue in Eduan Park.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.beautymattersplk.co.za', '$[#]', 'https://www.beautymattersplk.co.za/laser-hair-removal/'), description_enriched_at = datetime('now') WHERE slug = 'beauty-matters-eduan-park' AND description = 'Beauty Matters is an aesthetics and beauty clinic in Eduan Park offering laser hair removal, skin treatments such as micro-needling, chemical peels and dermaplaning, plus body treatments, waxing, and manicures and pedicures.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- bosman-attorneys-hospark (researched)
UPDATE businesses SET description = 'Bosman Attorneys is a law firm in Hospital Park, Polokwane, founded in 2003 and built on more than 20 years of practice. The firm handles civil and criminal litigation, family law, legal costs and bail applications, and its practice areas include estate planning.

The firm says it places each client''s needs first and delivers a valued, personal service with traditional values and integrity, all within the framework of the law. Its team of seasoned professionals invites visitors to request a consultation through the website. The firm says its senior legal practitioner holds right of appearance in the High Court and has more than 20 years of experience in civil and criminal litigation. The office is at 37 Voortrekker Street in Hospital Park, Polokwane.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://bosmanattorneyssa.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'bosman-attorneys-hospark' AND description = 'Bosman Attorneys is a law firm in Hospital Park with over 20 years of experience, handling criminal law, civil litigation, family law and legal costs matters, including bail applications and estate planning.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- boss-recruitment-bendor (researched)
UPDATE businesses SET description = 'Boss Recruitment is a provisional placement and training agency in IT Park, Bendor, established in Polokwane in 1995. The agency says it has a track record of more than 15 years in recruitment and works with small and medium enterprises, corporate clients and government.

Its services include executive and general placements, temporary and contract placements, HR outsourcing and consulting, and training. Employment screening covers pre-employment checks, reference checks, and ITC, criminal, educational and driver''s licence checks. The agency says its core values are integrity, service excellence, professionalism and flexible staffing solutions. Clients can advertise vacancies at no cost, and the agency handles the responses to those adverts. Its office is at 11 Pierre Street.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://bossrecruitment.co.za/about'), description_enriched_at = datetime('now') WHERE slug = 'boss-recruitment-bendor' AND description = 'Boss Recruitment is a recruitment and staffing agency in IT Park, Bendor, established in 1995, offering contract placements, employment screening and HR outsourcing to small and medium enterprises, corporates and government clients.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- florapark-comprehensive-primary-school-flora-park (researched)
UPDATE businesses SET description = 'Florapark Comprehensive Primary School is a public primary school in Flora Park, established in 1998 and classified as a Quintile 5 school. It has around 1,346 learners and a staff of 39 teachers, and it sits on the corner of Jasmyn Avenue and Van Marle Street.

The school''s website includes a digital library split into bands for Grades 1 to 3, 4 to 5 and 6 to 7, along with past ANA papers and memos. Families can download the school''s mobile app, and the school shares a gallery of its school photos and videos. The school''s team credits its educators for the hard work they put in every day.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://floraparkprimary.co.za', '$[#]', 'https://www.school-register.co.za/school/florapark-comprehensive/'), description_enriched_at = datetime('now') WHERE slug = 'florapark-comprehensive-primary-school-flora-park' AND description = 'Florapark Comprehensive Primary School, established in 1998, is a public primary school in Flora Park with around 1,346 learners and a staff of 39 teachers, classified as a Quintile 5 institution.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- house-of-asante-spa-polokwane-central (researched)
UPDATE businesses SET description = 'House of Asante Spa is a boutique day spa at 29 Jorissen Street in Polokwane Central. It offers full body massages, aromatherapy and hot stone therapy, along with beauty treatments such as manicures, pedicures, waxing, body exfoliation and facials, and the spa says it caters for people who care about looking and feeling good.

The spa''s menu includes a traditional hammam bathing ritual and water therapies, and every visit begins with a welcome ritual. Guests can rate their treatment and give feedback afterwards. The spa has a state-of-the-art swimming pool that is free to use after a one-hour spa treatment, and bookings can be made by phone or through the online booking form on its website.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.houseofasantespa.co.za'), description_enriched_at = datetime('now') WHERE slug = 'house-of-asante-spa-polokwane-central' AND description = 'House of Asante Spa is a day spa in Polokwane Central offering full body massages, aromatherapy and hot stone therapy alongside beauty treatments such as manicures, pedicures, waxing, body exfoliation and facials.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- it-experts-bendor (researched)
UPDATE businesses SET description = 'IT Experts is an IT support company in Bendor, Polokwane, that has supported homes and businesses across Polokwane and Limpopo since 2007. Its services include computer repairs, desktop, server and network support, server management, and sales of IT hardware and software, with a focus on corporate clients.

The company also offers VoIP telephony with a fixed monthly call cost, cloud desktops, and a range of internet connectivity from LTE, wireless and fibre that can be customised to each client''s needs. Its office-in-the-cloud service gives staff secure remote access. The company is based at Ismini Office Estate on Adjutant Mauritz Dommisie Street in Bendor.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://itexperts.co.za'), description_enriched_at = datetime('now') WHERE slug = 'it-experts-bendor' AND description = 'IT Experts has provided computer repairs, server management, business internet, VoIP telephony and cloud desktop support to homes and businesses across Polokwane and the wider Limpopo region since 2007, operating from Bendor.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- lapologa-polokwane-flora-park (researched)
UPDATE businesses SET description = 'Lapologa at Polokwane is a guesthouse in the quiet, busy Flora Park suburb, offering self-catering apartments that are stylish, tastefully decorated and open-plan. The apartments have ample space for a business traveller or a whole family, and each has a fully equipped kitchenette, air-conditioning and DStv.

The establishment is a four-star graded guesthouse and describes itself as a luxury and comfort-driven stay, centrally located for business or holiday travel. Polokwane is close to the Kruger National Park and the Magoebaskloof mountains, and the guesthouse is a convenient base for visitors travelling to neighbouring countries. The guesthouse is at 362 Suid Street in Flora Park.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.lapologbnb.co.za/polokwane-guesthouse', '$[#]', 'https://bnbfinder.co.za/places/lapologa-polokwane/'), description_enriched_at = datetime('now') WHERE slug = 'lapologa-polokwane-flora-park' AND description = 'Lapologa @ Polokwane is a 4-star graded guesthouse in Flora Park offering self-catering apartments and en-suite rooms, each with a fully equipped kitchenette, air-conditioning and DStv, catering to both business and leisure stays.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- limpo-security-seshego (researched)
UPDATE businesses SET description = 'Limpo Security is a private security company based at the Seshego Industrial Site, which describes itself as passionate about reducing crime in Limpopo and South Africa. It offers guarding, patrolling, access control, monitoring and CCTV surveillance, alarm systems, gate automation and VIP protection across the Capricorn District.

The company says it structures its security services around each client''s specific needs, whether for a business or a private home. Its website sets out the services on a dedicated page, and visitors are invited to contact the team to find out how the company can help. The company is at Factory No. 05C/12 on Freedom Drive in Seshego.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.limposecurity.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'limpo-security-seshego' AND description = 'Limpo Security is a private security company based at the Seshego Industrial Site, offering guarding, patrolling, access control, CCTV surveillance, alarm systems, gate automation and VIP protection services across the Capricorn District.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- limpopo-seamless-gutters-polokwane-central (researched)
UPDATE businesses SET description = 'Limpopo Seamless Gutters manufactures colour-coated seamless gutters, box gutters, fascia boards and roof sheeting on site, matched to each roof, in Polokwane Central. The company also supplies aluminium, Chromadeck and zinc-alume gutters, and it installs them for homeowners, contractors and property managers.

Its services include roof and house painting, roof flashing, barge and fascia boards, and torch-on waterproofing, along with roof, wall and balcony waterproofing. The company works on new developments, schools, hospitals and office projects, and it supplies a range of colours that includes silver, white, charcoal and Colonial green. Customers can send an inquiry through the website, and the business is at 117 Thabo Mbeki Street.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.adsnational.co.za/listings/view/id/403/Limpopo-Seamless-Gutters-Polokwane-Limpopo'), description_enriched_at = datetime('now') WHERE slug = 'limpopo-seamless-gutters-polokwane-central' AND description = 'Limpopo Seamless Gutters manufactures colour-coated seamless gutters, box gutters, fascia boards and roof sheeting on site to match each roof, and also offers roof, wall and balcony waterproofing services in Polokwane Central.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- martek-roofing-magna-via (researched)
UPDATE businesses SET description = 'MarTek Roofing is a MiTek-licensed truss fabricator in Magna Via, Polokwane, established in 1991, which designs, manufactures and installs timber and galvanised steel roof trusses. The company describes its work as quality services with expert roof design, manufacturing and installation backed by certified engineering.

The team uses the latest MiTek software to design cost-effective roof frames, and it handles installation for both domestic and industrial projects. Its published process runs from a detailed quote and discussion through payment, measuring and planning to manufacture, installation and sign-off. The company says its main factory in Magna Via has operated since 2010, and it is at 30 Kaye-Lyn Street.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.martekroofing.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'martek-roofing-magna-via' AND description = 'MarTek Roofing is a MiTek-licensed truss fabricator that has designed, manufactured and erected pre-fabricated timber and galvanised steel roof trusses since 1991, with its main factory in Magna Via, Polokwane, since 2010.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- reconnect-day-spa-fauna-park (researched)
UPDATE businesses SET description = 'Reconnect Day Spa is a family spa on McDonald Avenue in Fauna Park, Polokwane, with a Pretoria branch as well. Its treatments include body massages, facials, body scrubs and wraps, an infrared sauna, hot stone and deep tissue massages, and special treatments for guests.

The spa offers customised packages for birthdays, anniversaries and family celebrations, along with kiddies spa and mom-and-daughter packages. The business says it has been operating since 2010 and describes its staff as friendly, professional and passionate about making every customer feel special. The Polokwane branch is at 94 McDonald Avenue in Fauna Park, behind Savannah Mall.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://reconnectdayspa.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'reconnect-day-spa-fauna-park' AND description = 'Reconnect Day Spa is a day spa on McDonald Avenue in Fauna Park offering body scrubs and wraps, an infrared sauna, hot stone and deep tissue massages, facials, and family spa packages.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- s2-electrical-welgelegen (researched)
UPDATE businesses SET description = 'S² Electrical is an electrical contractor in Welgelegen, Polokwane, handling domestic to industrial installations and electrical contracting. In addition to general electrical work, the company can carry out large contracts with electrical consultants, and it is certified to design and install solar power systems.

The business says it is an authorised company, registered with the relevant authorities, and that it takes pride in quality workmanship and service excellence. Its website also highlights fast delivery and 24/7 customer service, and its mission statement commits the team to productive, proactive and accountable work without compromising safety and reliability. The company is at 135 General Kritzinger Street.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://s2electrical.co.za'), description_enriched_at = datetime('now') WHERE slug = 's2-electrical-welgelegen' AND description = 'S2 Electrical is an electrical contractor on Genl Kritzinger Street in Welgelegen, handling domestic, farm and industrial electrical installations and maintenance, and is also certified to design and install solar power systems.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
