-- content-upgrade:polokwane:026: 4 descriptions (3 deferred, no SQL), generated by scripts/content-upgrade/to-sql.mjs
-- kurumba-lodge-hospark (researched)
UPDATE businesses SET description = 'Kurumba Lodge in Polokwane offers luxury accommodation, fine dining and conference facilities in one place. Its 28 ensuite rooms are well appointed with modern amenities, and its self-catering units sit in a garden that the lodge describes as a private oasis.

The restaurant serves fine food and wine, and Jouba''s Pub offers a casual lunch, after-work drinks and live sports. Guests can also book intimate seated dining, and the lodge says it welcomes walk-in visitors as well as advance bookings. Conference and function facilities cater for year-end celebrations, weddings, birthday parties and productive business meetings.

The lodge says safety and comfort come first, with its own reservoir and a backup generator to keep services running. Wi-Fi, laundry and ironing services are included, and the lodge is in the Hospital Park area of Polokwane.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://kurumba.co.za'), description_enriched_at = datetime('now') WHERE slug = 'kurumba-lodge-hospark' AND description = 'Kurumba Lodge is a guest house and conference venue in Hospital Park offering en-suite bedrooms alongside presidential, exclusive and honeymoon suites, plus a self-catering unit set in a manicured garden with a private braai area; it also has an on-site restaurant and conference rooms that can host functions and small weddings.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- girasole-energy-superbia (researched)
UPDATE businesses SET description = 'Girasole Energy is a solar energy supplier in Polokwane, Limpopo, established in 2015. Its range covers solar panels, batteries, grid-tie inverters from 5kW to 100kW, hybrid and backup systems, solar kits and solar pumps, along with accessories.

The business says it grew out of an electrical motor rewinding business that has operated for more than 50 years, and it describes itself as an official partner of S and P Power Units, a Gauteng company with more than 22 years of solar experience. Its website says it uses high-end products from European suppliers and lists brands including Canadian Solar, Fronius, Blue Nova, Freedom Won and Hoppecke.

Recent projects listed on the website include an 8kWp grid-tie SMA system and semi off-grid hybrid systems for homes, and the company is based in Superbia, Polokwane.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://girasole.co.za'), description_enriched_at = datetime('now') WHERE slug = 'girasole-energy-superbia' AND description = 'Girasole Energy is a Polokwane solar supplier and installer, established in 2015 and grown out of an electrical motor rewinding and generator maintenance business with over 50 years'' history; it supplies and installs solar panels, batteries and inverters, manufactures solar panel framework, and is an official partner of Gauteng-based S&P Power Units.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- marlot-guest-house-hospark (researched)
UPDATE businesses SET description = 'Marlot Guest House is a Polokwane guesthouse offering luxurious accommodation in the heart of the city. It is aimed at business visitors and travellers exploring Limpopo, and the website describes its rooms as uniquely decorated with tranquil surroundings.

All rooms have DStv Open View, a mini bar fridge, tea and coffee facilities and air conditioning, and they are serviced daily. Breakfast is served each morning, and guests can use the swimming pool. The guesthouse also has a fully equipped function venue that seats 30 people, and its board room can accommodate up to 30 delegates for business meetings or group breakaways.

The guesthouse is close to the main access roads, and its website offers a photo gallery and 360-degree virtual tours before booking.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.marlot.co.za'), description_enriched_at = datetime('now') WHERE slug = 'marlot-guest-house-hospark' AND description = 'Marlot Guest House is a Hospital Park guest house with air-conditioned single, double and family rooms set in a manicured garden, each with a private entrance and en-suite bathroom; guests can also use an outdoor pool, sun terrace and games room, with a restaurant serving African cuisine and a bar on site.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- forty-4-on-hoog-capricorn (researched)
UPDATE businesses SET description = 'Forty 4 on Hoog is a boutique guesthouse in Polokwane with four spacious, luxurious suites, run by its owners, who have more than 30 years of experience in hospitality. The website describes the stay as soft luxury, with a welcome based on warm friendship and true hospitality.

The suites range from a 24 square metre junior suite, aimed at business travellers and fitted with a king bed and walk-in shower, to a 48 square metre junior deluxe suite and a 75 square metre king deluxe suite. The king deluxe suite has a lounge, a flat-screen television with a full DStv package, a bio-ethanol fireplace and a fresh fruit platter. Super king and presidential suites are also offered, and the suites described above are air-conditioned.

Guests can use the swimming pool and the garden, and the business is located on Hoog Street in the Capricorn area of Polokwane.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://forty4onhoog.co.za'), description_enriched_at = datetime('now') WHERE slug = 'forty-4-on-hoog-capricorn' AND description = 'Forty 4 on Hoog is a 4-star, adults-only guest house set around an outdoor swimming pool and garden, with suites ranging from Junior Suites to a King Deluxe Suite with fireplace and a Presidential Suite with a kitchenette. Guests get a full English or Irish breakfast, free WiFi, private parking and full-day security.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
