-- content-upgrade:polokwane:020: 6 descriptions (44 deferred, no SQL), generated by scripts/content-upgrade/to-sql.mjs
-- tony-turner-agencies-ladine (researched)
UPDATE businesses SET description = 'The agency is a family-owned business established in 1994 that exports, sells and distributes a range of goods, mainly for the irrigation and construction industries. It supplies agricultural and industrial pumps, including centrifugal and peripheral pumps, submersible borehole pumps, fountain pumps and sewage and drainage pumps, alongside landscape and agricultural irrigation solutions. Its catalogue also covers piping, pipe fittings, industrial hoses, filters and purification products, JoJo tanks and garden fittings, and plastic sheeting.

The business concentrates on the agricultural and construction sectors and sells products for a number of manufacturers and importers. Its homepage describes a commitment to helping customers grow since 1994. The agency is based in Polokwane, the capital of Limpopo, and buyers looking for pumps, piping or irrigation equipment in the area can source them from here.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://ttagencies.co.za'), description_enriched_at = datetime('now') WHERE slug = 'tony-turner-agencies-ladine' AND description = 'Tony Turner Agencies is a family-owned business, established in 1994, that exports, sells and distributes irrigation and construction products -- piping, fittings, industrial hoses, irrigation equipment and plastic sheeting -- from Ladine.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- wound-clinic-hospark (researched)
UPDATE businesses SET description = 'The Wound Clinic is an advanced wound care practice in Polokwane, founded in 2008 to meet the growing need for post-operative and chronic wound care. Its aim is the treatment and rehabilitation of complex wounds, and it treats different types of wounds on a daily basis. Patients can be on private or public medical aid, and the clinic works with product manufacturers to keep up with the latest wound care technology.

Advanced wound care is given by trained and experienced staff who have had ongoing training with specialists over the past decade. The clinic consults a multidisciplinary team that includes general practitioners, physicians, plastic and general surgeons, orthopaedic specialists, physiotherapists, occupational therapists, podiatrists, dieticians and diabetic centres. Its staff are members of WHASA.

Services are offered at 71 Burger Street in Hospital Park, and patients can book an appointment through the website.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://wound-clinic.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'wound-clinic-hospark' AND description = 'Wound Clinic is a specialist wound-care clinic in Polokwane, founded in 2008 to provide advanced post-operative and chronic wound treatment, with staff belonging to the Wound Healing Association of Southern Africa (WHASA).' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- becker-attorneys-bendor (researched)
UPDATE businesses SET description = 'The firm describes itself as a next-generation law practice, made up of business lawyers who serve small and medium-sized enterprises as well as individuals. It provides tailored, integrated legal services across a wide range of practice areas, and says it is built to fit each client''s needs rather than a standard template. Its team has over 15 years of experience.

Clients are offered cost certainty, with a reasonable and predictable price rather than billing by the hour. Meetings are arranged around each client''s day, and much of the work can be completed online, by email, by telephone or by video conference. The firm builds its service around technology, which it sees as a way to improve how clients are served.

The office is in Bendor, Polokwane, and suits start-ups, growing businesses, established organisations and entrepreneurs with bigger goals.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://beckerinc.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'becker-attorneys-bendor' AND description = 'Becker Attorneys is a business-law firm in Bendor serving small and medium enterprises and individuals, with practice areas spanning arbitration, mediation and conciliation, commercial and consumer law, estates, trusts and wills, and litigation.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- bendor-bayete-bendor (researched)
UPDATE businesses SET description = 'Bendor Bayete provides luxury self-catering overnight accommodation in the upmarket suburb of Bendor, Polokwane. Its furnished, en-suite self-catering suites are aimed at family visitors, corporate guests, business executives, people relocating to the area and international travellers. Secure parking and DSTV are available, and the business offers affordable rates on its furnished suites for companies.

The accommodation is close to banks, shops, hospitals and malls, and the website lists the Mall of the North, a Medi Clinic in Polokwane, Peter Mokaba Soccer Stadium, the airport and Savannah Mall as places about five minutes away. For big sporting or school events in the Polokwane area, guests can contact the business for their self-catering needs.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.bendorbayete.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'bendor-bayete-bendor' AND description = 'Bendor Bayete Self-Catering Accommodation is a guesthouse on Pierre Street in Bendor with a front desk open daily from 07:00 to 19:00, check-in from 14:00 and check-out by 12:00.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- ingwe-waste-management-dalmada (researched)
UPDATE businesses SET description = 'Ingwe Waste Management is a Level 1 BBBEE, 100% Black-owned company that has been operating for over 20 years. It collects, disposes of and recycles waste in Limpopo, Gauteng, Mpumalanga and North West, with weekly or scheduled pickups, flexible rescheduling, skip bin rentals and handling for high-volume and bulk waste.

The company also handles hazardous and industrial by-products, secure collection of medical and clinical waste, and tailored waste management plans for compliance. Recyclables are separated on site and processed at an in-house recycling facility, and the company reports a recycling rate of 85% and more than 50,000 tons of waste collected. Its website also highlights eco-friendly disposal, and the business is based in Dalmada, Polokwane.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.ingwewaste.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'ingwe-waste-management-dalmada' AND description = 'Ingwe Waste Management is a 100% Black-owned waste management company based at Plot 6 Geluk in Dalmada, providing residential, business and municipal waste collection, recycling, sanitary landfill management and cleanup services across Limpopo.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- ivory-lodge-bendor-park (researched)
UPDATE businesses SET description = 'Ivory Lodge is a 28-room lodge offering luxury overnight accommodation as well as bed and breakfast lodging. Traditional breakfasts are prepared daily and can be adjusted to guests'' dietary requirements. The lodge also has conference facilities and offers outside catering for breakfasts, luncheons, cocktail parties and private or corporate events.

The property sits near shopping centres and the city centre but outside the daily traffic, and its website says security is a priority. Travellers heading to Zimbabwe, Kruger National Park and Botswana often use it as a stop-over, and guests can visit nearby attractions such as Magoebaskloof Rainforest, the Bakoni Malapa cultural museum, Ebenezer Dam, Debegeni Falls and the Zebediela citrus estate. The lodge describes itself as an ideally located base in the heart of Limpopo.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://ivorylodge.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'ivory-lodge-bendor-park' AND description = 'Ivory Lodge Bendor is a 27-room guesthouse on Van Niekerk Street in Bendor Park, with air-conditioned rooms, private bathrooms and free WiFi, an outdoor swimming pool, braai facilities and a 24-hour front desk.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
