-- content-upgrade:polokwane:024: 12 descriptions (38 deferred, no SQL), generated by scripts/content-upgrade/to-sql.mjs
-- ruby-stone-boutique-hotel-fauna-park (researched)
UPDATE businesses SET description = 'RubyStone Boutique Hotel blends a classic suburban residential feel with a cool, urban style in the quiet suburb of Fauna Park, Polokwane. Its website describes it as a relaxed place to unwind, with easy access to the major shopping malls and other amenities.

The hotel offers Wi-Fi hotspots, air conditioning, car parking, conference facilities and a restaurant and bar. RubyStone''s own in-house restaurant, Ruby Steakhouse, serves the guests, and the staff say they can cater for business travellers, special occasions and holidays alike. The website''s gallery shows the foyer, boardroom and bedrooms, and rooms are presented as a home away from home. It is in Bekker Street, Fauna Park.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.rubystone.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'ruby-stone-boutique-hotel-fauna-park' AND description = 'Ruby Stone Boutique Hotel is a boutique hotel in Fauna Park with air-conditioned rooms featuring mini-bars, tea/coffee facilities and private balconies, alongside an on-site steakhouse serving African and Western dishes, a lounge, spa treatments and free Wi-Fi.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- all-seasons-function-hire-futura (researched)
UPDATE businesses SET description = 'All Seasons Function Hire rents marquee tents and waterproof stretch tents for events in Futura, Polokwane. The company describes its marquees as suitable for events of all sizes and types, providing space for guests, exhibitors and vendors.

Its services include ablution facilities so guests have clean restrooms, and a trained team that goes to the event site to set up the marquee, arrange chairs, tables and stages, and dismantle and remove everything afterwards. The business is an affiliate of Vyna Tarp, a PVC and canvas tarpaulin manufacturer, and it invites customers to inspect the products in Polokwane. The company says it aims to offer the best quality products and services to its clients.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://allseasonsfunctionhire.co.za/about/', '$[#]', 'https://allseasonsfunctionhire.co.za/contact/'), description_enriched_at = datetime('now') WHERE slug = 'all-seasons-function-hire-futura' AND description = 'All Seasons Function Hire is an event and tent hire company in Futura, supplying marquee and waterproof stretch tents with full setup, arrangement and dismantling of chairs, tables and staging, plus furniture, decor and mobile toilet hire for functions.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- bosveld-communications-annadale (researched)
UPDATE businesses SET description = 'Bosveld Communications is a Polokwane-based internet service provider that supplies fixed-wireless, satellite and fibre internet to homes, businesses and remote farming areas across Limpopo. It sells uncapped, unshaped and unthrottled connectivity, and its website lists fibre, Wi-Fi sign-up and portal login for existing customers.

The company also provides per-second VoIP calling, CCTV surveillance systems, computer, laptop and server sales, support and service, and custom wired and wireless network set-up. Its VoIP is billed per second at what the company describes as the best rates. An independent directory describes it as running its own registered network rather than simply reselling connections. Its head office is in Polokwane, and it serves customers across Limpopo.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://bosveld.co.za', '$[#]', 'https://whichvoip.co.za/listing/bosveld-communications/'), description_enriched_at = datetime('now') WHERE slug = 'bosveld-communications-annadale' AND description = 'Bosveld Communications is a Polokwane-based wireless internet service provider that has operated since 1994, offering uncapped wireless broadband, fibre and VoIP/hosted PBX connectivity alongside CCTV, networking and IT support, serving Polokwane and further afield into Limpopo toward Lephalale.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- mabotja-thabo-attorneys-polokwane-central (researched)
UPDATE businesses SET description = 'The firm is a Polokwane attorneys'' practice that serves clients in person and remotely, with consultations by appointment and support by phone, email or WhatsApp. Its services cover personal injury and RAF claims, family law and maintenance, divorce, estate planning, general and civil litigation, debt collection, defamation claims, corporate and commercial law and bail applications.

The firm says it takes the time to understand each client''s circumstances and tailors its approach to the best possible outcome. It serves individuals and families, including those who need a community trust attorney or guidance on complex litigation. Walk-in appointments are available at its Jorissen Street office in Polokwane.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.mabotjatinc.com'), description_enriched_at = datetime('now') WHERE slug = 'mabotja-thabo-attorneys-polokwane-central' AND description = 'Mabotja Thabo Attorneys Inc. is a law firm in Polokwane Central handling personal injury and RAF claims, family law and divorce, debt collection, estate planning and wills, civil litigation, defamation claims, corporate and commercial law, and urgent bail applications.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- masamah-graphics-mankweng (researched)
UPDATE businesses SET description = 'Masamah Graphics offers graphic design, printing, website design and development, and photo and video editing from a stall at the Mankweng Business Centre Complex. Its graphic design work includes logos, posters, banners, calendars, book covers, business cards, clothing designs and illustration.

The business also prints paper products and designs and develops websites, covering page architecture, content creation and graphic design. Its photo and video editing is prepared for use on social media, websites and printed materials, and it also creates photo and video adverts to help clients promote their businesses. The business says it offers paper printing for now and plans to expand its printing to a larger scale.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.masamahgraphics.com'), description_enriched_at = datetime('now') WHERE slug = 'masamah-graphics-mankweng' AND description = 'Masamah Graphics is a graphic design and printing studio at the Mankweng Business Center Complex (Gate 2), offering logo, poster, banner, calendar, business-card and clothing design alongside desktop publishing, paper printing, website design and development, and photography/video editing services.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- pietersburg-lodge-ivy-park (researched)
UPDATE businesses SET description = 'Pietersburg Lodge is a hotel in the Ivy Park suburb of Polokwane, with 48 luxurious rooms. The rooms are air-conditioned and have satellite television, and the lodge is about 3 km from the Peter Mokaba Stadium.

The lodge has a restaurant and a pub, and it offers a braai area and conference facilities. Its website describes comfort and hospitality, with luxurious rooms, modern conference spaces and delectable dining, and it lists local attractions for guests to visit. Rooms are priced from R1,200 a night for two people sharing, and bookings can be made through its website or by phone and email. The lodge is at 4 Pringle Street.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.pblodge.co.za/contact.php', '$[#]', 'https://www.sa-venues.com/visit/pietersburglodge/'), description_enriched_at = datetime('now') WHERE slug = 'pietersburg-lodge-ivy-park' AND description = 'Pietersburg Lodge is a 48-room guesthouse in Ivy Park with air-conditioned rooms, DStv, a bar fridge, tea/coffee facilities and Wi-Fi, plus an on-site restaurant and pub, secure parking, a fire pit and braai facilities, and a 24-hour front desk.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- sidze-guest-house-moregloed (researched)
UPDATE businesses SET description = 'Sidze Guest House is a guesthouse in the heart of Polokwane, offering luxurious accommodation for business and leisure travellers. Its suites include a standard suite, a deluxe suite, a deluxe long-stay suite and an exquisite option, each with air conditioning, a large television with DStv, and tea and coffee facilities.

The guesthouse serves nutritious, flavourful meals, and guests can reach the city''s major shopping malls and attractions nearby. The website describes the stay as a sanctuary of comfort and calm. Standard suites are priced from R750 a night and deluxe suites from R850 a night, and the guesthouse is at 82 Johnson Street, Polokwane Extension 4.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'http://www.sidzeguesthouse.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'sidze-guest-house-moregloed' AND description = 'Sidze Guest House is an en-suite guest house in Moregloed with double, queen and king rooms, a conference facility for up to 40 delegates and a smaller boardroom, positioned a few kilometres from Polokwane''s CBD and Mall of the North.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- jason-stander-optometrists-bendor-park (researched)
UPDATE businesses SET description = 'The practice is an optometry clinic at the Cycad Centre in Bendor, Polokwane, offering comprehensive eye exams, contact lens fitting and designer eyewear. It says it has served Bendor for more than a decade and uses state-of-the-art technology and equipment to provide tailored eye care.

The clinic''s services include general eye exams, eye disease diagnosis for conditions such as glaucoma, cataracts and diabetic retinopathy, and spectacle lens advice and enhancements. Its frame range runs from affordable everyday options to designer brands such as Ray-Ban, Oakley, Gucci and Tom Ford. A two-for-one promotion on eye exams is advertised, and visitors can book online.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://jsoptom.co.za'), description_enriched_at = datetime('now') WHERE slug = 'jason-stander-optometrists-bendor-park' AND description = 'Jason Stander Optometrists is a family eyecare practice at Cycad Centre with over a decade in Polokwane, offering comprehensive eye exams and a wide range of eyewear from designer brands such as Tom Ford, Gucci and Ray-Ban alongside more affordable options.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- maizey-plastics-superbia (researched)
UPDATE businesses SET description = 'Maizey Plastics Polokwane is a branch of a family-owned plastics supplier with a history stretching back to 1950. The branch distributes signage and engineering plastics to the signage, marine, agriculture, engineering and architecture industries.

Its signage range includes acrylic sheets, polycarbonate, pigmented vinyl, heat transfer films, foam boards, ACM, ABS and Correx, as well as aluminium lightbox and LED profiles and channel letters. The business says it offers personalised service, integrity and customer satisfaction, and it has been a trusted supplier of quality products for more than 75 years. The company says it works across industries and specialises in the distribution of signage and engineering materials, with a range chosen to suit the needs of each sector. Its website highlights a comprehensive range of quality products, and the branch serves its customers from Superbia, Polokwane.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.maizey.co.za/branch-details/maizey-polokwane-branch/'), description_enriched_at = datetime('now') WHERE slug = 'maizey-plastics-superbia' AND description = 'Maizey Plastics Polokwane is a branch of Maizey Plastics, one of Southern Africa''s largest independently-owned suppliers of semi-finished thermoplastics, stocking signage materials (acrylic, polycarbonate, ACM), engineering plastics (nylon, polypropylene, PTFE) and vehicle wrapping films from its Nikkel St premises in Superbia.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- thomsons-body-107-superbia (researched)
UPDATE businesses SET description = 'Thomsons Body 107 is a panel beating and spray painting business with more than 30 years of experience in auto body repair. Its services cover accident damage, insurance repairs, chassis repair and a fresh new look for a vehicle.

The business says it restores vehicles to their original condition, in both appearance and performance, and that its work meets manufacturer standards. It is approved by insurance companies and vehicle manufacturers, and it lists those approvals on its website. The business says it brings vehicles back to life with precision, care and craftsmanship, and that its team has the skills and technology to get customers back on the road safely. The workshop is in Superbia, Polokwane.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://thomsons107.co.za'), description_enriched_at = datetime('now') WHERE slug = 'thomsons-body-107-superbia' AND description = 'Thomson''s Body 107 is a Chery-approved panel beating and spray painting workshop on Mangaan Street in Superbia, a family-run auto body business operating for over 30 years and recognised as Polokwane''s best panel beater in a 2025 local readers'' choice award.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- tambati-overnight-and-conference-center-penina-park (researched)
UPDATE businesses SET description = 'Tambati Overnight and Conference is a bed and breakfast in Penina Park, Polokwane, offering affordable yet luxurious overnight accommodation with 17 fully furnished rooms. The property has lush gardens, a sparkling pool, a children''s play area and recreation areas, and it is set just outside the noise of the city.

Its bed and breakfast suits business travellers, backpackers, tourists and holidaymakers, and guests can book single, double, twin and luxury rooms. The property offers ample parking and security, and its website describes a warm and inviting atmosphere with efficient service. Tambati also has a fully featured conference facility for meetings and events.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://tambati.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'tambati-overnight-and-conference-center-penina-park' AND description = 'Tambati Overnight and Conference Center is a guesthouse in Penina Park offering ground-floor rooms with private bathrooms, air-conditioning and garden views, alongside a garden sun terrace, outdoor swimming pool and a fully equipped conference facility for meetings and events.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
-- orchid-aesthetic-clinic-sterpark (researched)
UPDATE businesses SET description = 'Orchid Aesthetics is an aesthetic clinic in Sterpark, Polokwane, offering botox and tissue fillers for ageing skin and facial rejuvenation. Its treatments also include anti-ageing solutions, acne treatment, chemical peels, cellulite treatment, medical weight loss, detox programmes and vitamin drips for IV hydration.

The clinic lists prices for some treatments on its website, including crow''s feet at R2,100, brow lifts from R1,400 and nasolabial lifts from R2,800. Patients are asked to book an appointment by phone or email, or through the online portal. The clinic presents several of its treatments as non-surgical options for people who want to feel good about their appearance.', source_urls = json_insert(CASE WHEN json_valid(source_urls) AND json_type(source_urls) = 'array' THEN source_urls ELSE '[]' END, '$[#]', 'https://www.orchidaesthetics.co.za/'), description_enriched_at = datetime('now') WHERE slug = 'orchid-aesthetic-clinic-sterpark' AND description = 'Orchid Aesthetic Clinic is a medical aesthetics clinic in Sterpark, Polokwane, offering treatments including Botox and dermal fillers, thread lifting, chemical peels, microneedling, PRP therapy and medical weight-loss programmes, alongside beauty services such as massages, waxing and nail treatments.' AND description_enriched_at IS NULL AND length(COALESCE(description, '')) < 700
  AND owner_user_id IS NULL AND COALESCE(subscription_tier, 0) = 0 AND COALESCE(origin, '') != 'owner_submitted'
  AND status = 'published' AND closed_at IS NULL AND is_test = 0
  AND custom_blocks IS NULL AND page_html IS NULL
  AND NOT EXISTS (SELECT 1 FROM business_claims c WHERE c.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.business_id = businesses.id)
  AND NOT EXISTS (SELECT 1 FROM business_photos p WHERE p.business_id = businesses.id);
